keeperfx/lang/speech_chi.po

Add lang/speech_chi.po, based on Chinese (Simplified) speech

---

keeperfx/lang/gtext_chi.po

Many improvements for translations.
Some details may still need to be polished.

update zh-CN translations

---

lang/gtext_eng.pot
lang/gtext_fre.po

Added a lot of missing translations
Rebased the french .po from the POT with Poedit ( automatic line rebasing)
Corrected some grammar mistakes in the POT

PO-fr + POT updates

---

src/creature_states.c
src/creature_states.h
src/creature_states_hero.c
src/keeperfx.hpp
src/main.cpp

- Heroes will exit through the hero gate for a bit
- Creatures will just flee to some random location in their dungeon instead

Units move out of cave in if already at flee position

---

src/lvl_script.c
src/lvl_script.h

-CAST_SPELL
-CAST_SPELL_ON_CREATURE
-CAST_SPELL_AT_LOCATION

CAST_SPELL script commands

---

src/magic.c

Like you used to, which should fix #851

Can no longer use possession without the spell

---

src/config_creature.h
src/config_magic.h
src/creature_graphics.c
src/creature_states.c
src/engine_render.c
src/thing_corpses.c
src/thing_data.h
src/thing_effects.c
src/thing_effects.h
src/thing_objects.c
src/thing_objects.h
src/thing_shots.c
src/thing_traps.c
src/thing_traps.h

Renamed some fields and function related to drawing and transparency

comments and renaming related to transparency

---

src/config_terrain.c
src/creature_states_rsrch.c
src/frontmenu_ingame_tabs.c
src/lvl_script.c
src/player_comptask.c
src/room_data.c
src/room_entrance.c
src/room_library.c

ROOM_AVAILABLE(ALL_PLAYERS,TREASURE,    2,0) :arrow_left:  that may be either researched or captured
ROOM_AVAILABLE(ALL_PLAYERS,GRAVEYARD, 3,0) :arrow_left:  that room become available only when captured
ROOM_AVAILABLE(ALL_PLAYERS,TORTURE,      4,0)  :arrow_left:  that room become researchable only when captured
#666

ENABLED flag for ROOM_AVAILABLE could be 2, 3 and 4 now

---

src/frontmenu_ingame_opts_data.cpp

Text is now displayed well away from the title.

Fixed error dialogue box.

---

src/console_cmd.c

Cheat `!map.pool empty` clear all creatures from a pool/
`!map.pool fly 20` set pool size for files for 20

cmd_map_pool

---

src/dungeon_data.h
src/packets.c
src/player_utils.c
src/room_data.h
src/roomspace.c
src/roomspace.h

one-click-build should do one slab per turn

---

src/event_monitoring.c

It was bug with write after buffer

fix event monitoring for greater good

---

src/bflib_cpu.c
src/bflib_cpu.h
src/main.cpp

It's more useful than the technobabble it currently displays.

Log file now shows your CPU's brand string.

---

src/lvl_script.c
src/lvl_script.h

It can cast non-shot creature spells on the specified creature.

Added USE_SPELL_ON_CREATURE command

---

src/room_util.c

Also extended the string length slightly to reduce the chances of one "overflowing".

Removed room capacity percentage on the query dialogue box

---

src/lvl_script.c
src/lvl_script.h

Two parameters: the player and the health.

Added SET_HEART_HEALTH and ADD_HEART_HEALTH script commands

---

src/lvl_script.c
src/lvl_script.h

Same parameters as SET_FLAG, but the value is the maximum value.

Added RANDOMISE_FLAG script command

---

src/creature_instances.c
src/creature_instances.h
src/front_input.c
src/gui_msgs.c
src/gui_msgs.h
src/magic.c
src/room_data.c
src/room_data.h

There is now a mode to claim enemy and neutral territory and fortify walls in possession.

---

src/creature_instances.c

Claiming path or rooms have different sound.

Added sounds for claiming in possession

---

campgns/lqizgood.cfg
lang/campgns/lqizgood/text_fre.po
pkg_lang.mk

Translations provided by ElClacoS

Good Campaign translated to French

---

src/front_easter.c

Like they did in the original game.

FECKOFF and JLW messages should once again bounce around the screen

---

.github/workflows/PR.yml
.github/workflows/Push.yml
campgns/burdnimp/map00222.txt

And also ignore draft pull requests

Split up the CI workflows to PR and Master commit

---

src/dungeon_data.h
src/lvl_script.c
src/lvl_script.h
src/player_utils.c

Added manufacture script variables

---

src/config.c

Also added ON/OFF alternatives to video scale

Allow 0/1 as Boolean value

---

src/config_creature.c
src/config_creature.h
src/config_crtrmodel.c
src/config_crtrstates.c
src/creature_jobs.c
src/creature_senses.c
src/creature_states.c
src/creature_states_lair.c
src/dungeon_stats.c
src/game_merge.h
src/lvl_script.c
src/main.cpp
src/player_instances.c
src/power_hand.c
src/thing_corpses.c
src/thing_creature.c
src/thing_effects.c
src/thing_list.c
src/thing_objects.c
src/thing_shots.c
src/thing_stats.c

Makes the SET_CREATURE_PROPERTY work on load.
Fixes #1061

Moved CreatureConfig to gameadd

---

.github/workflows/PR.yml

to keep this place clean: https://github.com/dkfans/keeperfx/actions/workflows/PR.yml

Stop commits from draft pull requests showing up

---

Makefile

Add origplus to list of CAMPAIGNS in Makefile

---

prebuilds.mk

this adds Korean character encoding

use po2ngdat ver 1.0.2.31

---

src/config_rules.c
src/creature_states.c
src/game_legacy.c
src/game_legacy.h
src/game_merge.h
src/room_data.c
src/room_util.c
src/thing_objects.c

Should now properly save the value for non-default configs. There was a todo left in the code.

GoldPerHoard rule to function properly from configs

---

campgns/keeporig.cfg
campgns/origplus.cfg
src/creature_instances.c
src/creature_states_gardn.c
src/game_loop.c
src/main.cpp
src/thing_creature.c
src/thing_data.h
src/thing_effects.c
src/thing_shots.c
src/thing_traps.c
src/thing_traps.h

and used enumeration instead of the magic numbers when filled

Named two hit type fields

---

src/creature_states_spdig.c
src/room_data.c
src/room_graveyard.c
src/spdigger_stack.c
src/thing_corpses.c
src/thing_corpses.h
src/thing_creature.c
src/thing_data.h

Should work exactly the same as before. Simply to make some functions more readable than thing.byte_14.

Made corpse_laid_to_rest function

---

lang/gtext_jpn.po
src/vidmode.c

Also shows an error message when failing to switch to the desired resolution.

Resolution is displayed as a message when switching.

---

src/player_instances.c

Fixed #1100: Floating spirit entry height

---

src/console_cmd.c

Could be useful for debugging.

Added option to not unpause the game when loading via console.

---

src/thing_objects.c

Fixed #1129 - Sight of Evil moved to open area

---

src/engine_render.c
src/frontmenu_ingame_map.c
src/gui_parchment.c
src/lvl_script.c
src/lvl_script.h
src/map_blocks.c
src/map_data.c

fix for width > 127  (issue #1126)

fix CONCEAL_MAP script command

---

src/spdigger_stack.c

check_place_to_pickup_gold rewritten

Imps now clean up gold bags

---

src/lvl_script.c
src/lvl_script.h

Also looks nice in the interface.
It would technically still be possible to go over the limit by adding max amounts of money in a quick loop, but at that point the player is simply asking for trouble.

Limited amount of gold to something sensible

---

src/console_cmd.c
src/console_cmd.h
src/lvl_script.c
src/lvl_script.h

To be consistent with other commands them take subtiles as params

Renamed USE_POWER_AT_SUBTILE to USE_POWER_AT_POS

---

src/map_blocks.c

Fixed #997 - Fortify does not include all corners

---

src/lvl_script.c

Example:
`SET_GAME_RULE(DungeonHeartHealth,4000)`

Added DungeonHeartHealth to SET_GAME_RULE script command

---

src/game_loop.c
src/game_merge.h
src/lvl_script.c
src/lvl_script.h
src/map_events.c
src/player_utils.c

For #1199
If there's just a number, it's the game string.

Added HEART_LOST_OBJECTIVE and HEART_LOST_QUICK_OBJECTIVE script commands

---

src/frontmenu_ingame_tabs.c
src/room_workshop.h

Removed MANUFCTR_TYPES_COUNT, as it's now variable

---

src/config_magic.c

Fixed some shot properties not resetting on custom campaigns/packs

---

src/creature_instances.c

Fixed #1235
Also possibly fixed #1236

Fixed #1235 - Dig sound effects

---

src/room_data.c

Health now added together when merging two separate rooms.

Health recalculated on merging rooms

---

src/creature_instances.c

Possession sounds now also outside of possession

---

src/room_garden.c
src/thing_data.h
src/thing_objects.c

Fixed #1251 - Wandering chickens

---

src/roomspace.c

Holding LMB always stays in untag mode

---

src/engine_render.c
src/engine_textures.h
src/game_merge.h
src/lvl_filesdk1.c
src/lvl_filesdk1.h
src/main.cpp

Fixed #1233 - Save custom tilesets

---

src/engine_render.c

Fixed #1234 - Custom tilesets in straight view

---

src/lvl_script.c

Fix #1253 - Crash in heavylog on custom trap script

---

src/custom_sprites.c
src/gui_draw.h
src/vidmode_data.cpp

Fix #1232 - Crashing option sliders

---

src/config_magic.c
src/room_data.c

and you gain the ability to research your lost books back.
Fixes #1265

Spellbooks moved between libraries

---

src/bflib_math.h
src/engine_camera.c
src/engine_camera.h
src/main.cpp

rewrote some camera routines + moved some out of main.cpp to engine_camera.c

rewrote cam routines

---

src/ariadne.c

Fixed #1293 - Units do not sleep centered on their lairs

---

src/front_input.c
src/frontmenu_ingame_tabs.c
src/gui_parchment.c

Zoom the zoombox on the parchment map along with the minimap zoom.
Press +/- to change zoom level.

Zoom the zoombox

---

src/bflib_sound.c
src/game_heap.c
src/sounds.c

made some files use decompiled version of bflib_fileio functions instead of dll version

made some files use decompiled version of bflib_fileio functions

---

src/creature_states.c

I think the payday issues should be fixed this way. It matches how the other states are cleaned up.

Fixed broken payday but different

---

src/creature_states.c
src/thing_creature.c

I've no idea why this happens, but this should fix it.

Fixed creatures dropped on dying becoming neutral.

---

src/thing_creature.c

Corpses and fainted creatures can now be picked up anywhere

---

src/creature_states.c

Event is raised when a creature waits outside a Treasure Room door

---

src/creature_states.c

Tunnellers should no longer seize control in possession

---

src/main.cpp
src/sounds.c

Footsteps of creatures dragging something now play

---

src/front_input.c

Possibly fixes #1338
There may still be issues after changing resolution in possession.

Changing resolution in possession should no longer freeze the game

---

src/bflib_sprfnt.c
src/bflib_sprfnt.h
src/frontend.cpp

The issues:
Missing letter:
Characters cut in half:

Fit text correctly in objective text boxes

---

src/player_instances.c

Swipe sprites are now loaded on passenger controlling

---

docs/data_structure.md
src/actionpt.c
src/config_terrain.c
src/keeperfx.hpp
src/map_blocks.c
src/map_columns.c
src/map_data.c
src/room_data.h

`find_column` moved to .c
Started doc about data structure

find_column moved to .c

---

src/console_cmd.c
src/creature_states_combt.c
src/thing_list.c
src/thing_objects.c
src/thing_stats.c

!thing.move
!thing.info
!mapwho.info

Move things around

---

src/thing_list.c

Fixed IF_CONTROLS all creatures

---

src/frontmenu_ingame_tabs.c
src/thing_creature.c

Fixed pickup buttons not working

---

src/creature_instances.c
src/creature_instances.h
src/creature_states_spdig.c
src/cursor_tag.c
src/dungeon_data.h
src/engine_redraw.c
src/front_input.c
src/game_merge.h
src/magic.c
src/packets.c
src/packets.h
src/packets_cheats.c
src/player_data.c
src/player_data.h
src/thing_creature.c
src/thing_creature.h

Fortifying walls, custom teleport destinations, and dragging things should now work in multiplayer.

Fortifying walls, custom teleport destinations, and dragging things in possession should now work in multiplayer.

---

src/creature_states_tortr.c

Kinky neutral torture units will now also torture forever

---

src/creature_instances.c

Made first person dig behaviour consistent

---

src/engine_redraw.c

Though the difference isn't as noticeable as I thought it would be....

Invisibility icon in possession darkens when creature is visible.

---

src/lvl_script_commands.c
src/lvl_script_lib.h

SET_CREATURE_INSTANCE([creature], [slot], [instance], [level gained])

Added SET_CREATURE_INSTANCE script command

---

src/thing_physics.c

Made blood go splat

---

src/frontend.cpp
src/game_merge.h
src/game_saves.c
src/game_saves.h
src/main_game.c
src/player_utils.c
src/power_specials.c
src/power_specials.h

Transfer multiple units per map

---

src/dungeon_data.h
src/lvl_script_commands.c
src/lvl_script_conditions.c
src/lvl_script_lib.h
src/power_specials.c

that counts how many units the player has transferred

Added a CREATURES_TRANSFERRED variable

---

src/engine_render.c

Scaled health flower the old way in frontview

---

src/lvl_script_commands.c

Warn on incorrect, not on missing optional script values

---

src/front_input.c
src/packets.c
src/packets.h
src/player_data.h

Turning left in possession should be normal again.

---

src/creature_states_hero.c

also fixed the classic bug mode
On the first level of undivine dungeons, the heroes could find red rooms, but not the red hearth, but based their attack on red on that.

Fixed heroes not attacking player with disconnected dungeon

---

src/creature_states.c
src/engine_render.c

- Creatures that became angry from missed payday, that are payed but still angry show regular anger icon now
- Horned reapers show they have gone psycho

Show correct mood icons on angry and psycho

---

src/custom_sprites.c
src/game_saves.c

Fixed map specific custom cursors/icons not reloading

---

src/front_input.c
src/game_saves.c
src/gui_boxmenu.c
src/main_game.c

Cheat menu status is now updated where appropriate

---

src/custom_sprites.c
src/front_simple.h

I am unable to reproduce #1341 but did some improvements.
@Loobinex Could you please test again.

Some guards and validations to fix 1341

---

src/creature_states_spdig.c
src/spdigger_stack.h

also redid check_out_unprettied_drop_place

rewrite check_out_place_for_pretty_behind_door

---

src/engine_render.c
src/engine_render.h

- fixed up the tabbing of display_drawlist
- left some comments
- identified shadows (QK_KeeperSprite)
- identified 'near' textures in 1st person view (QK_Unknown9)
- renamed some QK_ to be more specific

Clarified some display_drawlist stuff

---

src/config_magic.c

Stopped adding power levels on script loops

---

src/thing_objects.c

used for merging gold piles dropped on same spot

rewrite find_base_thing_on_mapwho_excluding_self

---

src/main.cpp

Scale lens, fixes possession screen flicker

---

src/creature_states.c

only if no filled treasure rooms are available and there's offmap gold

Creatures will now take pay from locked empty treasure rooms too

---

src/bflib_sprfnt.c
src/player_compchecks.c
src/room_workshop.c

LONG_MAX doesn't fit inside int

---

src/player_instances.c

Control Panel should no longer be messed up on exiting passenger control

---

src/map_blocks.c

rewrite element_top_face_texture

---

src/frontmenu_ingame_map.c
src/gui_parchment.c

pannel map is still the old way, pannel_map_draw_slabs is different

make purple slabs purple on parchment map

---

src/engine_render.c

Creature levels not shown in first person mode anymore

---

src/creature_states.c

also fixes an overflow in counting amount to persuade

rewrite Move check persuade

---

src/main.cpp

don't really see the point of IsRunningMark and IsRunningUnmark, code suggests it just makes an entry in the registry on start and deletes it when the program closes, why?, and when I check the registry doesn't even seem to actually make it, can I just throw the function out?

throw out IsRunningMark

---

.gitignore
src/packets_input.c
src/player_data.c
src/player_instances.c
src/power_hand.c
src/power_hand.h
src/thing_objects.c

The values from the hand powers in objects.cfg are used now. That also means it's possible to use a custom sprite as the hand.

Sprite and animation speed of hand cursor configurable

---

src/lvl_script.c
src/lvl_script_commands.c
src/lvl_script_commands_old.c
src/lvl_script_lib.c
src/lvl_script_lib.h

ADD_OBJECT_TO_LEVEL([object],[location],[value],[owner]*)
Could for example be used to place backup soul-containers on the map.

Objects placed with script have an owner now

---

src/creature_senses.c

Overshooting was possible
Fixes #1626

Fixed line of sight 3d returning false where it should not

---

src/creature_senses.c

And did the same change for all 3d line of sight functions

Fixed flying units being able to see and shoot through doors

---

src/thing_doors.c

Selling or destroying doors should no longer play a slapping sound

---

src/bflib_math.c
src/bflib_math.h
src/bflib_vidraw.c
src/config_settings.c
src/config_settings.h
src/creature_senses.c
src/engine_camera.c
src/engine_camera.h
src/engine_lenses.c
src/engine_render.c
src/engine_render.h
src/gui_parchment.c
src/keeperfx.hpp
src/light_data.h
src/player_instances.c

This is very work-in-progress. There's a bunch of little things that I'm leaving for later, I've been prioritizing the crashes and trying to get a full zoom out.

Expanded view distance and zoom out

---

src/creature_states.c

bug causes creature to walk to other side of dungeon before attacking another wall

rewrite Move check can damage wall

---

src/creature_instances.c
src/creature_instances.h
src/creature_states.c

Low health Imps should now follow commands for a while

---

src/thing_shots.c

Digging a frail subtile now digs the correct slab

---

src/creature_instances.c

- Damaging the wall creates rock chips
- Visual and Sound effect when the wall is destroyed

Made destroying walls from anger look nicer

---

config/creatrs/imp.cfg

Has always worked, was never added to file.

Added TokingRecovery to config file

---

config/fxdata/magic.cfg
src/config_magic.c
src/config_magic.h
src/creature_instances.c
src/thing_shots.c

Digging in possession should now match digging outside

---

src/engine_camera.c
src/engine_render.c

also adjusted flowers slightly to match the size they were before
https://github.com/dkfans/keeperfx/issues/1699

fix zoomed_range (flags, flowers & gold numbers)

---

src/packets_input.c
src/player_data.h
src/roomspace.c
src/roomspace.h

multiplayer not tested yet, probably needs more work for that

While tagging, also tag any that are inbetween the previously hovered slab and currently hovered slab

---

src/room_data.c

fixes performance issues on specific maps

Stopped locked in heroes from trying to attack

---

src/engine_lenses.c
src/engine_render.c
src/engine_render.h

This fix is a bit of a hack because the underlying issue is difficult to fully understand. But I'm very happy with it.

1st person flicker fix

---

src/map_blocks.c
src/map_blocks.h
src/thing_shots.c

Made diagonal digging in possession possible

---

src/engine_camera.c
src/engine_camera.h
src/engine_render.c

- Renamed my `zoomed_range` variable to `hud_scale`
- Don't show flowers in parchment view and also stop zoom from being applied there
#1732

Stop flowers from displaying in parchment view

---

src/game_legacy.h

Restore play_gameturn

---

src/bflib_render.h
src/bflib_render_gpoly.c
src/bflib_render_trig.c
src/engine_lenses.c
src/engine_render.c

copied from this swars commit
https://github.com/mefistotelis/swars/commit/724a6a23f6008246743493d2c28e89f1880c4f46

named Polypoint fields

---

config/fxdata/objects.cfg

Gave hero gate an AmbienceSound

---

src/actionpt.c
src/actionpt.h
src/game_legacy.h
src/game_merge.h

Game now supports 255 action points

Made 255 action points per level possible

---

src/engine_camera.c
src/engine_camera.h
src/front_input.c
src/player_instances.c

instant camera movement from parchment view

---

src/bflib_basics.c
src/bflib_basics.h
src/frontend.cpp

Lets you print debug messages on-screen. For now just the main menu but can easily be added to in-game as well.

Added LbPrint

---

src/map_blocks.c

Leave unseen things alone when placing terrain

---

src/creature_instances.c
src/main.cpp

Trap removal is now done when the slab is placed

Removed unneeded trap removal lines

---

src/thing_doors.c

Recompute ceiling after placing doors

---

src/light_data.c
src/thing_data.h

fixes #1788, plus another issue where if a book was moved by an imp its light would travel across the map

book light glitches

---

src/frontmenu_ingame_map.c

Scale minimap dotted line

---

src/bflib_video.c

Fixes #1750
Also fixes an annoying issue with positioning on switching windowed modes.

Window is reset on switching windowed resolutions

---

src/light_data.c

Hand light on high ground should always work again

---

config/fxdata/magic.cfg
src/config_magic.c
src/config_magic.h
src/creature_graphics.c
src/main.cpp
src/thing_data.c
src/thing_data.h
src/thing_effects.c
src/thing_shots.c
src/thing_traps.c

Named field_7 'hidden_projectile' and made it configurable as a shot property.

Made invisible shots configurable

---

src/engine_render.c

fix minimap icons when frameskipping

---

src/engine_render.c

Force wibble in possession mode

---

src/power_process.c

Creatures in custody are now released when transported by Armageddon

---

src/packets.c

Apply camera flip fix to only FrontView

---

src/frontmenu_options.c
src/lvl_script.c
src/map_locations.c

Replaces itoa calls with regular snprintf

itoa is non-standard

---

src/lvl_script.c

Replaces ltoa calls with regular snprintf

ltoa is non-standard

---

src/bflib_datetm.cpp
src/gui_frontbtns.c

Replaced timeGetTime calls with LbTimerClock_1000.

timeGetTime is non-standard

---

src/bflib_basics.c
src/bflib_basics.h
src/front_network.c
src/lvl_script.c

Replaced calls to strupr with equivalent implementation.

strupr is non-standard

---

src/bflib_basics.c
src/bflib_basics.h
src/config.c

Replaced calls to strlwr with equivalent implementation.

strlwr is non-standard

---

src/ariadne_wallhug.c
src/engine_render.c

Found some non-standard data types and replaced them with standard equivalent ones.

removed nonstandard data types

---

src/game_merge.h

Removed duplicate definition of TRAPDOOR_TYPES_MAX

---

src/creature_instances.c
src/thing_creature.c

Shots should no longer get stuck in a wall when fired inside one

---

src/frontmenu_ingame_map.c

with extra zoom out, I find it harder to find where I am, so I made the dotted line be more accurate.

Dotted minimap line starts closer to the center

---

src/packets_input.c

fix another tagging issue when moving cursor over gui panel

---

src/thing_effects.c

Fixes #1890
Co-Authored-By: Sim <68837817+SimLV@users.noreply.github.com>

Slow effect goes up and down now

---

src/config.h
src/keeperfx.hpp
src/main.cpp
src/music_player.c
src/music_player.h
src/sounds.c

Music source is no longer saved in save files

---

src/creature_states_combt.c

Clear collided door value on cleanup door combat

---

src/engine_camera.c
src/frontmenu_ingame_map.c
src/frontmenu_ingame_map.h
src/frontmenu_ingame_tabs.c
src/power_hand.c
src/thing_navigate.c

- stopped minimap interpolating pixels incorrectly when exiting parchment view
- fixed #1898
- fixed #1899

Minimap interpolation fixes

---

lang/gtext_jpn.po

The dwarves' names now match the English version

Renamed Japanese Tunneller

---

src/bflib_math.c
src/bflib_math.h
src/engine_render.c

It's better than before but it may still have minor issues.

partial fix to interpolated angles

---

src/thing_creature.c

Lightning and Drain now work properly again

---

src/engine_camera.c
src/engine_camera.h
src/engine_render.c
src/front_input.c
src/main.cpp
src/packets.c
src/packets_input.c
src/player_instances.c

Fix multiplayer crash

---

src/front_input.c

Always snap north on straight view

---

src/main.cpp

Winner in multiplayer is declared the winner as soon as (s)he wins

---

src/frontend.cpp

No Knight drag cinematic in multiplayer

---

src/engine_render.c

Cancel interpolation if distance to interpolate is too far

---

lib/keeper95_gold.map
src/engine_render.c
src/thing_physics.c

Fixes the root issue causing #1915

Don't slide things through the floor

---

src/roomspace.c

Detected best roomspace should work properly again

---

src/thing_creature.c

Computers cast spells again in battle

---

src/config_creature.c
src/config_creature.h
src/frontmenu_specials.c
src/globals.h
src/gui_tooltips.c
src/map_events.c
src/player_compchecks.c
src/player_comptask.c

part of the work to remove hardcoded CreatureData

Creature type names used from config files

---

.gitignore
.gitmodules
Makefile
enet.mk
src/bflib_enet.cpp
src/bflib_enet.h
src/bflib_network.cpp
src/bflib_network.h
src/front_network.c
tests/tst_enet_client.cpp
tests/tst_enet_server.cpp
tests/tst_fixes.cpp
tests/tst_main.cpp

MP menu item and backend
Was #1949

Enet step 1

---

src/lvl_script.c

Fixed drawfrom on if statements

---

src/frontmenu_ingame_map.c
src/frontmenu_ingame_map.h

fixes #1959
also when pausing the game it caused a lot of minimap issues, not just with the tunnelers, that's now solved too.

Corrected tunneler dots on minimap with delta time

---

src/frontmenu_ingame_tabs.c

Big room icon should now behave properly

---

src/bflib_render_trig.c

Implements the trig function, copied from:
* https://github.com/mefistotelis/swars/blob/master/bflibrary/src/general/poly_trigp.c
* https://github.com/mefistotelis/swars/blob/master/bflibrary/src/general/poly_trigr.c
Required for 64-bit port and VS / MSVC compatibility.

Implement trig functions

---

src/KeeperSpeech.h
src/event_monitoring.c
src/globals.h
src/keeperfx.hpp
src/lvl_script_commands_old.c
src/main.cpp
src/map_blocks.c
src/map_utils.c
src/power_hand.c
src/power_hand.h
src/thing_creature.c

In this PR are a set of changes needed to get the codebase compiling with MSVC. The changes have been commit grouped by the type of change.
The trig implementation has been separated to a different pull request.

Add MSVC compatibility

---

src/creature_instances.c

First-person reinforcing now has the range of digging

---

src/bflib_math.h
src/engine_camera.c
src/light_data.c
src/lvl_script_commands.c

[40x40.zip](https://github.com/dkfans/keeperfx/files/10098207/40x40.zip)
for testing in mapdata.c change these values
`MapSubtlCoord map_subtiles_x = 40*3;`
`MapSubtlCoord map_subtiles_y = 40*3;`
`MapSlabCoord map_tiles_x = 40;`
`MapSlabCoord map_tiles_y = 40;`
and load the attached small map
rendering still very broken, but already fixes some issues

fixes for custom mapsizes

---

src/player_instances.c
src/thing_list.c

Floating Spirit no longer falls to the floor in possession

---

src/engine_render.c
src/front_input.c
src/frontmenu_ingame_map.c
src/frontmenu_ingame_map.h
src/light_data.c
src/light_data.h

changes in front_input fix the rotation bug in posession, were mouse coords, so comparing to map_subtiles_x made no sense
fixed the minimap in src/frontmenu_ingame_map.c
cleaned up some light code, actual issue not yet fixed

more small map fixes

---

src/engine_render.c

fix rendering happening in wrong spot for small maps
and some cleanup
still lots of other stuff that's messed up

fix rendering happening in wrong spot for small maps

---

src/gui_tooltips.c

Fixed tooltip length

---

Makefile
package.mk
pkg_lang.mk
tool_po2ngdat.mk

Should allow -j to work without problems.

Makefile fixes

---

src/map_data.c

fix some slabs not being taggable for mining on small maps

fix some slabs not being taggable for mining

---

src/map_ceiling.c
src/map_columns.c
src/map_utils.c

should fix ceiling in small maps for newly dug tiles,
ceiling_init still in dll, so initial ceiling state will still be wrong

Cleanup ceiling functions

---

src/frontmenu_ingame_tabs.c

Fixes crash on possessing placed floating spirits

Only draw existing portraits

---

src/engine_render.c
src/lvl_filesdk1.c

[map00001.zip](https://github.com/dkfans/keeperfx/files/10147302/map00001.zip)
slx file for the map on #2012

fix custom tilesets for small maps

---

src/frontmenu_ingame_map.c
src/frontmenu_ingame_map.h

fixed small map minimap + did removed some dllimports

fixed small map minimap + did removed some dllimports

---

src/frontmenu_ingame_map.c

fix minimap on non square maps

small maps: fix minimap on non square maps

---

src/engine_render.c

this attempt works on the tall map and the 40x40

fix black polys on small map again

---

src/game_lghtshdw.h
src/light_data.c
src/light_data.h
src/map_blocks.c
src/thing_traps.c
src/thing_traps.h

no functional changes, just cleanup

cleanup light code

---

src/light_data.c

The previous fix made the lighting less smooth.

Redo fix of flickering dynamic lights in delta time

---

src/engine_camera.c
src/engine_camera.h
src/frontend.cpp
src/packets.c

code no longer needed since the render limit was lifed

remove code to zoom in when hiding sidebar

---

src/creature_states.c
src/creature_states_hero.c
src/creature_states_lair.c
src/game_merge.h
src/map_blocks.c
src/map_data.c
src/map_utils.c
src/map_utils.h
src/power_process.c
src/room_util.c
src/slab_data.c

fixes part of small map savegames I missed

also store arounds in gameadd

---

campgns/grkreign.cfg
lang/campgns/grkreign/text_chi.po
lang/campgns/grkreign/text_pol.po
pkg_lang.mk

Added Chinese translations for this campaign.

Create text_chi.po for grkreign campaign

---

campgns/ncastles.cfg
lang/campgns/ncastles/text_chi.po
lang/campgns/ncastles/text_pol.po
pkg_lang.mk

Added Chinese translations for this campaign.

Create text_chi.po for Nikolai's Castles campaign

---

src/gui_parchment.c

Fixed low-res fullscreen map candles

---

src/game_loop.c

HEART_LOST_OBJECTIVE should only display for your own heart

---

src/frontend.cpp

it's a little bit fast on frameskip 1 specifically, but good otherwise

Fix message box being slow during frameskip

---

config/fxdata/magic.cfg
src/config_magic.c
src/config_magic.h
src/gui_tooltips.c
src/lvl_script_commands.c
src/power_specials.c
src/power_specials.h
src/thing_creature.c
src/thing_effects.c
src/thing_effects.h

- Speeches and Effects configurable
- Added Custom box to magic.cfg, string 2005 no longer hardcoded
- Removed magic numbers, used functions and enums

Special boxes pull more information from config files

---

src/lvl_script.c

Fix Drawfrom

---

src/lvl_script.c

DRAWFROM now draws from correct range in IF statements

---

src/thing_objects.c

Fix dungeon heart briefly flickering dark when SKIP_HEART_ZOOM is on

---

src/creature_states_combt.c
src/creature_states_spdig.c
src/creature_states_spdig.h

enables mapmakers to mod their workers how they see fit

Workers use all self buffs while working

---

src/sounds.c

unless the total time is less then 500 seconds

only buzz on bonus timer every 500 seconds (10k gameturns)

---

src/lvl_script.c

Fixes #2212 without breaking #2169

drawfrom can return creatures again

---

src/lvl_script_commands.c
src/lvl_script_lib.h
src/sounds.c
src/thing_data.c
src/thing_data.h
src/thing_navigate.c

HIDE_HERO_GATE(g,n)
g: gate number, positive or negative both work
n: 1= hidden, 0 = visible
Heroes will not use hidden gates

HIDE_HERO_GATE script command

---

src/lvl_script_commands.c

To match CREATE_EFFECT and CREATE_EFFECT_AT_POS script commands

CREATE_EFFECTS_LINE script command accepts effect names too

---

src/creature_states_lair.c

Fix creatures behind their lair in straight view with delta time on

---

src/lvl_script_commands.c

Make sure adding negative health does not overflow hearth health

---

src/lvl_script_conditions.c

Make sure we use the right player in the right command

---

lang/gtext_spa.po

Fixed spanish translate

---

src/lvl_script_commands.c

`CHANGE_CREATURES_ANNOYANCE(PLAYER0,ANY_CREATURE,SET,10000) ` will now make all your units angry.

Fix ANY_CREATURE for CHANGE_CREATURES_ANNOYANCE

---

campgns/ancntkpr.cfg
config/fxdata/magic.cfg
lang/campgns/ancntkpr/text_spa.po
pkg_lang.mk

Also fixed a bug with Custom special tooltip

Added Spanish translation to Ancient Keeper campaign

---

campgns/pstunded.cfg
lang/campgns/undedkpr/landview_eng.pot

- Made sure flags are where the levels are
- Made sure everything is red after you beat the final level
- Speeches added: https://github.com/dkfans/FXsounds/pull/4

Updated Post Undead Keeper landview

---

src/thing_list.c

It was ignoring the NO_ENMHEART_ATTCK  on the new functions

Fixed imps attacking heart

---

src/creature_instances.c
src/globals.h

Reinforcing smoke now shows again

---

src/thing_list.c

To test, try to query the soul container in the top right of this map: [heartmap.zip](https://github.com/dkfans/keeperfx/files/11068920/heartmap.zip)

Make thing-cheats work on large maps

---

package.mk
src/config_creature.c

Fixed common block being needed in creature.cfg

---

lang/gtext_dut.po
src/lvl_script_conditions.c

Makes this script work:
```
MAGIC_AVAILABLE(PLAYER0,POWER_OBEY,1,1)
REM When player finds two must_obey books win the game
IF_AVAILABLE(PLAYER0, POWER_OBEY == 3)
QUICK_INFORMATION(6,"You have found two Must Obey books, now surely the world will obey")
WIN_GAME
ENDIF
```

Do a count for IF_AVAILABLE on powers

---

src/front_input.c
src/roomspace.c

Fixed rotating, zooming, and speedup when building Bridges or selling

---

src/frontmenu_ingame_map.c
src/gui_parchment.c

Shows gems visible on both the map and the parchment map, with a specific color when tagged/marked for digging.

Show gems on parchment and minimaps

---

config/creatrs/imp.cfg
src/creature_control.h
src/thing_creature.c

Skeletons no longer eat, and rebirth documented

---

config/fxdata/effects.cfg

names were incorrect way around, swapped.

swapped names for effects 65 and 66

---

src/thing_shots.c

Melee shots also drain health, cause disease, group and other spell effects

---

lang/levels/classic/text_fre.po
lang/levels/standard/text_fre.po

corrected some french mistakes

PR from my branch of /german

---

src/config_campaigns.c
src/lvl_filesdk1.c

Stopped nagging in log if not all lof-fields are filled

---

src/config_terrain.c
src/room_data.c

Allow custom rooms on mappacks/campaigns

---

config/fxdata/rules.cfg
src/creature_states_rsrch.c
src/dungeon_data.h
src/room_library.c

also enabled the researching of creatures

Allows the research order list to be 64 items long

---

src/thing_effects.c

Copy all fields of afterimages

---

src/config_terrain.c
src/map_blocks.c
src/map_blocks.h
src/power_specials.c
src/room_util.c
src/thing_effects.c

Set correct owner on slab change

---

src/lvl_script_commands_old.c
src/lvl_script_value.c

resets max level for growup creatures

Allow max level 0 on SET_CREATURE_MAX_LEVEL

---

config/fxdata/objects.cfg
src/config_objects.c
src/config_objects.h
src/engine_render.c
src/lvl_script_value.c
src/thing_objects.c
src/thing_objects.h

Both were mistakes from yesterday

Fixed SET_CREATURE_MAX_LEVEL and BUOYANT spelling

---

src/config_terrain.c

Removed slab_attrs data from code

---

src/creature_states_hero.c

Make heroes wait before attempting another task

---

src/main.cpp
src/packets_input.c

Illegal door placements no longer destroy objects there

---

src/lvl_script_commands.c

Made Box128 work for COUNT_CREATURES_AT_ACTION_POINT

---

src/lvl_script_commands.c

also allow names for Crates in SET_DOOR_CONFIGURATION or SET_TRAP_CONFIGURATION

Fixed SET_DOOR_CONFIGURATION

---

src/lvl_script.c
src/lvl_script_commands.c
src/lvl_script_lib.h

NEW_ROOM_TYPE([name])
Works the same way as NEW_TRAP_TYPE and NEW_OBJECT_TYPE

Added NEW_ROOM_TYPE script command

---

src/lvl_script_commands.c
src/thing_objects.c

Fixes #2444
KeeperFX levels only. Classic levels should remain unchanged.

SET_MUSIC now works inside conditional blocks

---

config/fxdata/magic.cfg
src/thing_creature.c
src/thing_effects.c
src/thing_shots.h
src/thing_traps.c

Word of Power Traps no longer stun victims

---

src/power_hand.c
src/power_hand.h
src/thing_creature.c

fixes bug where creature can only level up once while multiple increase level specials are used.

Creatures can now level up in hand

---

config/fxdata/magic.cfg
src/config.c
src/config.h
src/config_magic.c
src/config_magic.h
src/magic.c

Can give modders to option to make some spells work only on imps, or stops some spells from being cast on imps.

Added ONLY_DIGGERS and NO_DIGGERS castability options

---

src/thing_effects.c

Poison Gas Traps now work again

---

src/config_terrain.c
src/config_terrain.h
src/creature_states.c
src/engine_redraw.c
src/gui_tooltips.c
src/lvl_script_commands.c
src/player_compevents.c
src/player_compprocs.c
src/player_computer.c
src/room_entrance.c
src/room_workshop.c

Replace hatchery, lair and workshop rooms with roles

---

src/thing_creature.c

Fixed durations of keeper powers

---

src/room_util.c
src/thing_doors.h

On both the ground and the thing.

CHANGE_SLAB_OWNER works on doors

---

src/creature_battle.c
src/creature_battle.h
src/lvl_script_commands.c
src/lvl_script_conditions.c
src/lvl_script_lib.h

Script variable for active battles

---

src/thing_traps.c

Do not explode tnt traps before they are armed

---

src/front_input.c

Screenshots can be taken when game is paused

---

src/thing_objects.c

force key position to 5

---

config/fxdata/rules.cfg
src/config_rules.c
src/creature_states_train.c
src/game_legacy.h
src/lvl_script_commands_old.c
src/lvl_script_value.c

Limits to which level the training room can train. Different from max level as it still allows level up specials and xp gain through combat.

Added TrainingRoomMaxLevel rule

---

src/creature_states.c

Following creatures ignore payday.

---

src/config_terrain.c

The AI would terminate a room build processes when it found it could neither research or build a room. That meant that if he later got access to that room through a script, he would not build it anymore. 
I now reset the build process to make sure he would consider it.

Make computer players build rooms when they get access from script

---

src/globals.h

Drips from the ceiling now splash again

---

src/globals.h
src/map_blocks.c
src/map_blocks.h
src/player_instances.c

fixes bug of them not being able to cross lava with bridges
fixes #2593

computers can explore one tile by building bridges

---

src/globals.h
src/map_data.c

Alternative fix for ceiling dripping

---

src/player_compchecks.c

Computer players also toggle gui button when enabling prison

---

.vscode/tasks.json

allows you to put trailing commas in launch.json

VSCode tasks.json: dont bother validating json

---

src/creature_states_hero.c

Reverted room attack code, restore performance

---

src/creature_states.c
src/thing_creature.c

Fix bug with prisons eating chickened creatures, and small units

---

src/frontmenu_ingame_tabs.c

Fixed crash on querying invalid creature model

---

src/engine_render.c

Protect against divide by 0 in get_floor_pointed_at

---

src/lvl_script_commands.c

You can test it with this:
```
IF(PLAYER0,GAME_TURN > 80)
HIDE_HERO_GATE(1,1)
ENDIF
IF(PLAYER0,GAME_TURN > 120)
HIDE_HERO_GATE(1,0)
ENDIF
```

Hide light when hero gate is hidden.

---

src/engine_lenses.c

Set field_C in rotpers_parallel

---

campgns/burdnimp.cfg
campgns/lqizgood.cfg
campgns/postanck.cfg
campgns/pstunded.cfg
campgns/revlord.cfg
campgns/twinkprs.cfg
campgns/undedkpr.cfg
lang/campgns/lqizgood/landview_dut.po
lang/campgns/lqizgood/landview_eng.pot
lang/campgns/lqizgood/landview_pol.po
lang/campgns/postanck/landview_eng.pot
lang/campgns/postanck/landview_pol.po
pkg_sfx.mk

Needs:
- https://github.com/dkfans/FXsounds/pull/6
- https://github.com/dkfans/FXsounds/pull/7
- https://github.com/dkfans/FXsounds/pull/8
- https://github.com/dkfans/FXsounds/pull/9
- https://github.com/dkfans/FXsounds/pull/10
- https://github.com/dkfans/FXsounds/pull/11
- https://github.com/dkfans/FXsounds/pull/12

Improved campaign speeches

---

src/slab_data.c
src/slab_data.h
src/spdigger_stack.c

Stop other Imps claiming the tile you are in possession

---

src/bflib_render_trig.c

taken from swars commit
https://github.com/swfans/swars/commit/de130401a7372f493a77ce05d6a82535f79a4adc
https://github.com/swfans/swars/commit/b9728496bffe497f068f65b2b752523e079d5e5a

port crash fix from swars

---

src/room_lair.c

To reproduce an issue, load this map: [levels.zip](https://github.com/dkfans/keeperfx/files/13267640/levels.zip)
Blue bile demon should make a bed in the nearest lair, but it does not. With the fix it does.

Fix distance for best lair

---

campgns/ancntkpr.cfg
pkg_sfx.mk

Comes with: https://github.com/dkfans/FXsounds/pull/14

Added ancient keeper landview speeches in chinese

---

config/fxdata/textureanim.cfg
src/config_slabsets.c
src/config_textures.c
src/engine_arrays.c
src/engine_arrays.h
src/engine_render.c
src/engine_textures.c
src/engine_textures.h
src/game_legacy.h
src/lvl_filesdk1.c
src/main.cpp
src/map_blocks.c
src/map_columns.c
src/map_columns.h

adds a tmapbXXX.dat file to allow custom textures
also implement campaign specific texture files wich resolves #2519

allow more textures

---

src/thing_objects.c

gold hoards created only at storage height

---

src/player_instances.c

Better heart zoom position

---

config/fxdata/objects.cfg
src/config_objects.c
src/config_objects.h
src/console_cmd.c
src/game_legacy.h
src/light_data.c
src/light_data.h
src/lvl_script_commands.c
src/packets_cheats.c
src/thing_data.c
src/thing_objects.c
src/thing_objects.h

cleared up some light related fields
merged ObjectConfig and ObjectConfigStats 
thing_objects_data should eventually also merge into ObjectConfigStats  but haven't done that
removed some hardcoded object data that was already in cfg
Immobile now from cfg, though I don't know what can cause objects to move, so idk if it has an effect

Clear up light and objects

---

src/bflib_datetm.cpp
src/console_cmd.c
src/front_input.c
src/frontmenu_ingame_evnt.c
src/game_legacy.h
src/gui_tooltips.c
src/gui_topmsg.c
src/main.cpp
src/main_game.c
src/packets_cheats.c
src/packets_misc.c
src/player_utils.c
src/scrcapt.c
src/thing_data.c
src/vidmode.c

Fps not in save file

---

src/light_data.c

More divide by 0 light radius protections

---

src/config_magic.c
src/config_trapdoor.c
src/lvl_script_commands.c

Trap light radius same as object light radius

---

src/frontmenu_ingame_tabs.c
src/thing_creature.c
src/thing_creature.h
src/thing_list.c
src/thing_list.h

Also fixed a multiplayer desync.

Only permitted creatures can be queried via cycling through them

---

config/creatrs/imp.cfg

Some fields were still undocumented.
This PR try to document them, plus make the whole thing clearer and consistent as well as fixing minor typos.

Improve documentation on imp.cfg

---

config/keeperfx.cfg
src/config.c
src/power_hand.c
src/power_hand.h

Hand size cfg setting

---

src/creature_groups.h
src/lvl_script.c
src/lvl_script_commands.c
src/lvl_script_commands_old.c
src/lvl_script_lib.c
src/lvl_script_lib.h
src/thing_corpses.h
src/thing_factory.c

ADD_EFFECT_GENERATOR_TO_LEVEL([effect generator name],[location],[range])
Partial implementation of #2801

Added ADD_EFFECT_GENERATOR_TO_LEVEL

---

src/config_creature.c
src/config_crtrmodel.c
src/config_crtrstates.c
src/config_cubes.c
src/config_effects.c
src/config_lenses.c
src/config_magic.c
src/config_objects.c
src/config_powerhands.c
src/config_rules.c
src/config_slabsets.c
src/config_terrain.c
src/config_textures.c
src/config_trapdoor.c

map00001.effects.toml placed together with other map files would be map specific effects.toml

Level specific cfg files

---

src/creature_states_wrshp.c

Units leave workshop when there is no work

---

src/ariadne.c
src/ariadne_edge.c
src/ariadne_edge.h
src/bflib_render.h
src/config_effects.c
src/config_effects.h
src/config_objects.c
src/creature_control.c
src/engine_render.c
src/front_landview.h
src/light_data.c
src/light_data.h
src/lvl_filesdk1.c
src/map_blocks.c
src/packets.c
src/player_utils.c
src/thing_creature.c
src/thing_effects.c
src/thing_factory.c
src/thing_objects.c
src/thing_shots.c
src/thing_traps.c

named some random fields, and scrapped couple unused rendering fields

Named fields

---

src/thing_list.c

Fixes #2903
Bug introduced in #2850

Fixes script criteria not working on ANYWHERE

---

src/sounds.c

Loaded sound filenames are cleared on level exit

---

src/room_util.c

some bitmask caused it to be red instead

fix orange roomflames

---

src/creature_states.c
src/frontmenu_specials.c
src/thing_list.c

Fixed issues related to no specified creature model

---

levels/standard/map00443.txt
src/lvl_script_commands.c
src/lvl_script_commands_old.c
src/lvl_script_lib.h
src/lvl_script_value.c

* `USE_SPECIAL_MAKE_SAFE` renamed to `MAKE_SAFE`
* `USE_SPECIAL_LOCATE_HIDDEN_WORLD` renamed to `LOCATE_HIDDEN_WORLD`
* Kept the two old ones for compatibility reasons
* Added `LEVEL_UP_PLAYERS_CREATURES([player],[creature],[count])` where `[count]` accepts negative values

Restructured LEVEL_SPECIAL script commands

---

src/map_blocks.c
src/map_data.c
src/map_data.h

Creatures still scout land revealed through allies

---

src/config_crtrmodel.c
src/creature_control.h
src/creature_states_spdig.c
src/front_input.c
src/packets.c
src/thing_effects.c
src/thing_navigate.c

- In first person, vertical mouse movements now use maximum turning speed too
- Made the turning code understandable, and some research into the vertical angle limits

Turning speed adjustments

---

src/bflib_math.c
src/creature_control.h
src/engine_render.c
src/front_input.c
src/packets.c
src/player_data.h
src/player_utils.c

I don't think anyone enjoyed that sluggish feeling first person camera, this helps a lot.
Delta time kinda creates a little bit of inertia/acceleration anyway.

Removed camera inertia/acceleration from first person

---

src/config_slabsets.c

Fixed Prison bars

---

src/lvl_script_commands.c
src/lvl_script_commands_old.c
src/lvl_script_value.c
src/thing_list.c
src/thing_list.h

Todo: make it accepts ANY_CREATURE to resolve #2383.

Refactor SET_CREATURE_MAX_LEVEL

---

src/lvl_script_commands.c

It seems that the last slot never actually existed.

Fixed first external sound not playing

---

src/front_input.c
src/magic.c
src/thing_creature.c

Can now teleport to Portals in Possession

---

src/front_input.c
src/packets_cheats.c

Fixed cheat menus in possession

---

src/creature_states.c
src/player_utils.c

On losing, a possessed creature is released

---

src/lvl_script_commands.c
src/lvl_script_lib.c
src/lvl_script_lib.h
src/lvl_script_value.c

USE_POWER_ON_PLAYERS_CREATURES([target_player],[creature],[caster_player],[power],[level],[free])

USE_POWER_ON_PLAYERS_CREATURES script command

---

src/creature_states_lair.c

Disable Recovery if frequency set to 0.

---

src/room_data.c
src/room_util.c
src/room_util.h

Rooms should be properly destroyed

---

config/fxdata/objects.cfg
src/thing_objects.c

Reset UpdateFunction for all objects

---

src/thing_objects.c

Forgot to do this on https://github.com/dkfans/keeperfx/pull/2961

Inactive Heart also use the config for the explosion effect

---

src/frontmenu_ingame_map.c
src/frontmenu_ingame_tabs.c

Fix Minimap Door highlights

---

src/spdigger_stack.c

Only attempt to destroy doors next to players land

---

src/spdigger_stack.c

Separate computer events for separate door targets

---

src/engine_render.c
src/main.cpp
src/packets_input.c
src/player_data.h

Fix tagging around map edge

---

src/gui_msgs.c

Fixed log errors when using QUICK_MESSAGE with non-player icons

---

src/thing_list.c
src/thing_list.h

Query cycling should now work properly

---

lang/campgns/burdnimp/landview_spa.po

I have corrected some words and phrases that were wrong

Revision of translation

---

README.md

README: link to digital edition purchase pages + add CLI to masterserver component description

---

campgns/keeporig/map00104.txt
campgns/origplus/map00104.txt

If you win the map before getting to this point, the script is stopped and you cannot claim the unit anymore. Now you can.

On secret 5 player can get increase level after victory

---

src/player_instances.c

Reset camera inertia when zooming

---

config/fxdata/rules.cfg
src/config_rules.c
src/config_rules.h
src/thing_effects.c
src/thing_list.c

Fix Friendly Fight AreaDamage and AreaRange

---

src/config_effects.h

Increased effect and effect elements limit from 128 to 255

Doubled max effects and effect elements

---

src/lvl_script_commands.c

Fixed RESET_ACTION_POINT

---

src/thing_factory.c

No double gold values on keeperfx maps

---

src/bflib_filelst.c
src/creature_states.c
src/creature_states_spdig.c
src/spdigger_stack.c
src/spdigger_stack.h

- Units without toking recovery will not try toking (good for familiars / summoned units)
- Imps will toke until HealThreshold
- Imps will not refuse jobs while low health
- Imps can be dropped away from assignable jobs to go toking

Reworked toking again

---

src/lvl_filesdk1.c
src/map_blocks.c
src/map_ceiling.c
src/map_ceiling.h
src/power_hand.c
src/thing_creature.c

Creatures dropped close to wall still fall

---

src/config.c

Fixed reading of end-of-file config parameters

---

src/creature_states_scavn.c
src/thing_stats.c

Instead of adding the value... Possible this fix for https://github.com/dkfans/keeperfx/issues/3076

Fix Scavenging Room resetting the counter to work value on switch

---

src/console_cmd.c
src/game_legacy.h
src/lvl_filesdk1.c
src/map_blocks.c
src/map_ceiling.c
src/map_columns.h
src/map_data.c
src/map_data.h

also refactor the Map struct to get rid of the bitshifting required on the data field

Double columns count

---

src/console_cmd.c

command to move view for Dofi.

---

src/thing_shots.c

like ranged drain already does

Melee drain considers armour for health gained

---

src/creature_senses.c
src/map_blocks.c

Fix for website crash report 48

Fixed divide by 0 crash on no longer existing creature

---

levels/classic.cfg
levels/personal.cfg
levels/standard.cfg

Allows users to bundle music with single maps

Enabled media folders for the bundled map packs

---

config/fxdata/spritecolors.toml
src/config_spritecolors.c
src/config_spritecolors.h
src/lvl_script_commands.c
src/map_blocks.c
src/room_data.c
src/thing_objects.c
src/thing_objects.h

adds objects like heartflames and guardpost flags to the spritecolour toml
also implements #3067

make coloured roomobjects more generic

---

src/power_hand.c
src/thing_physics.c
src/thing_physics.h
src/thing_shots.c

Fixed pushing on pickup

---

src/creature_states.c

Restores behavior from original game.

Creatures you assign to lair will sleep even when slapped

---

src/game_saves.c
src/lvl_filesdk1.c
src/lvl_filesdk1.h

Map-specific strings are reloaded with the savegame

---

config/fxdata/rules.cfg
src/config_rules.c
src/config_rules.h
src/light_data.c
src/light_data.h
src/main.cpp

Also made them able to be switched during a game, which can make some cool effects

implement 'GlobalAmbientLight' and 'LightEnabled' game rules

---

src/creature_states.c
src/creature_states_hero.c

Fix heroes standing still

---

src/dungeon_data.c

remove check on neutral for of map gold

---

src/map_blocks.c

Fixed claimed path meshing with neutral path

---

src/lvl_script_commands.c
src/lvl_script_lib.h
src/map_data.c
src/map_data.h

CHANGE_SLAB_TEXTURE([x], [y], [texture], [fill]*)
Resolves #3193

Added CHANGE_SLAB_TEXTURE level script command

---

config/fxdata/terrain.cfg
src/config_terrain.c
src/config_terrain.h
src/room_data.c

If given to Treasure Room, allows it to have full efficiency (100%) even with strange shape.
Useful to make a DK2-like starting Treasure Room around the Dungeon Heart.

Adds new TotalCapacity method

---

src/lvl_script_value.c

``SET_CREATURE_PROPERTY`` clear creature property flag instead of toggling them.

Fix SET_CREATURE_PROPERTY not correctly clearing all flag

---

src/frontmenu_ingame_tabs.c

Information Panel shows dead Keeper faces again

---

levels/standard/map00450.txt
levels/standard/map00456.txt

Death Clock and Shores of Battle.
Comes with these binary files:
[updatedmaps.zip](https://github.com/dkfans/keeperfx/files/15201456/updatedmaps.zip)

Implement roaming creatures on two bundled maps

---

src/engine_render.c

There is no more food in dungeon keeper.

Removed food

---

src/frontmenu_net.c
src/lvl_script.c

+ fixed join crash
+ fixed REM at any line

Fixes for Join Crash. Rem at any line

---

src/magic.c

Don't annoy if CTA does not work

---

src/frontmenu_ingame_opts.h
src/packets_cheats.c
src/thing_data.c

and fixed cheat query on doors

Query cheat shows more info on creatures

---

src/engine_redraw.c

Trap placement displays cursors again

---

src/frontmenu_ingame_tabs.c

Correctly scale payday text for ultra-wide

---

src/game_legacy.h
src/lvl_filesdk1.c
src/map_blocks.c
src/map_columns.h

fixes #3295
unearth version coming shortly

increase map column limit

---

src/api.c

- Implement Acknowledgement ID for request and response packet linking
- Implement multipart JSON processing (allow multiple JSON objects in packet)
- Clear subscriptions on disconnect and server exit
- Add 'unsubscribe_all' API action
- Fix a small recursion bug
- Comment updates

API v2 - implement mutlipart json packets and ack_id

---

src/main.cpp
src/map_blocks.c

helps with casting keeper powers on hero ground

Roaming players have explored ground too

---

src/config_objects.c
src/config_trapdoor.c

https://keeperfx.net/workshop/item/406/morkadash no longer crashes on start

fixed crashed with script commands that add traps

---

src/lvl_script_commands.c

fixes complaining on revealing a player

REVEAL_MAP_LOCATION checks location

---

src/front_input.c
src/frontend.h
src/frontmenu_ingame_tabs.h
src/frontmenu_ingame_tabs_data.cpp

Press 1 on a map with more than 4 keepers to see.

Pressing 1 switches to next player info button

---

src/custom_sprites.c

Fixed shadows on custom creatures

---

src/main.cpp

update spell/room/trap icons after load

---

src/frontmenu_ingame_map.h
src/main.cpp

fix map panel colour on load

---

src/gui_parchment.c

Reported by Pleb Crusher, I'm unable to reproduce this issue myself.
Here is his crash log:
[keeperfx.log](https://github.com/user-attachments/files/16045432/keeperfx.log)

Parchment crash fix

---

src/map_events.c

Tab hit sound plays again

---

src/magic.c
src/slab_data.c

Destroy Walls no longer overwrites a slab's texture with your own

---

src/player_compchecks.c

Fixes #3369
Bug was introduced in f5facf298ac48e814f61bef564acbeef0678de90

Computer players assign unassigned creatures to train too

---

src/front_input.c
src/frontmenu_ingame_tabs.c
src/frontmenu_ingame_tabs_data.cpp

Fixed handling of query page on clicking '1'

---

deps/astronomy/astronomy.c
src/bflib_netsp.cpp
src/config_strings.c
src/front_highscore.c
src/frontmenu_select.c
src/lvl_script_commands.c
src/room_lair.c

Should fix the warning.
I also opened a PR on the library repo.

Fix astronomy library warning

---

src/lvl_filesdk1.c

Fixed crash on map specific string load

---

config/fxdata/creature.cfg
src/config_creature.c
src/config_creature.h
src/config_crtrmodel.c
src/console_cmd.c
src/creature_control.h
src/game_legacy.h
src/lvl_script.c
src/lvl_script_commands.c
src/lvl_script_commands_old.c

Now you can use it like this, provided you have a bird.cfg in your folder:
```
NEW_CREATURE_TYPE(BIRD)
IF(PLAYER0,GAME_TURN > 120)
SWAP_CREATURE(BIRD,HORNY)
ENDIF
```
Also, you can simply swap existing creatures from the creature list.

Removed SWAP_CREATURES

---

src/map_blocks.c
src/map_blocks.h
src/room_util.c

Make sure wibble is set correctly on script slab change

---

src/frontmenu_options.c

mouse_button_label goes out of scope before using it

---

src/lvl_script_commands.c

Overlapping source/destination args when concatenating music track info

---

src/engine_render.c
src/game_saves.c

Fixed a couple compiler errors with -O3

---

lang/gtext_chi.po
lang/gtext_fre.po

Added Chinese translations for new string; improved some previous ones

Chinese strings for Midas door and updated spells

---

src/lvl_filesdk1.c
src/lvl_filesdk1.h

Fix #3453
Arbitrary limit for now... feel free to discuss it.

IncreaseMapFileMaxSize

---

src/ariadne.c
src/ariadne.h
src/ariadne_tringls.h
src/globals.h

Fixed Orange ignoring own locked doors

---

config/fxdata/rules.cfg
config/fxdata/spritecolors.toml

Tiny update for spritecolors.toml to make it looks like better with spacing - in my opinion easier to read - and consistent.

Not functional change for spritecolors.toml 

---

src/magic.c

fix cooldown lightning

---

src/thing_creature.c

Caused by (#3463)
Type: Bug Fix

Fix wind spell

---

src/lvl_script_commands.c

Similar to #3461 but for players' modifiers.

Health&Speed updated when modifiers change

---

config/fxdata/spritecolors.toml
src/frontend.cpp
src/sprites.h

To go along with: https://github.com/dkfans/FXGraphics/pull/77

Alarm Trap specific tab icon

---

src/thing_creature.c

Also fixed the unsummon effect for new players

Familiars dying will unsummon

---

src/bflib_network.cpp

Fixed TCP/IP networking

---

src/player_compprocs.c
src/room_library.c

Fixed RESEARCH script command

---

src/config_rules.h

increase sacrifice victims

---

config/fxdata/trapdoor.cfg
src/thing_effects.c
src/thing_stats.c
src/thing_stats.h

Configurable based on door health

Rebalanced Midas Door

---

src/front_input.c

technically the bitflag did same thing, but makes no real sense here
implements #3556

use boolean && instead of bitwise &

---

src/config_strings.c
src/config_strings.h
src/game_saves.c
src/lvl_filesdk1.c
src/lvl_filesdk1.h
src/main.cpp

Discrete map strings list

---

src/thing_creature.c
src/thing_creature.h
src/thing_shots.c
src/thing_stats.c
src/thing_stats.h
src/thing_traps.c

Strength based percentage damage works against everything

---

src/lvl_script_commands.c

Fixes this bug: https://streamable.com/qlhfwu

Fixed MOVE_CREATURE doing weird stuff in possession

---

Makefile

Updated makefile to include astronomy fix

---

config/creatrs/archer.cfg
config/creatrs/imp.cfg
config/creatrs/thief.cfg
src/config_creature.h
src/config_crtrmodel.c
src/lvl_script_value.c
src/power_specials.c
src/thing_creature.c
src/thing_creature.h
src/thing_list.c

Add a new function to get a random creature kind based on model flags.
Basically made for Steal Hero special but I didn't hardcode it for the specific flag, so it can be used in the future for something else.
Also fix 2 typos.

New function GetRandomCreatureKindWithModelFlags

---

config/fxdata/magic.cfg
src/power_process.c

Scripted Disease spreads

---

src/main.cpp

Fixed minimap player color resetting after restart

---

src/config_crtrmodel.c

Should fix the log complaining about ``NULL``

Fix Log Error regarding PrisonKind/TortureKind

---

src/frontend.cpp

Allow symbols in save names

---

config/keeperfx.cfg
src/config.c
src/game_legacy.h
src/music_player.h

https://keeperklan.com/threads/9764-More-than-50-music-tracks-possible-at-all

Raise MUSIC_TRACKS_COUNT from 51 to 126

---

src/engine_render.c
src/keeperfx.hpp

Display health flowers of low health allied creatures

---

src/bflib_inputctrl.cpp
src/bflib_mouse.cpp
src/keeperfx.hpp
src/main.cpp

Fixed -altinput

---

levels/legacy_cfgs/creature.cfg
src/creature_instances.c

Do not use protect against doors

---

src/creature_states_combt.c
src/lvl_script.c
src/room_entrance.c

Reverts dkfans/keeperfx#3587 to fix #3661 (but only if no solution is found)

Revert "DRAWFROM command now handles string ranges"

---

src/engine_render.c

Hot Fix for health flower

---

src/engine_render.c

Health Flower shows up again for allies

---

src/config_creature.c
src/config_creature.h
src/config_crtrmodel.c
src/creature_graphics.c
src/dungeon_stats.c

Should now work for real with old custom creature.

Fix for Extra Graphics Animation

---

src/config_crtrmodel.c

``fixed_anim_speed`` it was not possible to flip it from true to false, but I don't know if it was intended?

Allow to flip FixedAnimSpeed

---

src/power_hand.c

Fixed crash when holding enemy creature in hand at the edge of the screen

---

src/creature_instances.c

Prevent vandalizing glitch

---

src/config_creature.h
src/keeperfx.hpp
src/lvl_script_commands.c

These were the final missing ones

Added Senses and Appearance blocks to SET_CREATURE_CONFIGURATION

---

src/power_specials.c

Copy annoyance level, hunger level, paydays owed and advanced,

Multiply Creature copy more stuff

---

src/player_data.c

Fixed quick possession

---

config/fxdata/magic.cfg
src/config_effects.c
src/config_magic.c

It had already been supported, but it was not reflected yet in the magic.cfg.

Add Effects Names On Shots

---

src/bflib_sound.c

Removed "Sample table not loaded" log print

---

src/api.c
src/lvl_script.h
src/lvl_script_conditions.c
src/lvl_script_conditions.h

Fixed IF_AVAILABLE limit of 127

---

src/thing_effects.c

Fixed timebomb not doing any damage

---

src/dungeon_data.h
src/map_locations.c
src/map_locations.h
src/thing_traps.c

LAST_TRAP_EVENT[playername]
Note: Works for all except for TRAP0_ACTIVATED

Created LAST_TRAP_EVENT meta location

---

src/lvl_script_commands.c
src/lvl_script_lib.h
src/player_instances.c
src/player_instances.h

`PLACE_TRAP([player],[trap],[stlx],[stly],[free])`
Also made sure there is no door subtracted from player when PLACE_DOOR script command is used with free param.

PLACE_TRAP script command

---

src/engine_textures.c
src/engine_textures.h
src/lvl_filesdk1.c
src/main.cpp

Accepts a map01234.tmapa##.dat file.

Map specific tmap files

---

src/engine_redraw.c
src/front_input.c
src/frontend.cpp

Allows saving your game in possession.
Pressing escape during pause also works.

Pressing Shift+Esc opens options menu in possession

---

src/lvl_script.h
src/lvl_script_commands.c

And cleaned up the workaround in SET_POWER_CONFIGURATION

Expanded ScriptValue with longlong

---

src/engine_redraw.c
src/front_input.c
src/lvl_script_commands.c
src/lvl_script_lib.h
src/packets_input.c
src/player_data.h
src/player_instances.c
src/player_utils.c

`LOCK_POSSESSION([player],[lock])`
where: 1 is locked, 0 is unlocked. Stops players from exiting possession, does not force players into possession.

LOCK_POSSESSION script command

---

src/thing_creature.c

Fix "Eternal" freeze

---

src/creature_states.c
src/creature_states.h
src/thing_creature.c

~~Fix for https://github.com/dkfans/keeperfx/issues/3811~~

Fix DoT termination + Cleanup 'kill_creature' function

---

src/main_game.c
src/thing_doors.c

Fixed secret door not working when freshly placed

---

src/config_magic.c
src/config_objects.c
src/config_terrain.c
src/config_trapdoor.c
src/custom_sprites.c
src/lvl_script_commands.c

get_icon_id returns 'bad icon' when nothing found

Make sure the placeholder bad icon is always used

---

config/creatrs/imp.cfg
src/thing_creature.c
src/thing_stats.c

As mentioned in https://github.com/dkfans/keeperfx/pull/3792, this part was split from https://github.com/dkfans/keeperfx/pull/3716.

Max health only limited by 'HitPoints' variable type

---

src/config_objects.c
src/front_input.c
src/gui_parchment.c
src/gui_parchment.h

Spy window shows objects again

---

src/thing_effects.c

Expands upon 56833fec4c2c5a8907567c16be961a5030d5175d and has all effect elements created by effects be rotated correctly too, and they rotate during movement.
This allows mapmakers to have custom effects with a direction.

Full support for effect rotations

---

src/lvl_script.h
src/lvl_script_commands.c
src/lvl_script_value.c

For 9 players it triggered it 9 times. See #3860

Fixed ALL_PLAYERS triggering scripts 81 times

---

src/creature_states_pray.c
src/lvl_script_commands.c

SET_SACRIFICE_RECIPE change spawns for all players

---

Makefile
src/bflib_fmvids.cpp

FFMpeg still hasn't commented on my open issue so to fix the warnings we'll just assume the palette changed every frame.

Fixed deprecation warnings

---

src/frontmenu_specials.c
src/gui_draw.c
src/gui_frontbtns.c

same thing for the resurrect creature icon

Scale transfer/resurrect box better for all resolutions

---

src/creature_states_combt.c

Ghosts attack enemy doors when ordered to

---

src/config_creature.c
src/config_creature.h
src/config_crtrmodel.c
src/config_rules.h
src/config_trapdoor.c
src/config_trapdoor.h
src/creature_instances.c
src/creature_instances.h
src/creature_states_pray.c
src/creature_states_pray.h
src/keeperfx.hpp
src/lvl_script_commands.c
src/lvl_script_commands_old.h
src/lvl_script_lib.c
src/lvl_script_lib.h
src/lvl_script_value.c
src/main.cpp
src/map_data.c
src/map_data.h
src/power_hand.c
src/power_hand.h
src/thing_doors.c
src/thing_doors.h
src/thing_list.c
src/thing_list.h
src/thing_stats.c
src/thing_stats.h
src/thing_traps.c
src/thing_traps.h

no functional changes expected, more refactor to be used as base for lua PR

Refactor in preparation for Lua Part 2

---

src/engine_redraw.c
src/game_merge.h
src/lvl_script_commands.c

Fixed DISPLAY_VARIABLE and DISPLAY_COUNTDOWN player overwrite

---

src/bflib_sndlib.cpp
src/sounds.c

Cheap fix to prevent hearing damage when mass-digging

Reduce mass dig loudness

---

src/sounds.c

Should fix a lot of missing sounds

Bumped max_number_of_samples back to 100

---

src/front_landview.c

Not actually OpenAL related, broken since #3604

Restored ambient sounds on landview

---

src/front_torture.c

Not actually OpenAL related, broken since #3604

Restored torture door sounds

---

config/creatrs/imp.cfg
pkg_gfx.mk

Related to https://github.com/dkfans/FXGraphics/pull/91

Added Teeth swipe

---

src/slab_data.h

Doesn't appear to cause problems.
Closes #3766

Bumped SLABOBJS_COUNT to 1024

---

src/bflib_sound.c

Emitter flags are important

---

src/front_input.c

Bug introduced at ad6b5becf24dc9ae520d98a305d2081aefbddbbc

Fix Shift blocking possession movement

---

src/console_cmd.c

string.show <num> and quick.show <num>

Console commands for displaying game strings

---

src/lvl_filesdk1.c

Clear memory allocated for level string data

---

src/config_effects.c
src/config_effects.h
src/lvl_script_commands.c

this one only does the script command, not the toml

effect_gen config command

---

src/config.c
src/config.h
src/config_compp.c
src/config_creature.c
src/config_crtrmodel.c
src/config_crtrstates.c
src/config_cubes.c
src/config_effects.c
src/config_lenses.c
src/config_magic.c
src/config_objects.c
src/config_players.c
src/config_powerhands.c
src/config_rules.c
src/config_slabsets.c
src/config_spritecolors.c
src/config_terrain.c
src/config_textures.c
src/config_trapdoor.c
src/lvl_script_commands.c
src/value_util.c
src/value_util.h

Warning: terrain.cfg(line 1335): Value out of range for unsigned char: -1
now replaced with 
Warning: global terrain config(line 1335): Value out of range for unsigned char: -1

better errors for configs

---

src/api.c
src/creature_groups.c
src/creature_groups.h
src/dungeon_data.c
src/dungeon_data.h
src/lvl_script.c
src/lvl_script_commands.c
src/lvl_script_commands_old.c
src/lvl_script_lib.h
src/lvl_script_value.c
src/main.cpp
src/slab_data.c
src/slab_data.h
src/thing_creature.c
src/thing_creature.h
src/thing_effects.c
src/thing_effects.h

Should be final part before merging the actual lua PR
functional changes, the http api will now treat variables as lvl_version(1) even on maps where it isn't set

Refactor in preparation for Lua Part 3

---

src/thing_creature.c

Fixes #4012
It gives all spell effects 1 gameturn more duration, but I think this is a correction.

Give timebomb opportunity to explode when expired

---

src/creature_states.c

#4028 broke state cleanups, this fixes it again

Fix creature state cleanups

---

config/fxdata/trapdoor.cfg
src/room_workshop.c

Now you can make it go as high as you want. Now that we have so many custom traps and doors, it might be useful if someone wants you to have a _really_ big workshop to make the super powerful traps.

Made workshop manufacture level scalable

---

src/creature_graphics.c

The bug was introduced in alpha 4512

Fixed anims bugging out

---

src/front_input.c
src/packets.c

Block camera inputs when chat/console is open

---

src/frontmenu_ingame_map.c
src/gui_parchment.c

hopefully added a greenish minimap dot for workshop crates

add minimap dot for workshop crates

---

src/player_comptask.c

Fixed crash on moving to rooms

---

src/bflib_sprfnt.c

Always reset string length on carriage return

---

src/frontend.cpp
src/sprites.h

thought it'd be a nice addition :)
https://github.com/dkfans/FXGraphics/pull/106

Added message icon for finding a dungeon special

---

config/fxdata/lua/bindings/misc.lua
src/config.c
src/config.h
src/config_campaigns.c
src/front_landview.c
src/game_merge.h
src/game_saves.c
src/lua_api.c
src/lvl_script_commands.c
src/lvl_script_lib.h

Made it possible to jump to campaign level

---

src/bflib_vidraw_spr_remp.c

Response to crash https://keeperfx.net/dev/crash-report/95

Prevent crash at scaling function

---

src/lua_api_slabs.c

Simple replacement of word in log message.

Fix log message for missing fields in slabs

---

src/roomspace.c

No longer possible to tag for digging beyond the maximum box size

---

src/roomspace.c

Fixed interpolated tagging

---

src/config_settings.h
src/console_cmd.c
src/console_cmd.h
src/front_input.c
src/packets.c
src/packets.h
src/player_data.h

Add console command Tab key for auto completion.
Add console message UP key for switch to last.
Fix the error modification of GAME_KEYS_COUNT macro in the https://github.com/dkfans/keeperfx/pull/4156.

Console command auto completion

---

src/creature_states_pray.c
src/dungeon_data.c
src/dungeon_data.h
src/dungeon_stats.c
src/front_lvlstats.c
src/frontmenu_ingame_tabs.c
src/lua_api.c
src/player_compchecks.c
src/player_compprocs.c
src/player_computer.c
src/player_utils.c
src/room_data.c
src/room_lair.c
src/room_list.c

Several dungeon variables were incorrectly named.

room_slabs_count -> room_discrete_amount

---

src/config_rules.c
src/config_rules.h
src/creature_states_pray.c
src/lua_api.c

Fixed remove_sacrifice_script command

---

config/fxdata/lua/classes/Creature.lua
src/lua_api_things.c

Added extra creature variables for lua script:
- gold_held
- opponent_count
- opponents_melee_count`
- opponents_ranged_count
- exp_points
- hunger_amount
- hunger_level
- hunger_loss

Lua: unlock gold, combat, hunger and xp creature variables

---

src/console_cmd.c
src/game_saves.c

Fix some potential out of bounds access issues.

Add prompts for incorrect parameters on the console command.

---

src/lvl_script.c

Parse script with incorrect end of line symbol

---

src/thing_shots.c

No notification when you kill your own heart

---

src/game_legacy.h
src/net_sync.c

I was given a log with a room desync that I couldn't fix, so here's some detailed logging for future room desyncs.

more desync analysis

---

src/main.cpp

not surprised I made this mistake, it was a last minute adjustment

Fixed effects sticking around permanently

---

src/lua_api_player.c

Now IF_CONTROLS and IF_AVAILABLE work with TOTAL_CREATURES in Lua

LUA: Implement TOTAL_CREATURES for other IFs

---

src/game_loop.c
src/main.cpp
src/player_data.h
src/player_utils.c
src/thing_creature.c

And PURPLE, BLACK and ORANGE hearts can claim neutral creatures now

Orange keeper can die in multiplayer

---

src/engine_redraw.c
src/packets_input.c

Helps when you try to possess imps mining on top of the gold pile they left.

Focus creatures when holding possession hotkey

---

src/engine_redraw.c
src/roomspace.c

Also fixed a bug regarding the cursor

Fixed highlight box size getting stuck from building/selling
