src/config_settings.c
src/frontmenu_options.c
src/kjm_input.c
src/kjm_input.h

In response to #810.
This allows the assignment of key combos that are already in use. When this occurs:
- the key with the matching key combo takes on the key combo of the currently chosen key
- and the currently chosen key takes on the currently chosen key combo
i.e. they are swapped. 
The "other" key involved in the swap, i.e. the one the player didn't choose to change, is "highlighted" in the deep red colour in the Define Keys Menu. This colour is cleared when the user sets the key manually.
_(Note that this is a grey colour in CJK fonts.)_
Also:
- ALT can be used as a single modifer key for Rotate/Speed and Possess/Query
- Rotate/Speed can also now use any valid single key
- [bugfix] Pressing Escape no longer returns to the Options Menu when you cancel a key assignment
Any further …

Assign keys already in use

---

lang/gtext_eng.pot
src/bflib_keybrd.h
src/bflib_mouse.cpp
src/config_strings.h
src/frontmenu_options.c
src/kjm_input.c

**_This is not a good/proper implementation, but a decent interim one._**
Middle mouse button (Mouse 3) and mouse wheel up/down can be bound in the key binding menu to an in-game action.
If bound to an action, the action will trigger when the user presses one of the mouse buttons in-game.
- The fact the mouse buttons work as  a binding for in-game actions is because of the use of `lbKeyOn[]`.
- The use of `lbInkey` lets the user bind the mouse buttons in the key bind menu.
~~**Currently uses hardcoded strings for the mouse buttons when shown on the key binding menu, appropriate new ones should probably be added to the .dat file.** _Other than the strings, this is good to go._~~ GUI Strings are now used

 Add mouse3 and mouse wheel to bindable keys [Patch]

---

lang/gtext_eng.pot
pkg_lang.mk
src/config_campaigns.c
src/config_settings.c
src/config_settings.h
src/config_strings.c
src/config_strings.h
src/front_input.c
src/front_input.h
src/frontmenu_options.c
src/kjm_input.c
src/main.cpp
src/packets.c
src/player_instances.c
src/roomspace.c
src/vidmode.c

- Removed limit of 1001 GUI strings **(GUI_STRINGS_COUNT must now be increase as new strings are added)**
- _DK_GameSettings added and GameSettings expanded _(need to check what in DLL is dependent on GameSettings)_
- Added `make pkg-lang-single LANGUAGE=eng` to just build the .dat file for a single language (works for any language)
- Added One-Click Build, Single Subtile selling, and Snap Camera keys to keybind menu
- Replaced in-game usage of One-Click Build, Single Subtile selling, and Snap Camera to use the above game key bindings rather than the hard-coded keys

Add roombuild keys to rebind menu

---

src/packets.c

compounded conditional statement moved to a new boolean - drag_check.
Before this fix, it was checking for SHIFT only or CTRL and hold left mouse button to paint a bridge. 
Now it checks for (SHIFT or CTRL) and hold left mouse button to paint a bridge.

fixed a mistake with bracket usage

---

src/lvl_script.c
src/lvl_script.h

USE_POWER_AT_LOCATION renamed to USE_POWER_AT_SUBTILE; added USE_POWER_AT_LOCATION
Would be great having the option to use action points or hero doors for spell casts.
- use power at location now takes one action point/hero door argument instead of former subtiles x,y
- former USE_POWER_AT_LOCATION renamed to ..._at_subtile

USE_POWER_AT_LOCATION renamed to ..._AT_SUBTILE; added ..._AT_LOCATION

---

src/lvl_script.c
src/lvl_script.h

New script command: ALTER_CREATURES_ANGER([player],[anger],[operation])
Annoys/calms all player's creatures.
* player is target player
* anger is anger value: refer to AnnoyLevel in creature's config
* operation: whether anger should be added to current anger for every creature(1), reduced(-1), or set(0)

New script command: CHANGE_CREATURES_ANNOYANCE

---

src/lvl_script.c
src/lvl_script.h
src/player_comptask.c

Mapmakers want to be able to make a computer player dig towards a specific player or location or player based on script conditions.
I made a script command that goes COMPUTER_DIG_TO_LOCATION([player],[location]), where location is any accepted location like Hero gate, player or action point.

Trigger computer attack/dig from level script

---

src/creature_control.h
src/creature_states.c
src/creature_states_combt.c

creatures would start looking around before the drop was finished, causing them to flee too fast, and possibly other issues.

Fixed dropping flying units

---

src/creature_control.h
src/creature_graphics.c
src/creature_states.c
src/creature_states.h
src/creature_states_combt.c
src/creature_states_hero.c
src/lvl_script.c
src/main.cpp
src/sounds.c
src/thing_creature.c

- Fearstronger only. Wounded units and imps(101 fear) still flee.
- After 8 seconds might still flee, but this gives you a chance to redrop, or have 4 units by then.
- named 2 CreatureControl variables

Dropping weak units on strong enemies will make them fight through fear

---

src/map_columns.c
src/map_columns.h
src/map_data.c
src/thing_physics.c
src/thing_shots.h

Also seems to enable you to avoid boulders in possession by flying over them.

Fix #919 - Boulders ineffective in Hatchery

---

src/config_campaigns.h
src/gui_msgs.c
src/gui_msgs.h
src/lvl_script.c
src/lvl_script.h

Commands send a chat message from a specific creature/player. Also accepts 'None' to have no icon.
```
QUICK_MESSAGE([message_ID], "[message text]", [creature/playername])
DISPLAY_MESSAGE([string number], [creature/playername])
```

Remade PRINT and MESSAGE commands

---

src/player_compevents.c

Stops computers from casting disease and chicken on imps. Because lightning is most effective there.

Computers only cast lightning on imps.

---

src/config_campaigns.h
src/console_cmd.c
src/console_cmd.h
src/packets.c
src/room_data.h
src/thing_factory.c

This pull  has !thing.create, !object.create, !creature.create, !gold.create, and !slab.place. Object, gold, and slab takes only the type/amount as parameters. !create.thing takes 2 numbers, the [class](https://github.com/dkfans/keeperfx/blob/a07769e091ff842c93577baf9add33eebff8f5df/src/thing_list.h#L35) and model (I think in that order), and creature takes the creature, level, amount, and owner, the latter two of which are optional.
You can place any terrain, and create any thing, or specifically objects or creatures.

Added thing creating and slab placement commands.

---

src/lvl_script.c

CHANGE_CREATURES_ANNOYANCE([player],[creature],[operation],[annoyance])
Allows for ANY_CREATURE
Fixes #958

CHANGE_CREATURES_ANNOYANCE now accepts a creature parameter

---

src/power_hand.c
src/thing_corpses.c
src/thing_creature.c
src/thing_data.h
src/thing_effects.c
src/thing_list.c
src/thing_objects.c
src/thing_physics.c
src/thing_physics.h
src/thing_shots.c

Dropping flying units (fairy, fly, vampire with flight spell enabled) into battle they should now drop at a reasonable speed towards their normal altitude.
To see the new behavior simply drop a fairy or vampire and some non-flying units into a party of enemies and compare their drops.

Fixed flying units falling really slow when dropped

---

src/creature_states_tortr.c
src/dungeon_data.h
src/lvl_script.c
src/lvl_script.h

Does not count special diggers. This is consistent with the GOOD_CREATURES and EVIL_CREATURES variables.
Works like this:
```
IF(PLAYER0,EVIL_CREATURES_CONVERTED >= 1)
QUICK_OBJECTIVE(11," 1 evil creature converted",ALL_PLAYERS)
ENDIF
IF(PLAYER0,GOOD_CREATURES_CONVERTED >= 2)
QUICK_OBJECTIVE(13," 2 heroes converted",ALL_PLAYERS)
ENDIF
```
Can be used to detect how many creatures/heroes a player has converted, and tweak the specific conversion rates based on this.

Added GOOD_CREATURES_CONVERTED and EVIL_CREATURES_CONVERTED script variables

---

src/config.c
src/config.h
src/frontmenu_select.c
src/lvl_filesdk1.c

Proof of concept …
Using e.g. #201 as the level name in a .lif file will set `lvinfo->name_stridx` to 201.
`lvinfo->name_stridx` is then used on the Map screen to show the level name. (through existing code)
`lvinfo->name_stridx` is also used on the Level select screen to show the correct level names (added in ec62600)

Translatable level names for mappacks

---

src/bflib_sound.c
src/bflib_sound.h
src/map_events.c

tabfall.wav should now play when you receive a message, but only when you in the top dungeon view and have the GUI enabled. It should stop when the tab hits to sound more natural.

Added TabFall sound

---

src/creature_states_spdig.c
src/gui_soundmsgs.h
src/room_library.c
src/room_workshop.c
src/room_workshop.h
src/spdigger_stack.c
src/thing_creature.c

The Mentor should now tell you when:
*Neutral creatures join your dungeon
*A door or trap crate is discovered or taken.
The Mentor now says that a spell has been discovered, rather than taken, if the spell book is neutral-owned.

Adding missing Mentor dialogue

---

src/lvl_script.c
src/lvl_script.h

Using this command scripts will be able to count down from some value.
If the value to be stored in flag is too big or small, it will get set to 255 or 0.
Script param details in commit msg
Example:
<pre>
REM at some point, spawn a party 3 times and for every summoned horny, spawn one more
IF_ACTION_POINT(4, PLAYER0)
SET_FLAG(PLAYER0, FLAG0, 3)
SET_FLAG_COMPUTED(PLAYER0, FLAG0, INCREASE, PLAYER0, REWARDED[HORNY], 0)
SET_TIMER(PLAYER0, TIMER0)
ENDIF
IF(PLAYER0, TIMER0 > 240)
IF(PLAYER0, FLAG0 > 0)
ADD_PARTY_TO_LEVEL(PLAYER_GOOD, MY_PARTY, -1, 1)
ADD_TO_FLAG(PLAYER0, FLAG0, -1)
SET_TIMER(PLAYER0, TIMER0)
ENDIF
ENDIF
</pre>

New script command: SET_FLAG_COMPUTED

---

src/creature_instances.c
src/main.cpp
src/map_data.c
src/map_data.h
src/packets.c

subtile_is_diggable_for_player() now (optionally) checks for fortified walls
subtile_is_diggable_for_player() used to return true for enemy/neutral fortified walls, now if the `enemy_wall_undiggable` parameter is set to true: it will deem fortified walls of other players to be undiggable.
Setting `enemy_wall_undiggable` to false is equivalent to the old behaviour of subtile_is_diggable_for_player().
Therefore, all existing calls to subtile_is_diggable_for_player(), and the synonymous can_dig_here(), have been modified to set `enemy_wall_undiggable` to false.
____
Now that subtile_is_diggable_for_player() will also return false for enemy/neutral fortified walls, **tag_cursor_blocks_dig()** can use that function instead of the convoluted IF statement it used before.

subtile_is_diggable_for_player() improvement

---

src/dungeon_data.h
src/engine_render.c
src/front_input.c
src/main.cpp
src/packets.c
src/roomspace.c
src/roomspace.h
src/roomspace_detection.c

**basic one-click highlight**
Any time you could tag/untag for digging, you can now hold CTRL to use the one-click square brush.
Interface conflicts with scroll wheel are handled the same as for one-click build/sell.
tag_cursor_blocks_dig() now works with roomspaces
process_dungeon_power_hand_state() and process_dungeon_control_packet_dungeon_control() now use get_dungeon_highlight_user_roomspace() before tag_cursor_blocks_dig() to set up a roomspace.
keeper_highlight_roomspace() is used instead of direct calls to untag_blocks_for_digging_in_rectangle_around() and tag_blocks_for_digging_in_rectangle_around() to allow slabs in a roomspace to be tagged/untagged.
multiple functions added to roomspace.c to allow one-click highlight to work

One-click Highlight (Square Brush mode)

---

src/front_input.c
src/main.cpp
src/packets.c
src/roomspace.c

Bugfix:
Holding left mouse button over a dungeon message stuck the cursor in PickAxe/Highlight mode when hovering over "low slabs", and it could only be reset to normal by clicking left or right mouse button.
This is now fixed.
Feature:
Holding Ctrl+RMB now works over low slabs, as long as you start holding Ctrl+RMB over a high slab (wip)

One click highlight lowslab adjustments

---

src/gui_tooltips.c

Fixes #1003
Tool Tips are positioned according to the mouse X and Y coordinate. A y-offset of 86 was added, which was correct for 640x400.
This fixed 86 has now been replaced with a value based on the units_per_pixel value. This means that the tool tip is now in the correct position at all resolutions.
Instead of this:
we now have this:

position tool tips correctly

---

Makefile

keeperfx.exe has a dependancy on libwinpthread-1.dll when building with MSYS2 & mingw32.
This PR removes the dependency.
Side effect - this PR adds an error message like:
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 10 (VERSION) name: 1 lang: 409
to end of KFX build process, but it is harmless.
Sources:
* https://stackoverflow.com/questions/13768515/how-to-do-static-linking-of-libwinpthread-1-dll-in-mingw (why I added the new commands)
* https://stackoverflow.com/a/63375091 (why the new error message is harmless)
So, to explicitly state the details here: 
* A static link to lwinpthread is added at the end of the linker flags, this means libwinpthread-1.dll is no longer needed by KFX (when built …

remove libwinpthread-1.dll dependency

---

src/bflib_video.c
src/bflib_video.h
src/gui_parchment.c

correcting the position of these corner sprites:
(top left shown)
For reference, DK GOG:
KeeperFX 1080p master:
KeeperFX 1080p with this PR:

correct position of corner sprites in draw_zoom_box()

---

src/bflib_video.c
src/bflib_video.h
src/frontmenu_ingame_map.c
src/frontmenu_ingame_tabs.c
src/vidmode.c

Fixes #824.
there may be slight rounding errors, but minimap now does not get more zoomed out the higher the video resolution.
e.g. 1920x1200 is a 3:1 match of 640x400 and looks the same in fullscreen, 1920x1080 _might_ be slightly off.
3840x2160 fully zoomed in:

minimap (and money total) now correct size at all resolutions

---

config/keeperfx.cfg
src/config.c
src/config.h
src/engine_arrays.c
src/engine_render.c
src/main.cpp
src/map_blocks.c

initial commit is proof of concept, it needs testing to ensure there are no unintended consequences of turning wibble off.
wibble defaults to ON
you can also control it via the keeperfx.cfg file, use:
`WIBBLE=ON`
and
`WIBBLE=OFF`
preview with wibble turned off:

Toggle wibble feature

---

src/bflib_mspointer.cpp
src/bflib_video.c
src/bflib_video.h
src/gui_draw.c
src/gui_tooltips.c
src/power_hand.c
src/vidmode.c

... uses HEIGHT to scale if window aspect ratio is over 16/10, uses WIDTH to scale if window aspect ratio is 16/10 or lower. 640x400 and 640x480 are the same, anything wider is now correct. All resolution now have the same size of cursor, power hand and tool tips relative to the window size.
3440x1440 mode (21:9):
uses the new `units_per_pixel_ui` and `scale_ui_value()`
_**Note:** 1080p power hand is now about 1 pixel smaller in both dimensions, but it now matches original DK 640x400 mode better._
_____
Other functions have been added to aid the scaling project: they are designed to help collect all of the scaling together in one place. At a future point in time, these functions and their use can be re-assessed to reduce redundancy.
**_Initial support for variable UI scaling (only works …

power hand, cursor and tooltips now correct size in all aspect ratios/resolutions

---

src/config_settings.c
src/config_settings.h
src/engine_camera.c
src/frontend.cpp
src/main.cpp
src/packets.c
src/player_instances.c
src/player_utils.c

... to settings.dat
Are there any others settings that should/could also be saved?
There is a discussion here: #296, that brings up the suggestion of camera zoom and rotation. I have fixed the mentioned bug about cluedo mode (low wall mode) not always saving.
Camera zoom level might be a good idea to add, especially after #1030.

saves the current mini map zoom level

---

src/config_trapdoor.h
src/dungeon_data.c
src/lvl_script.c

Changing the script command from:
`SET_TRAP_CONFIGURATION([trapname],[val1],[val2],[val3],[val4],[val5],[val6],[val7])`
to
`SET_TRAP_CONFIGURATION([trapname],[command],[value])`
This to allow you to set any of the 21 trap values, and hopefully in an easier way.
Example:
``` 
SET_TRAP_CONFIGURATION(BOULDER,Shots,4)
SET_TRAP_CONFIGURATION(BOULDER,SellingValue,5000)
```

Rework SET_TRAP_CONFIGURATION

---

src/lvl_script.c

From commit #b25c22b onward, the EXPORT_VARIABLE command does not work anymore. This breaks the ASSMIST campaign.
It's because that commit changed it to only recognize flag variables, instead of all script variables like MONEY.

Fix EXPORT_VARIABLE not working anymore

---

.github/workflows/CI.yml

when merging to master both GITHUB_HEAD_REF and GITHUB_BASE_REF are blank, so the logic in the line 
**"if [[ "$GITHUB_HEAD_REF" != "$GITHUB_BASE_REF" ]]; then"** 
works as needed - the "Alpha" PACKAGE_SUFFIX is applied when merging to master, and the "Prototype" PACKAGE_SUFFIX is applied when committing to a PR.
_(Also removed an extra space that was added by mistake)_

remove unneeded echos from `.github/workflows/CI.yml`

---

src/console_cmd.c

fps <value> - displays the framerate, or sets it to the specified value
time <turn> <framerate> - converts game turns to real time
timer,toggle
timer.switch - switches between timers
game.save and game.load <slot> - should allow you to go beyond the usual slots
cls - clears console messages
ver - displays KeeperFX version
volume - displays current volume values
volume.sound and volume.music <value> - sets volume values
player.score - displays the score of the specified player
sound.test and speech.test <value> - tests the specified sound/speech

Added some miscellaneous commands

---

config/keeperfx.cfg
src/config.c
src/config.h
src/engine_arrays.c
src/engine_arrays.h
src/engine_render.c
src/main.cpp
src/map_blocks.c

Implements #1048
When `WIBBLE=LIQUIDONLY` turn on some aspects of wibble, so that the water/lava is animated correctly with wibble, (but the walls remain straight like WIBBLE=OFF mode)

add LIQUIDONLY option to WIBBLE setting

---

src/thing_shots.c

- Fixes #1110
- Should also effect melee shots when a modder would remove the REBOUND_IMMUNE property of those shots
- Also fixes the possibility to add NO_HIT to melee shots

Arrows can now be rebounded again, even when strength based

---

src/main.cpp
src/thing_creature.c
src/thing_shots.c

Fixes #1109
In DK navigate missile would rebound, in FX it would circle around the target.

Navigate Missile spell now rebounds like it used to

---

src/thing_creature.c

Fixes #479
Testmap: [479.zip](https://github.com/dkfans/keeperfx/files/6971854/479.zip)
1) Use the reveal map below the heart in the testmap
2) Build graveyard
3) Capture fairies
4) It helps to use cheats to level them up in prison so they cast heal
5) Slap them against the wall until they die.
-> Notice they will all be dragged to graveyard, and none are stuck into the wall.

Flying units cannot be slapped to death into a wall anymore

---

src/room_data.c

Now when you place a library under a spellbook, the capacity remains available, and an imp should be able to 'claim' the book still.
Same as with crates and workshops.

Unshelved books do not take up space

---

lang/gtext_chi.po
src/roomspace.h
src/slab_data.c

When building rooms, using shift-build will now automatically suggest expanding the current room type without mouse scrolling.
Scrolling back will still allow to use the slab type as a wall.
Fixes https://github.com/dkfans/keeperfx/issues/1125

Changed default room detection looseness for one-click build

---

src/creature_instances.c
src/room_util.c

In the current master when you sell the last tile of a room type, (So that afterwards you have 0 tiles left in your entire dungeon) you would get a 'room lost' message.
This was a mistake.
With this PR, this event should no longer happen, but the AI should still rebuild rooms when you claim or destroy them.

No event on room sold

---

src/config_creature.c
src/config_creature.h
src/creature_states_pray.c
src/player_utils.c
src/thing_list.c

Fixes these bugs:
Bug 1: Units will always stay under Call to Arms
1) Cast call to arms
2) Disable it -> all units should stop being effected
-> notice they remain under the effect of Call to Arms
Bug 2: Imps will leave through the portal, units will never die without portal access.
1) Use the cheat menu to kill a blue keeper -> all his units should leave and imps should die
-> Notice imps will exit through the portal. If blue has no portal, his units continue working instead of dying.

Search filters looking for any/all creatures broken

---

src/player_comptask.c

Fixes a bug where potential torture victims where dropped onto active battles instead.

Stop dropping enemies into battle

---

config/fxdata/keepcompp.cfg
src/player_comptask.c

The  <room type> param is now respected. Before, it was forgotten when a unit was picked up.
Also commented the keepcompp.cfg file some more, and included a new - but still unused - check configuration.

Fixed 'MOVE CREATURE TO TRAINING' check

---

src/game_saves.c
src/main.cpp

This is the reported bug:
1) Install this map on the custom map pack: [personal.zip](https://github.com/dkfans/keeperfx/files/7672210/personal.zip)
2) Start it and notice there are lots of custom traps on the tab panel
3) Save the game
4) Completely exit the game, before restarting and loading the save
-->> Notice there are no custom traps and the log is full of 'unknown trap' errors
This PR fixes that bug.

Additional custom traps work on restart

---

src/creature_instances.c
src/thing_corpses.c
src/thing_creature.c
src/thing_creature.h
src/thing_data.h
src/thing_objects.c
src/thing_physics.c
src/thing_shots.c
src/thing_traps.c

- Bug was introduced because arrows are now strength based, and code assumed those were melee.
- Changed that part to look at both strength-based and reboundable properties to exclude 'strength based projectiles
- (Re)named a bunch of variables in my quest to understand the code
To reproduce the original bug, make an arrow trap and have it shoot an arrow against the wall (by missing an enemy)
Testmap attached: [test106.zip](https://github.com/dkfans/keeperfx/files/7726809/test106.zip)

Arrows no longer slide against walls when fired from trap or rebound spell

---

src/power_hand.c

Fixes an exploit where you can get enemy keepers to drop his entire army away.
To reproduce:
1) Get near an enemy dungeon undetected
2) Get towards the enemy Portal
3) Get detected by an enemy unit while you are standing on or near the entrance
-> the computer will drop in his army to fight your unit
4) Pick up your unit
-> Notice the enemy units see nothing to fight and believe they are being fired and will leave through the portal
New behavior is that the enemy keeper should avoid dropping units on the entrance.

Computer players recognize dropping on entrance is dangerous

---

src/actionpt.c

If you pick up a unit from within action point range, he will keep triggering the AP. This could provide issues in cases where it is reset.
Here is a testmap: [testmap1282.zip](https://github.com/dkfans/keeperfx/files/7942675/testmap1282.zip)
A sound is played when the AP is triggered, and a sound is played when it is reset. Pick up the imp from the empty room to see the broken/fixed behavior.

Things in hand no longer trigger action points

---

src/thing_objects.c

Introduced in #1279 (af1870454)
To reproduce the bug:
1) Start this map: [dropgoldbugmap.zip](https://github.com/dkfans/keeperfx/files/8011687/dropgoldbugmap.zip)
2) Reveal
3) Zoom to action point the objective points to
-> notice the gold pots do not drop completely
Crucially though, I reverted code introduced in the spellbook integration commit, which moves neutral books at level start. We might have regression there.

Fixed a recent issue of stuff not dropping into water well

---

src/creature_states.c

instead of standing in front of a locked door it that happens to be closest.
To see the new behavior:
1) Make a dungeons with 2 filled treasure rooms
2) Build and lock a door to one of the treasure rooms
-> Notice on payday, units will take gold from the open treasure room.
Old behavior:
-> Units closest to the locked treasure room would wait for the door to be unlocked.

Units will now first try open treasure rooms on payday

---

src/creature_states.c
src/thing_creature.c

This enables game to detect treasure room queue, making sure units line up nicely and will not die there.

Door collide ID no longer reset for friendly doors

---

src/thing_objects.c

checked in ida and both functions are identical so the 2 can safely be replaced by the non numbered version

replace object_update_armour2 by _DK_object_update_armour

---

src/creature_control.c
src/thing_creature.c

Previously, they only showed when possessing your own creatures.

Creature lenses in possession now always show

---

src/thing_stats.c

Creature weight was based on size and height, that are modified with some params for certain unit types (like how much they eat and if they are an insect). However, the size and height of every unit is exactly the same, so this leads to units being often the exact same weight. And Orc weighted as much as an Imp of the same XP level.
I now based the calculation on the Eye height of the unit, plus the same set of modifiers. As a result, smaller creatures weigh a bit less, larger creatures a bit more, low levels weigh a bit less, high levels weigh a bit more.

More differentiating unit weight computation

---

src/engine_camera.c

When possessing a chickened unit, you will move to a chicken eye level.
This is fun, but also helps the player with recognizing he is a chicken.

Chicken eye-height in possession

---

src/frontmenu_ingame_tabs.c
src/frontmenu_ingame_tabs_data.cpp
src/gui_draw.h

Kill an enemy keeper and the icon shows him defeated.
Requires new data files, attached for easy testing: [data.zip](https://github.com/dkfans/keeperfx/files/8103252/data.zip)

Keepers show dead faces on defeat info panel

---

src/gui_msgs.c

Resolves #1351
Also changed the hero player's icon to the white one.

Messages from dead players now show the dead icon on chat messages

---

src/thing_objects.c

You now need -alex command line to get the spider from gold+chicken sacrifice.

Only get spider sacrifice with easter eggs enabled

---

src/engine_render.c

Should be same size for every resolution now. Also handles other numbers.
Partial fix for #993

Scale the number values that appear on selling gold

---

config/fxdata/magic.cfg
src/thing_objects.c
src/thing_objects.h
src/thing_shots.c

This stops boulders from getting slowed down by gold and the gold visibly showing damage.
Also made it so that objects getting hit do not use the 'creature' hit sound, but the 'generic' hit sound.

Objects that cannot be destroyed do not take damage

---

src/thing_list.c

Now `USE_SPELL_ON_CREATURE(PLAYER0,IMP,ANYWHERE,SPELL_CHICKEN,10)` works again
Fixed #1198

Fixes targeting imps with script criteria

---

src/creature_states.c
src/creature_states_gardn.c
src/room_data.c
src/room_data.h

If used capacity is over total capacity, do a recound and throw an error message

Implemented workaround for too many chickens

---

src/packets_input.c

Selling would cause desyncs/crashes on multiplayer. Now it does not.

Fixed desyncs on selling

---

pkg_gfx.mk
pkg_sfx.mk
prebuilds.mk

when doing a make pgg-gxf or sfx it currently downloads an outdated zip and unpacks it
this replaces it with cloning the correct repo instead
note this doesn't include updating existing repo or anything
only clones when the zip would've otherwise been downloaded
but better then the outdated zip it is now

replace downloading zip with cloning git gfx sfx

---

src/slab_data.c

Fixes walls remaining when a Dungeon Heart is destroyed.

Corners walls of unclaimed path should now be unfortified

---

src/frontmenu_ingame_opts_data.cpp

A mismatch was introduced in 0c6235e4a that made you click the button to the right by accident:
On the image, notice the tooltip below the cursor is for gamma.

Sprite matches click position on gfx option buttons again

---

src/creature_control.h
src/creature_states.c

When a tunneler party is placed in a very small room, units do not have space to follow.
When units do not have space to follow, they will elect a new leader after 8 failed attempts. And said new unit is big and strong but cannot tunnel and so they are forever trapped in the box.
Party members will have over 8 failed attempts before a tunneler can breach a white wall. So I changed the margin to 12.
At 10, they would escape after having the party disbanded.

Party members won't mutiny on slow tunneler escape

---

src/ariadne_wallhug.c
src/creature_control.h
src/creature_states.c
src/thing_doors.c
src/thing_list.c
src/thing_physics.c
src/thing_physics.h

When a follower cannot get to his position, it is deemed he cannot reach the party and after x failed attempts, he will start his own party.
However, it is possible the follower position is on the other side of a wall while he is still very much a member of the party. As such, I do not count a fail if he is closer to the party leader than he is to the follower position he is trying to go.
On this image, the archers would try to reach all red circled positions, would deem 10 and 11 as free positions, but they cannot reach. 
This PR makes it so that they notice they are close enough to the tunneler to not need to start their own party.

Followers do not abandon the party when they are close to the leader

---

src/creature_groups.c

However, DEFEND_PARTY still overwrites it.
Testmap: [1419.zip](https://github.com/dkfans/keeperfx/files/8410032/1419.zip)
1) Reveal the map to see the tunneler coming from Hero Gate 1
2) Use cheats to kill the tunneler and notice the thief becomes the new leader (the tunneler does not want to, by script)
3) Kill the thief and see the tunneler does become leader (the other units do not want to either), and continues digging
Change the tunneler party objective to have it become leader as soon as the thief is killed.

Special diggers are considered first for party leadership

---

src/thing_data.c

Reduces frequency of thing limit warning messages. To see the difference start a complex map then use sight of evil. Before, when it was closed it displayed a message, now it usually does not.

Prevent thing limit message on effect elements

---

src/thing_creature.c

Teleporting in possession now drops the thing you're holding.

---

src/creature_states_hero.c
src/dungeon_data.h

Before, they would attack the available player with the lowest player number. Now, they take 'best dungeon' from the APPROPRIATE_DUNGEON command.
With ALWAYS_TUNNEL_TO_RED bug it has classic behavior.

Spawned parties now attack best player

---

src/lvl_script_commands_old.c
src/lvl_script_value.c

just not the one the user requested.
These rules are new:
{"HungerHealthLoss",              24},
{"GameTurnsPerHungerHealthLoss",  25},
{"FoodHealthGain",                26},
{"TortureHealthLoss",             27},
{"GameTurnsPerTortureHealthLoss", 28},

added more rules for CHANGE_GAME_RULE

---

src/room_util.c

Fix to a recently introduced issue. When placing a large gold hoard in a treasure room with limited efficiency, it should transfer the hoard to one that fits, and throw out the -remaining- gold into a pile. Instead it created the hoard and a pile of gold worth the full hoard amount too.

Fixed non-fitting hoard to give too much gold

---

src/game_saves.c
src/main.cpp

Because the stats files could have custom icons configured, they should be known at that point.
Fixes a bug where on reload, the creature icons are unknown.

Moved loading custom icons to be before loading the stats files

---

src/creature_states.c

It said 'no job found' when a job _was_ found.

Corrected log message that had flipped meaning

---

src/creature_states_prisn.c

The voice line should only be created when an actual skeleton is made.

Don't give skeleton created voice on creature limit

---

src/creature_control.h
src/creature_states.c
src/dungeon_data.h
src/main.cpp
src/player_utils.c
src/player_utils.h
src/power_hand.c
src/thing_list.c

This commit introduced issues: 395da4e933b17d54cdacf9a15aadcfb7cb0498aa
It sought to fix keepers never having to pay missed paydays, and units being angry forever by converting anger to money and back. However
- Mad Psycho reapers cannot get happy so they took infinite money
- Units get angry more from missed pay then they gain in happiness on payday, so it ended up costing the player too much money for other units too.
So instead I'm allowing for the 'prepayments_received' function to go negative - renamed to paydays_advanced - to keep track on how much money is still owed. If during payday there's enough cash to pay backpay for that single unit, it is done.
Also, if there's enough money to pay the backpay in between paydays to pay ALL backpay, units will go get payment instead of …

Creatures now remember backpay, instead of just their emotions

---

src/creature_states_wrshp.c

Units would take one to few workers in cases where there were no workshop items available to produce. Now this is correct.
The code I fixed said the difference was to make sure crates could still be created in a full workshop, but I see no issues there.

Now correct numbers of workers can produce nothing in the workshop

---

src/creature_control.h
src/creature_jobs.c
src/creature_states.c
src/creature_states_rsrch.c
src/creature_states_scavn.c
src/creature_states_wrshp.c
src/thing_creature.c
src/thing_list.c

Before this PR, a unit in a workshop that is just one slab, would freeze up. Now they walk around the tile, like they would before on a room with two slabs.

Units walk around single-slab workshop too

---

src/front_input.c

only the drawing was scaled, the inputs were forgotten.
Zooms are now the same in draw_whole_status_panel and get_dungeon_control_action_inputs
Fixes #1161

Scaled minimap control input zoom the same as the minimal itself

---

src/creature_states_spdig.c
src/thing_creature.c

- Stopped imps from moonwalking while dragging
- Stopped imps from teleporting books
- Made drag positions of all things to be behind the imp instead of inside the imp

Drag spellbooks backwards and moved all drag positions

---

src/lvl_script_commands.c

In process_fx_line, this code returned true:
```c
if (fx_line->step >= fx_line->total_steps)
{
fx_line->used = false;
break;
}
```
This because it came to a negative amount of steps in some cases.

Fixed effects_line not working on some distances

---

config/creatrs/sorceror.cfg
config/creatrs/wizard.cfg
src/creature_states.c
src/creature_states_guard.c
src/creature_states_prisn.c
src/creature_states_prisn.h
src/creature_states_train.c
src/creature_states_wrshp.c
src/thing_navigate.c

and a revert to an accidental change made in 7c81dc636e836a2865a5f398ada0ceb80f171b00
- The 'work annoyance and going postal' function is called when creatures 'move' during there job. However, workshops have a special move function that avoids calling the regular function. Now the special workshop function checks for annoyance or going postal too.

Fixed work annoyance and going postal not working for workshop

---

src/bflib_sprfnt.h
src/console_cmd.c
src/engine_redraw.c
src/front_input.c
src/frontend.h
src/game_saves.c
src/gui_boxmenu.c
src/keeperfx.hpp
src/main_game.c
src/packets.c
src/packets.h
src/player_data.h

Removed all implementation related to playeradd->cheat_menu_active  and the PckA_ToggleCheatMenuStatus packet introduced to stop possessed creatures on spinning right, that caused several bugs related to not being able to turn in possession at all.
And introduced an alternate fix to the unwanted turning.

Stopped the no-turning bug forever

---

src/frontmenu_ingame_map.c

This makes minimap follow parchment map behavior.
fixes #1519

Display unowned books and mystery boxes on minimap

---

src/spdigger_stack.c
src/spdigger_stack.h
src/thing_creature.c

Made possession pickup rules for library objects the same as regular rules

---

src/config_creature.c
src/config_creature.h
src/creature_jobs.c
src/creature_states.c
src/creature_states.h
src/creature_states_barck.c
src/creature_states_combt.c
src/creature_states_gardn.c
src/creature_states_guard.c
src/creature_states_lair.c
src/creature_states_pray.c
src/creature_states_prisn.c
src/creature_states_rsrch.c
src/creature_states_scavn.c
src/creature_states_tortr.c
src/creature_states_train.c
src/creature_states_wrshp.c
src/player_compchecks.c
src/player_compprocs.c
src/player_comptask.c
src/player_computer.h
src/room_data.c
src/room_data.h
src/room_jobs.c
src/thing_creature.c

make creatures able to work properly in multiple rooms that have the correct role, used to only accept the first roomkind that had the role

roomroles jobs

---

src/main.cpp

To reproduce the bug, cast cave-in on a torture victim to see it stop being tortured. Now that does not happen.

Fixed creatures escaping custody under cave-in spell.

---

src/ariadne.c

Fixes #1585
src/ariadne.c: In function ‘ma_triangle_route’:
src/ariadne.c:1944:28: warning: iteration 3517 invokes undefined behavior [-Waggressive-loop-optimizations]
1944 |              tree_route[i] = route_fwd[i];
src/ariadne.c:1942:9: note: within this loop
1942 |         for (i=0; i <= sizeof(tree_route)/sizeof(tree_route[0]); i++)

ma_triangle_route goes out of bounds

---

src/frontend.h

This symbol is defined twice in the same header file.

redefinition of _DK_gui_error_text

---

src/vidmode_data.cpp

`max(sizeof(block_mem), 960*720u)` does not compile on 64-bits as they are different data types:
```
g++ -DHAVE_CONFIG_H -I.    -g -O2 -D_REENTRANT -I/usr/include/SDL2 -g -O2 -MT src/keeperfx-stubs.o -MD -MP -MF src/.deps/keeperfx-stubs.Tpo -c -o src/keeperfx-stubs.o `test -f 'src/stubs.cpp' || echo './'`src/stubs.cpp
mv -f src/.deps/keeperfx-vidmode.Tpo src/.deps/keeperfx-vidmode.Po
src/vidmode_data.cpp:239:93: error: no matching function for call to ‘max(long unsigned int, unsigned int)’
239 |     {"*TEXTURE_PAGE",    (unsigned char **)&block_mem, NULL, max(sizeof(block_mem), 960*720u), 0, 0},// Store whole texture image or land view image
```

No matching function call to max()

---

src/bflib_vidraw.c
src/engine_render.c

Found a couple pointer casts that will not work on 64-bits

int is not large enough to hold 64-bit pointers

---

src/config_campaigns.c
src/config_objects.c
src/game_saves.c
src/main_game.c

This stores information in the log that I now need to ask often.
Fixes https://github.com/dkfans/keeperfx/issues/1505
Also updated the object loading information to specify the campaign it's for.

Add campaign name and level number info into log

---

src/creature_states.c
src/map_blocks.c

- Cleared up new_slab_tunneller_check_for_breaches function to make it obvious breaches only occur on explored slabs
- Stopped breaches from occurring by units inside a tunnel (with cubes above their head)
- The parchment map now shows the top slab instead of the floor slab in case of tunnels
Fixes a bug where tunnelers when they would cross a tunnel across the map into an enemy dungeon, would trigger a 'breach' notification for the player too.
Also closes #1468

Tunnel behavior improved - breaching and map colour

---

src/dungeon_data.h
src/game_loop.c
src/main.cpp
src/thing_list.c
src/thing_shots.c

Enemies will only attack the main one. After it is destroyed, the second one takes over.
Solves a bug where all soul containers would be destroyed if one lost health.

Handle 2 dungeon hearts

---

src/map_blocks.c

There's only rock crumble when the new slab is higher then the new slab, but it determined this based on just one column. Now each individual column determines if rock crumble is needed.

Now check each column for height to determine crumble

---

src/creature_states_combt.c
src/gui_soundmsgs.c
src/gui_soundmsgs.h
src/sounds.h
src/thing_creature.c

Done it for 'creatures are winning/losing' battle and 'creatures are attacking enemy' 'being attacked by enemy' messages.
Also stopped notifying for units joining a battle when they were already in the battle queue.

Stop playing mentor speeches of things happening on screen

---

config/fxdata/cubes.cfg
src/config.h
src/config_creature.c
src/config_crtrmodel.c
src/config_crtrstates.c
src/config_cubes.c
src/config_cubes.h
src/config_effects.c
src/config_lenses.c
src/config_magic.c
src/config_objects.c
src/config_rules.c
src/config_terrain.c
src/config_trapdoor.c
src/engine_render.c
src/game_legacy.h
src/game_merge.h
src/map_blocks.c
src/map_columns.c

In Unearth you can place custom slabs which contain custom columns which use cubes that are defined inside /fxdata/cubes.cfg
Extended beyond 511 to 1023, but it can be set to whatever value by adjusting `CUBE_ITEMS_MAX` and cubes.cfg

Cube count extended

---

src/front_input.c

fixes bug introduced in #1634 where you can't scroll in 2 directions by moving mouse to corner

fix map scrolling in corners

---

src/engine_render.h

Also set BUCKETS_COUNT to correct value. (this shouldn't matter much)

Stop thing objects disappearing at certain angles while fully zoomed out

---

src/config_settings.c
src/engine_render.c

The view distance setting in DK's settings menu now only affects the 1st person camera view. So you can still have the atmospheric fade effect if you want. (Loobinex's idea)
There are no performance concerns here, simply zoom in your camera if you want better performance, DK automatically handles the culling.

Always use max view distance in overhead view

---

src/magic.c
src/map_columns.c
src/map_columns.h
src/packets_input.c

You can now pick up gold in frail corners

---

src/creature_senses.c

when target is pushed into corner itself
To reproduce the bug, have a room like this: 
Then walk a unit into the corner from outside the room, as if you would want to wall-clip, and units inside would shoot at you from inside the room.

Stopped units from shooting through corner

---

src/thing_shots.c

Also fixed recent build warning and gold rubble being created at imp feet

Fixed dropping gold on random rooms

---

src/engine_render.c

- SlabSelector draw order adjusted
- in create_shadows(), 702 changed to BUCKETS_COUNT-2 this makes sense and matches add_draw_status_box()

SlabSelector draw order adjusted

---

src/engine_camera.c

It's in the dll and still needed. Fixes a bug where attacks in possession miss always.
To reproduce the bug, possess a lvl1 dragon and attack a lvl1 hero barbarian in possession. Notice you cannot hit him.

Set old eye height again

---

src/creature_states_hero.c

Old tunneler behavior was to find a dungeon it could go to, but when it would not it would simply tunnel to player 0 and walk into water if need be.
Modern tunneler behavior is smarter, but it should not be used with the classic bug enabled. It was used when no dungeon was found the tunneler could tunnel to.

Made sure modern tunneler behavior does not conflict with classic bug behavior

---

src/main.cpp
src/sounds.c

The main loop is a mess, even before I added the frametime measurements, which made it worse. It's better now, organised into three functions. Plus this is also preparation for delta time which explicitly needs to treat logic and draw separately.
Besides organisation I altered my frametime measurements to require one less function in the main loop, and I also moved this section of code out of the draw section and into `update_player_sounds()` (at the bottom of `update()`):
```
// Music and sound control
if ( !SoundDisabled ) {
if ( (game.turns_fastforward == 0) && (!game.numfield_149F38) ) {
MonitorStreamedSoundTrack();
process_sound_heap();
}
}
```

Reorganised main loop

---

src/room_util.c

Fixes #1709
The lair has multiple roles, for regular sleeping the checks would consider the size of the lair needed, but to heal it checked only for 1 free capacity.

Use lair size when looking for room the heal in

---

src/gui_parchment.c

The blinking of neutrals (as done in draw_overhead_creatures) on the parchment map, now works the same way as it did for neutrals on the minimap (as done in draw_overlay_creatures). Now it should be easier to recognize neutrals.

Pixels on parchment map blink for neutrals

---

src/front_input.c

The game is so old that it's got the language of "inverted" backwards in the options menu, old flight sims are now what's considered inverted these days.
This also changes the default, KeeperFX is a modern port so it should cater to modern expectations.

Invert mouse reflects modern standards

---

src/engine_render.c
src/light_data.c
src/thing_data.c
src/thing_data.h
src/thing_stats.c

- added `thingadd->time_spent_displaying_hurt_colour` so flashing red lasts the correct amount of time
- clear ThingAdd and LightAdd whenever creating a new Thing or Light
- altered `lightadd->interp_initialize` so it doesn't need setting for each new light
- renamed TF4F_Unknown80 to TF4F_BeingHit

fixed time spent flashing red when thing receives damage

---

src/creature_states_scavn.c
src/engine_camera.c
src/engine_camera.h
src/engine_render.c
src/magic.c
src/player_instances.c
src/power_hand.c
src/power_process.c
src/power_specials.c
src/thing_creature.c
src/thing_navigate.c
src/thing_navigate.h
src/thing_objects.c

- Possibly fixes an issue with the camera shifting around that some users reported
- Reset interpolation position in certain situations when Thing position greatly changes so Things don't visually fly across the map: Creature dropped by CPU, Teleport ability, Hold Audience, Armageddon, Steal Hero, Scavenged creature, moving the Call to Arms flag.

Fixed interpolation glitches

---

src/thing_shots.c

fixes #1013, #1727 and also the inconsistent red fade when possessing a creature (while lightning abilities are being used elsewhere by creatures).

fix 1st person palette issues caused by lightning attacks

---

src/magic.c

instead of the hurt sound.
Causes units to make a different sound. Most notable on the fly.

Use the slap sounds from the config when units get slapped

---

src/dungeon_data.h
src/keeperfx.hpp
src/lvl_script.c
src/lvl_script_commands.c
src/lvl_script_lib.h
src/main.cpp
src/power_hand.c
src/power_hand.h

SET_HAND_RULE([player],[creature],[rule_slot],[rule_action],[rule*],[param*])
Where:
[player] - The player’s name, e.g. PLAYER1.
[creature] - The creature name, e.g. BILE_DEMON. Includes ANY_CREATURE.
[rule_slot] - Rule slot a rule will be assigned to. There are 8 available slots per player's creature type: RULE0, RULE1, ..., RULE7
[rule_action] - ALLOW or DENY. Whether creatures that match the rule should be allowed/denied from being picked up. If you just want to disable or re-enable rule already stored in a slot, use DISABLE or ENABLE and leave the last two params (rule, param) empty.
[rule*] - only specify if rule_action is ALLOW/DENY. One of the following:
ALWAYS - all creatures match this rule until it is disabled or overridden
AGE_LOWER/AGE_HIGHER - only creatures whose time in …

New script command: SET_HAND_RULE

---

src/engine_render.c
src/light_data.h
src/main.cpp
src/packets.c
src/player_data.h

- fixed Thing positions lagging for 1 turn when pressing middle mouse button to flip the camera in FrontView
- fixed an interpolation issue when moving the mouse off the map in one position then back onto map elsewhere
- added `playeradd->mouse_is_offmap`

Fixes for interpolation and delta time, added mouse_is_offmap variable

---

src/frontmenu_ingame_map.c
src/gui_topmsg.c
src/packets_input.c
src/roomspace.c

- Fixed Call to Arms flag circles on minimap juddering while paused
- Onscreen message time now correctly affected by delta time
- While holding left-click to tag slabs, moving the cursor off the map and then back onto the map somewhere else caused a massive line of slabs to be tagged. That's now fixed with `fix_previous_cursor_subtile_when_offmap` variable.

bugs fixed: CTA minimap flag circles, onscreen message time, tagging

---

src/engine_render.c

fixes #1843
Apparently `thing->mappos.z.val` is briefly (for 1 turn) set to 65534 in certain situations. 65534 is very high up and causes the interpolation to fall all the way down during the next turn.
Don't know why this happens, but if this happens again in another recreatable way then that'll give us a hint.

fixed interpolation issue of Things falling from sky

---

src/thing_objects.c

Issue introduced in 2c456e4cffb24fc9641258a68660fc31b318c062, causes log errors like:
```
Error: get_dungeon_f: move_object: Tried to get non-existing dungeon 5!
```

Fixed looking for neutral dungeon on moving objects

---

src/bflib_math.c

Replaced calls to _lrotr with equivalent implementation.

_lrotr is non-standard

---

src/main.cpp

Fixed gold text not showing up when zoomed in too much in straight view

---

src/creature_control.h
src/creature_states.c
src/engine_redraw.c
src/game_legacy.h
src/magic.c
src/main.cpp
src/main_game.c
src/power_hand.c
src/power_process.c
src/power_process.h
src/room_entrance.c

- No new creatures to break the check for 0 creatures
- Fixed bug of not teleporting tortured units
- Named a var

Armageddon teleports units in torture, no units from portal while active

---

src/keeperfx.hpp
src/main.cpp
src/player_instances.c
src/player_instances.h

Somewhat conflicting, `main` is copying the first 17 but there are 19 defined and indexing is done modulus `PLAYER_INSTANCES_COUNT` so I'm leaning towards it being 19.

Added size to player_instance_info

---

src/creature_states.c
src/creature_states.h
src/main.cpp

Generates warning:
```
src/creature_states.c:458:3: warning: excess elements in array initializer
458 |   {NULL, NULL, NULL, NULL,
```
Either there are too many elements in states array or `CREATURE_STATES_COUNT` is too small.

Added sizes to states arrays

---

src/thing_shots.c

fixes and issue where projectiles clip through creature faces. Collision detection is based on thing-size which remains the same even after level up.

Rebound at creature center

---

src/room_list.c

by using room kind again.
Fixes a bug where DEFEND_ROOMS and ATTACK_ROOMS party objectives would not work.

Fixed defend rooms and attack rooms objectives

---

src/map_blocks.c
src/map_blocks.h
src/player_compchecks.c
src/spdigger_stack.c

Fixes #760. slab_is_safe_land checks the owner and returns true only if it's the specified player or neutral. We don't want that here.

Enemy path no longer blocks digging

---

src/config_creature.c

It now allows a heal_requirement if a creature can make a lair or can go toking.

Stop resetting heal_requirement to 0 for imps

---

src/thing_creature.c

prevents loads of stuck flyer situations

Flying units step up instead of slide up

---

src/config_effects.c
src/config_effects.h
src/lvl_script_commands.c
src/lvl_script_lib.c
src/lvl_script_lib.h
src/lvl_script_value.c
src/thing_list.c
src/thing_list.h

MOVE_CREATURE([player],[creature],[criterion],[count],[location],[effect]*)
Instantly moves [count] creatures fitting the criterion to [location].  Effect is optional, if unset, ball puff effect is used.
COUNT_CREATURES_AT_ACTION_POINT([action_point],[player],[creature],[target_flag_player],[target_flag])
Counts creatures in action point and stores the result in [target_flag].

New script commands: MOVE_CREATURE, COUNT_CREATURES_AT_ACTION_POINT

---

src/creature_groups.c
src/creature_states.c

When a hero party reaches a door, all followers will now help destroy the door, instead of them all waiting while the leader takes it out.

Followers help attacking doors

---

src/creature_states.c

When a unit remembers a door it once collided with, on payday it will get stuck on the memory.

Reset collided door position before looking for treasure room

---

src/thing_creature.c

this would happen when they where placed on the door slab by the mapmaker

Neutral creatures colliding with doors no longer break them

---

src/frontmenu_ingame_map.h

Needed to make this change to overcome error when linking `keeperfx.exe`.
Not sure why this doesn't fail on the CI or for other people.

Add missing extern to frontmenu_ingame_map.h

---

src/lvl_script_commands.c
src/lvl_script_conditions.c
src/lvl_script_lib.h
src/lvl_script_value.c
src/packets.c
src/player_data.c
src/player_data.h

Resolves #776 
Used the last 3 unused bits in `player->allied_players` to represent which allies (blue, green, yellow) are locked. This means that this functionality is currently limited to single player.
**Changes to `ALLY_PLAYERS`:**
* Unlocked enemy: `ALLY_PLAYERS(PLAYER1,PLAYER2,0)`
* Unlocked ally: `ALLY_PLAYERS(PLAYER1,PLAYER2,1)`
* Locked enemy: `ALLY_PLAYERS(PLAYER1,PLAYER2,2)`
* Locked ally: `ALLY_PLAYERS(PLAYER1,PLAYER2,3)`
**New command: `IF_ALLIED({PLAYER},{PLAYER}{OP}{VALUE})`:**
Allows you to check the ally status of any two players. This will allow all sorts of use cases, such as forming a reply alliance in single player, or special events in multiplayer if two particular players are allied.
**Example script:**
Add this to the end of Korros Tor …

Implement #776: Level script - fixed alliances

---

src/map_utils.c
src/map_utils.h
src/player_compevents.c

also accept CTA positions where creatures cannot be dropped
Fixes #1894

Made sure computer players drop at the correct location to destroy doors

---

src/bflib_client_tcp.cpp
src/bflib_client_tcp.hpp
src/bflib_nethost_udp.cpp
src/bflib_nethost_udp.hpp
src/bflib_netlisten_udp.cpp
src/bflib_netlisten_udp.hpp

Fixes warning:
```
src/bflib_nethost_udp.cpp: In constructor ‘UDP_NetHost::UDP_NetHost(const StringVector&)’:
src/bflib_nethost_udp.cpp:34:28: warning: cast between incompatible function types from ‘void (*)(UDP_NetHost*)’ to ‘int (*)(void*)’ [-Wcast-function-type]
34 |  thread = SDL_CreateThread(reinterpret_cast<int (*)(void *)>(threadFunc), "UDP_NetHost", this);
|                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sdl/include/SDL2/SDL_thread.h:132:59: note: in definition of macro ‘SDL_CreateThread’
132 | #define SDL_CreateThread(fn, name, data) SDL_CreateThread(fn, name, data, (pfnSDL_CurrentBeginThread)SDL_beginthread, (pfnSDL_CurrentEndThread)SDL_endthread)
|  
```

Fixed warning in src/bflib_nethost_udp.cpp

---

tool_dkillconv.mk
tool_peresec.mk
tool_png2bestpal.mk
tool_png2ico.mk
tool_pngpal2raw.mk
tool_po2ngdat.mk
tool_rnctools.mk
tool_sndbanker.mk

Fixes the following warning:
`make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.`

Jobserver warning

---

src/player_compevents.c
src/roomspace.c

Fixes the following warnings:
```
src/roomspace.c: In function ‘update_slab_grid’:
src/roomspace.c:1502:82: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
1502 |                             roomspace->slab_grid[x][(roomspace->height - 1) - y] = false;
In file included from src/player_data.h:26,
from src/game_legacy.h:26,
from src/roomspace.c:24:
src/roomspace.h:71:12: note: at offset 0 to object ‘slab_grid’ with size 400 declared here
71 |     TbBool slab_grid[MAX_ROOMSPACE_WIDTH][MAX_ROOMSPACE_WIDTH];
|            ^~~~~~~~~
src/roomspace.c:1497:82: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
1497 |                             roomspace->slab_grid[x][(roomspace->height - 1) - y] = true;
In file included from src/player_data.h:26,
from …
```

Fixed warnings in src/roomspace.c

---

src/creature_states_spdig.c
src/thing_creature.c

When workers can't return a crate they found to the workshop - for example because of a locked door - but there is an unarmed trap on the map, they will use the crate to arm a trap. However, when the player placed the trap, the 'available traps' counter went down and a crate in the workshop was earmarked for arming it.
Using the found crate to arm the trap, the count is now too low, and a crate is stuck forever in the workshop.
Also, in much the same way, when a modder changes their game files to make other room types create crates, these will generally be used by imps to arm traps even when the workshop can be reached and create the same problem.
I fixed this by after arming a trap, checking if there is still a crate earmarked to arm the already armed trap, and if there is, 'refund' the …

Prevent ghost-crates when arming traps with found crates

---

Makefile

Add -Wno-shadow when building deps/zlib/contrib/minizip/unzip.c

Ignore zlib warning

---

src/engine_render.c

possession should look better now, (ceiling is seperate from this PR) rest should look ok

small maps: fix wrong columns in possession

---

src/map_ceiling.c

last time I checked the last quater of the map the ceiling touched floor, now on same map this no longer happens, not sure what fixed it but seems fine now

enable rewritten version of ceiling_init

---

src/creature_battle.c
src/creature_states_hero.c
src/room_data.c
src/thing_navigate.c
src/thing_navigate.h

Heroes wanting to attack rooms would not do so until they had access to filled rooms or rooms connected to the dungeon heart. Now they will attack the rooms when they can.

Heroes also attack empty disconnected dungeon rooms

---

src/spdigger_stack.c

Unexplored subtiles are no longer untagged when an enemy reinforces them

---

src/globals.h
src/lvl_filesdk1.c
src/main.cpp
src/map_blocks.c
src/map_columns.c
src/map_data.c
src/map_data.h
src/player_utils.c
src/power_process.c

purely for readability, shouldn't impact functionality

seperate the revealed bitflag from mapblk data field

---

src/config_campaigns.c

fix mappacks only containing lof files and no lifs in the free map packs section not showing up

fix lof only mappacks showing

---

src/frontend.cpp
src/frontend.h
src/main.cpp
src/vidmode.c

This applies to both querying and possession.
Fixes #2125

Game now remembers which query menu was active when changing resolution

---

src/frontend.cpp

Happened on clean installation or corrupt continue-save.
Fixes #2146

Fixed room names missing when no campaign is loaded

---

src/creature_groups.c

This warn heavily spams the log when the command is used in a loop

Removed warning message for delete from party

---

src/game_saves.c

Changing the game-structure can cause continue-saves to not work. Unfortunately, once that happens they may remain corrupt forever or until the user manually deletes the file.
Now the game deletes the file when it can't use it.

Delete non-functional continue-game files to make continue save work again

---

src/thing_list.c

Function would loop through only a small part of units.
```
USE_POWER_ON_CREATURE(PLAYER_GOOD,ANY_CREATURE,ON_ENEMY_GROUND,PLAYER0,POWER_CHICKEN,3,1)
```
This script command should convert all heroes on red ground to chickens. It did only a small part.

Fixed get_player_list_nth_creature_of_model_on_territory

---

src/config_magic.c

Prevents this log entry:
Warning: parse_magic_special_blocks(line 1573): Incorrect value of "SPEECHPLAYED" parameter in [special9] block of global magic config file.

No longer warn in the log when 0 is set as a speech played

---

src/creature_senses.c

Fixes issue with flying vampires on a guardpost (up high) not seeing units properly and deciding to flee.

Creatures that can move over lava can now also see the sides of creatures

---

src/thing_list.c

not finding anything is not an error, but it filled the log with thousands of errors saying:
```
Error: get_player_list_nth_creature_of_model_on_territory: Tried to get creature of index exceeding list
```

stop the list getting filled with errors due to not finding units

---

src/game_lghtshdw.h
src/light_data.c

Found the ambient light value, you can make the game look extra dark, or full-bright and ugly like Unearth.
(i adjusted it inside of `light_set_lights_on()` and `clear_stat_light_map()` functions to take these screenshots)

renamed field_46149 to global_ambient_light

---

src/bflib_fileio.c

Should fix issues with corrupted continue saves sticking around.
Draft, because I have trouble reproducing the bug at this point. Need a corrupted continue save to test.

Truncate save-files when they are too large

---

src/frontmenu_ingame_evnt_data.cpp
src/frontmenu_ingame_tabs.h

63 was used for both a trap button, and the zoom eye

Clear up duplicate tutorial flash buttons

---

src/room_entrance.c

armageddon.count_down is 500 turns, but who cares when it has not been cast yet
fixes #2230

Also spawn creatures in the first 500 gameturns

---

src/creature_states.c
src/room_data.c
src/room_data.h
src/slab_data.c

The log provided errors: `Error: find_random_valid_position_for_thing_in_room: Taking random slab (40/57) in LAIR index 5 failed - internal inconsistency.`
And creatures would have trouble finding lairs in rooms when creatures with model number > 32 would already have a lair there.

Fixed creatures not making lairs after extra creature did

---

src/bflib_vidraw.c

Properly scale frame on landview

---

src/packets.c
src/packets_input.c
src/roomspace.c

Fixes bug introduced on #2196
To reproduce the bug:
1) Pick up any unit
2) Try to mark/tag for digging with either Shift of Ctrl
-> Notice it does not go into one-click mode
I fixed it in a way that Ctrl-Pickup of gold hoards still works.

Fixed one-click-marking with creatures in hand

---

src/creature_states.c

Many log files get filled up with this warning:
```
Warning: creature_setup_adjacent_move_for_job_within_room_f: process_torture_visuals: No position to move creature VAMPIRE index 273 in TORTURE room
```
To reproduce that, place a unit with healing into a 1x1 torture room with a door and frameskip for a bit.
The problem is caused because the 'person_get_somewhere_adjacent_in_room_f' went out and found out a valid position inside the room, and only then checked if the creature radius would put it partly inside the wall at that position. At this point it would fail and throw a log error, instead of looking for a space a bit further away from the wall.

Fixed creatures not seeing a place to walk

---

src/frontmenu_ingame_map.c

Minimap was updated during slab change from door -> no door, then it was both a door and not a door, so provided error messages in the log. Removed error message.

No error on destroyed door

---

src/creature_states_combt.c
src/thing_list.c
src/thing_list.h

Many logs are filled with errors that state:
`Error: check_for_possible_combat_with_enemy_creature_within_distance: The creature GIANT index 204 cannot fight with creature IMP index 363 returned as fight partner`
This is because it uses the function `get_highest_score_enemy_creature_within_distance_possible_to_attack_by` uses `creature_can_have_combat_with_creature`, then later to check does `creature_can_have_combat_with_creature` and then considers it an error that the filter has found a creature it can in fact not have combat with.
But this happens because they get fed different values on the 'move_on_ground' param, so a different result is possible.

No longer give error on two different combat filters giving different results

---

src/creature_states_lair.c

Dropping units into a lair with enough capacity would sometimes have a unit try to make a bed in another lair room, because another bed was in their way. Now they will look for another spot in the same room, provided there is still capacity.

fixed creatures making a lair elsewhere if they are standing on a lair totem

---

src/thing_shots.c

Exploding shots are not used by creatures against objects in general, to avoid friendly units in the explosion. But now that makes sense. Behavior similar to attacking doors.

Shots explode on hearts too, when applicable

---

src/lvl_script_commands.c

CREATE_EFFECT and similar commands would no longer create effect elements. Now it works again.
To test, spawn hearts on your heart:
```
CREATE_EFFECT(-45,PLAYER0)
```

Allow spawning effect elements through script again

---

src/slab_data.c

Makes building up against a neutral/allied/enemy walls provide the same room efficiency as building up against dirt and rocks.
Non-owned doors still give 0 points..

Made non-player walls give 1 efficiency point

---

src/creature_states_pray.c
src/creature_states_pray.h
src/lvl_script_commands.c
src/lvl_script_lib.h

USE_SPELL_ON_PLAYERS_CREATURES([player],[creature],[spell],[spell_level]*)
Also changed the last param to be optional here:
USE_SPELL_ON_CREATURE([player],[creature],[criterion],[spell],[spell_level]*)

USE_SPELL_ON_PLAYERS_CREATURES script command

---

src/config_magic.c

Fixes #2387
That issue was introduced in [#2356](https://github.com/dkfans/keeperfx/pull/2356/files)

Do not break powers when unspecified on campaigns

---

src/room_data.c

When using level script to change neutral rooms, the log would fill with errors like:
`Error: get_dungeonadd_f: count_slabs_of_room_type: Tried to get non-existing dungeon 5!`
This is because it would try to count the number of slabs the dungeon owned, but neutral is no real dungeon.

Don't try to count the amount of slabs for neutral dungeons.

---

src/thing_list.c

if mapmakers want to cast on the spectator, they can by naming the model

Don't cast on spectator when using 'any creature'

---

src/thing_data.c

Fixes a bug with disease flies or armour lights not knowing where to go. To see the bug in action, add this to a level script and start the game with heart zoom enabled:
```
USE_SPELL_ON_PLAYERS_CREATURES(PLAYER0,ANY_CREATURE,SPELL_DISEASE,1)
```

Delete attached effects when thing structure is deleted

---

src/gui_tooltips.c
src/lvl_script_lib.c
src/power_specials.c
src/thing_creature.c
src/thing_factory.c
src/thing_objects.c
src/thing_objects.h

Allows mapmaker to give different custom boxes a different look.
To make it work:
- in objects.cfg add a new object with `Genre = SPECIALBOX`
- in magic.cfg increase the SpecialsCount and add a new special, where the artifact is the new object

Any object can be a custom mystery box

---

src/frontmenu_ingame_tabs.c

Freeze greys out unusable spell icons in menu

---

src/creature_states_hero.c

Fixes bug where unit defending room tried to steal non-existing traps.
Enums CHeroTsk_DefendRooms and CrSt_CreaturePicksUpTrapObject  are both 11, so it took the wrong job.
Add this party to a level to test:
CREATE_PARTY(watchmen)
ADD_TO_PARTY(watchmen,FAIRY,8,200,DEFEND_ROOMS,120)
ADD_TO_PARTY(watchmen,THIEF,8,200,DEFEND_ROOMS,120)

Use state as continue_state for defend rooms

---

Makefile

There's a bizarre issue that may only affect certain Windows PCs (not all) when attempting to compile the source code for the first time.
The error is at the bottom of this log:
```
D:\Github\keeperfx>wsl make standard
make -f libexterns.mk
make[1]: Entering directory '/mnt/d/Github/keeperfx'
Extracting package: sdl/SDL2-devel-2.28.1-mingw.tar.gz
cd "sdl"; \
tar --strip-components=2 -zxmUf "SDL2-devel-2.28.1-mingw.tar.gz" SDL2-2.28.1/i686-w64-mingw32/bin SDL2-2.28.1/i686-w64-mingw32/include SDL2-2.28.1/i686-w64-mingw32/lib SDL2-2.28.1/i686-w64-mingw32/share 2>&1 | \
grep -v '^.*: Archive value .* is out of .* range.*$'
make[1]: [libexterns.mk:45: sdl/lib/libSDL2main.a] Error 1 (ignored)
Finished extracting: sdl/SDL2-devel-2.28.1-mingw.tar.gz
Extracting package: …
```

makefile: create configure.log file first to avoid (rare?) error

---

src/creature_graphics.c
src/creature_graphics.h
src/thing_effects.c
src/thing_effects.h
src/thing_objects.c

Protections against a crash with modded objects and or animations with no animation length.
To reproduce the bug, put this in a map script and wait 5 seconds for a crash:
```
IF(PLAYER0,GAME_TURN > 60)
ADD_OBJECT_TO_LEVEL(SPECBOX_INCLEV,PLAYER0,0,PLAYER_NEUTRAL)
ENDIF
IF(PLAYER0,GAME_TURN > 100)
SET_OBJECT_CONFIGURATION(SPECBOX_INCLEV,UpdateFunction,UPDATE_POWER_SIGHT)
ENDIF
```
Also named some effect element fields.

Protect against neutral power sight crash

---

src/lvl_script_commands.c

SET_TRAP_CONFIGURATION and SET_DOOR_CONFIGURATION allow you to set the ManufactureRequired. However, common values are already 50000, but it allowed only up to a SHORT value to be set (32k).
This is now changed to allow LONG values.
The rest of the variables should still work, even those with multiple values.

Allow ManufactureRequired to be properly set through script

---

src/bflib_inputctrl.cpp

Since e47a9172ff9852a062b55407ae7aadf5a6808e07 the behavior with -altinput is different. When I start up the game with the -altinput command line option, depending on where I have my cursor when it loads, the hardware cursor reaches the edge of the screen before the keeperfx cursor does, so I can not click the menu buttons in the bottom right of my screen.
This PR fixes this.

Fixed mouse not reaching every spot on screen with -altinput

---

src/lvl_script_commands_old.c
src/lvl_script_value.c
src/power_specials.c
src/thing_creature.c
src/thing_creature.h

SET_CREATURE_LEVEL now accepts negative values. Example:
`LEVEL_UP_CREATURE(PLAYER0,BILE_DEMON,MOST_EXPERIENCED,-7)`
Also, allows values over 9, so level ups can be done a lot more in case of growing up creatures.

Allow negative increase level from script

---

.gitignore
.vscode/tasks.json
Makefile

Here's a method to call both `make clean` and `make standard` but only 'clean' when necessary. I haven't tested it super thoroughly yet, there could be problems with it.
I'll just go over the basics for anyone out of the loop:
- `make clean` is necessary to run whenever you edit a header file (.h, .hpp), otherwise massive issues occur.
- If you run `make standard` twice in a row, the second time will be much faster.
- If you run `make clean`, then `make standard` will be slow.
- `make all` currently runs `make clean` then `make standard` right after, so it's always slow.
There's a lot of benefits to having only one function to call both. Such as not running into bugs if you edit a header file but forget to call `make clean`. Having only one function to run will also work well with …

makefile: Dynamically choose between 'make standard' and 'make clean'

---

src/map_blocks.c

Recently (5a163dc2de644a04d08196f2be4da4d0e0aecd9c) keys got moved from height 4, to height 5, to be on top of doors. This introduced a bug with braced doors, that keys were thrown off.
Found code that moved all things on slab-change to floor height. This includes doors, which changes the door-things from height 5 to height 1. It however excluded things with model 2 (suspect this was for _object_ thing model 2, torch) that kept the original height. Braced door is door 2, and so this conflicted.
I kept the weird code as it is and only handled this specific case. I was unwilling to change more because at this point I have not investigated if:
- Door things should be height 5 or height 1, and if there are bugs related to either height
- If in the original game doors things had height 1 or …

Fixed braced doors placing weird keys

---

Makefile

On a fresh install (git clone) on my Linux laptop it took upwards of 5 `make all` calls before it stopped calling 'clean', because .h files everywhere kept changing by themselves inbetween each compile (there's .h files inside folders such as `/deps/`, `/sdl/`, and `/obj/` sometimes). Not sure whether this is only a fresh install issue, but even if it is then that's a bad first impression that needs fixing.
Looking at only header files inside the `/src/` folder fixes the issue, on a fresh install it correctly stopped cleaning after the first compile. I've also adjusted the code to now output the names of any header files that have changed.

makefile: fix too much cleaning in new `make all`

---

src/config_campaigns.c
src/frontmenu_ingame_tabs.c
src/game_merge.c
src/light_data.c
src/map_data.c
src/map_data.h
src/player_utils.c
src/thing_creature.c

to reproduce the crash, start the game with a -level command line option to a level that does not exist.

Fixed crashes on starting a non-existing level

---

.gitignore
.vscode/settings.json
.vscode/tasks.json
Makefile

I've added a lot to the VSCode default built task (`Ctrl`+`Shift`+`B`), it now compiles, copies the files to your game directory and runs the game, all automatically. I've tested on both Windows(WSL) and my Linux laptop, everything's working great and we don't even need to call any external bash scripts.
The one and only requirement is that every user needs to go fill out `settings.json` with their game directory. It's unfortunate we have this extra step but I believe this is the most user-friendly path we can take. In comparison, manually copying files from `//wsl$` directories is very unfriendly.
It's set up so that the build task will instantly fail and give you bright red text in the terminal that tells you to go fill it out. There's instructions to do so inside of `settings.json` and …

Enhanced tasks for VSCode

---

.gitignore
.vscode/defaultuser
.vscode/settings.json
.vscode/tasks.json

#2545 makes use of `--skip-worktree` to ignore personal changes made to settings.json, however this causes issues when switching branches and in some cases it won't even let you switch branch because the file is different. That's pretty unfriendly.
So instead this time we'll go with the approach of creating a user.json file upon starting VSCode. When switching branches, this file will stay.
The downside is we need to instruct users to run `sudo apt-get install jq` which is a lightweight app for reading json files, and it won't let me write comments in the defaultuser (user.json) file, so those instructions will have to go in the guide.

Enhanced VSCode tasks, different approach

---

Makefile

`make all` is taking an extra ~2 seconds or so due to the silly changes I made in #2544 to make it write ALL the checksums to .header_checksum and print all changes to the terminal. My first method was a lot faster.
I've kept the ./src/ change I originally made, so only files in the /src/ directory will be looked at. And I've also made another change to use md5sum instead of sha256sum, which is also a little faster.

fix make all being slow

---

src/lvl_script_conditions.c

It did not accept slab_x over 127

Fixed IF_SLAB_TYPE and IF_SLAB_OWNER on big maps

---

Makefile

also using cksum instead of md5sum as it's 0.04 seconds faster https://github.com/dkfans/keeperfx/pull/2553#issuecomment-1691161141

makefile: Compile times printed for 'make all'

---

src/engine_render.c
src/engine_render.h

Fixes this behavior when placing slabs on the south side of big maps:
Also cleaned up some unused fields

Fixed big map trap placing beyond slab 127

---

.vscode/tasks.json

The tasks.json now supports three OS configurations:
- Linux
- Windows WSL (VSCode in WSL mode)
- Windows
I also made a discovery, tasks are slow as hell when you string them together. It was adding ~1.5 seconds while in WSL mode and ~7 seconds in Windows mode. Something as simple as printing using echo 5 times like this is very slow:
```
{
"version": "2.0.0",
"tasks": [
{
"label": "Check For jq Installation",
"type": "shell",
"command": "echo 1",
},
{
"label": "Check For Game Directory",
"type": "shell",
"command": "echo 2",
"dependsOn": "Check For jq Installation",
},
{
"label": "Compile",
"type": "shell",
"command": "echo 3",
"dependsOn": "Check For Game Directory",
},
{
"label": "Copy Files",
"type": "shell",
"command": "echo 4",
"dependsOn": "Compile",
},
{
"label": "Compile, Copy …
```

VSCode tasks now support Windows (non-wsl) + some reorganizing

---

src/lvl_script_commands.c

Fixes an issue with custom music not loading. To reproduce:
1) Download and install this campaign: https://www.file-upload.net/download-15181910/NeuerOrdner.zip.html
2) Launch the game with the -nocd command line option so that music can play
3) Start the second map of the campaign. Dig north to fight heroes or cheat units so that a battle starts.
-> battle music starts playing
4) Exit the level
5) Use cheats to start the first level of the campaign now
-> notice no music starts playing.
Music should start playing.

Fixed issue with not loading custom music

---

src/thing_objects.c

On certain old maps, keys have a position of 4.5, but when we were setting their new position to 5, we weren't setting the decimal place so they were at 5.5 which throws the key off the door.
#2523
#2525
#2547

Fix keys falling off doors on strange maps

---

.vscode/tasks.json
Makefile

Unfortunately it's been launching the executable regardless of whether the compilation succeeds, creating confusion.
That's fixed now. A small edit also had to be made to the makefile to propagate the "make standard" error code to the "make all" request.

vscode tasks: when compilation fails, stop and show error message

---

.vscode/c_cpp_properties.json
.vscode/defaultlaunch
.vscode/defaultlinuxscript
.vscode/defaultsettings
.vscode/defaultuser
.vscode/extensions.json
.vscode/settings.json
.vscode/tasks.json
src/main.cpp
src/music_player.c
version.mk

I've finally gotten gdb fully working (I only had it partially working before) and integrated with VSCode. The key part that took me a while to understand was to compile with `DEBUG=1` as an argument, like: `make -j8 DEBUG=1 all`. It now tells you the exact line which causes a crash.
`DEBUG=1` produces a much larger executable packed with debugger symbols, allowing the function names and line numbers to actually be read, and probably helps with whatever other features gdb has.
When you press F5 to run `launch.json`, it'll first run the `preLaunchTask: "Compile, Copy Files"` and if that succeeds then it'll launch the executable with debugging. Users need to edit and fill out `launch.json` with their game directories (or edit the linux script).
When there's a crash, the game executable …

VSCode debugging

---

src/player_comptask.c
src/player_computer.h

A recent bugfix made computers avoid temples and portals when dropping units, this made them unable to sacrifice since they avoided temple pools.
Now I skip the 'dangerous drop site' check when sacrificing. Fixes #2589

No longer scared of temple floor when sacrificing

---

src/creature_instances.h
src/creature_states_combt.c

Allows modders to make new buffs that are used by creatures.

Auto cast all buffs not predefined

---

src/globals.h

These structs and variables are used all over the code, it is good to clear up their meaning.
I can now hover over the above structs and variables in VS Code to see the added comments.

add comments to Coord2d and Coord3d

---

src/thing_traps.c

Cannot be seen on the default traps, would work on traps that look like a true cannon.

Ranged traps rotate in the direction of the thing they shoot

---

src/thing_objects.c

Add this script to a map:
```
REM The red flag is now a dungeon heart, a beating heart with the update function and 18000 health
SET_OBJECT_CONFIGURATION(GUARDFLAG_RED,Health,18000)
ADD_OBJECT_TO_LEVEL(GUARDFLAG_RED,1,0,PLAYER0)
SET_OBJECT_CONFIGURATION(GUARDFLAG_RED,Properties,96)
SET_OBJECT_CONFIGURATION(GUARDFLAG_RED,UpdateFunction,UPDATE_DUNGEON_HEART)
IF(PLAYER0,GAME_TURN > 80)
REM The soul container is just a regular object
SET_OBJECT_CONFIGURATION(SOUL_CONTAINER,UpdateFunction,0)
SET_OBJECT_CONFIGURATION(SOUL_CONTAINER,Health,0)
SET_OBJECT_CONFIGURATION(SOUL_CONTAINER,Properties,4)
ENDIF
```
Run the map and notice a crash. `SET_OBJECT_CONFIGURATION(SOUL_CONTAINER,Health,0)` crashed it. Added some divide by 0 code.

Fixed crash when heart is configured to be 0 health

---

src/lvl_script_commands.c
src/map_blocks.c

- Fixes #2631
- Gives a script error that is informative when out of range: `Error: conceal_map_rect_check(line 75): Conceal coordinates out of range, trying to conceal from (0,-20) to (360,325) on map size 360x345`
- Allows 0 as a value on [hide revealed] param

Fixed CONCEAL_MAP_RECT for bigmaps and provided better log info

---

config/keeperfx.cfg
src/bflib_video.c
src/bflib_video.h
src/config.c

Default (with no value in cfg file) is 1, which is the primary/first/only display.
Setting `display_number=1` ( which will set `display_id=0`) is exactly the same as current master (i.e. `SDL_WINDOWPOS_CENTERED` is the same as `SDL_WINDOWPOS_CENTERED_DISPLAY(0)`)*
Usage:
e.g. putting the following in the config file will cause keeperfx to run on the 2nd monitor.
```
; The display to use for the game
DISPLAY_NUMBER=2
```
implements #2345
(commented updated to reflect new behaviour in b9bb953)
____
*_"Looking at the definition of SDL_WINDOWPOS_CENTERED in SDL_video.h we see it is defined as 
`#define SDL_WINDOWPOS_CENTERED         SDL_WINDOWPOS_CENTERED_DISPLAY(0)`
so we could also use the macro SDL_WINDOWPOS_CENTERED_DISPLAY( n ) where n is the display index."_ - …

allow choosing of display number via config file

---

src/front_landview.c
src/front_landview.h

More level numbers than Link can hold rupees.

Allow more multiplayer level numbers

---

src/player_utils.c

To reproduce the issue, start a map early in the campaign, claim the portal, use the reveal cheat then frameskip while the fly explores.
Come back to hundreds of log lines like this:
```
Sync: [935] creature_explore_dungeon: The creature FLY owned by player 0 can't navigate to subtile (196,112) for exploring
Sync: [937] creature_explore_dungeon: The creature FLY owned by player 0 can't navigate to subtile (187,121) for exploring
Sync: [939] creature_explore_dungeon: The creature FLY owned by player 0 can't navigate to subtile (136,127) for exploring
```

Stop log warning spam when exploring already explored map

---

src/config_campaigns.c

To reproduce the issue:
1) Start up a campaign where the player is not red. ((example)[https://keeperklan.com/threads/7384])
2) Exit the campaign
3) Start a campaign where the human player is not specified. (Basically any campaign besides the original one)
-> notice you start as the non-red player

Make sure human player is 0 if it's not specified in campaign config

---

src/creature_states_spdig.c

Fixes a bug where imps limited in level with `SET_CREATURE_MAX_LEVEL` but were configured to get work experience, would still get XP. They would not level up, but gain a level worth of xp each time.

Working imps do not get XP when they are at max level

---

config/keeperfx.cfg
src/config.c
src/config.h
src/keeperfx.hpp
src/main.cpp

* Can now override config file from command line
* example: `-config foo.cfg` on the command line to load "foo.cfg" instead of "keeperfx.cfg"
* added `MUSIC_FROM_DISK=ON/OFF` config setting
* added `-cd` command line option
*  `-nocd` command line option no longer functions, and a warning is written to the log if it is used.
* default to music from files in a folder rather than CD
* added command line overrides functionality - so that a command line option can supersede a config option
* the first of these is -`cd`
I'll finish #2535 in a separate PR - i.e. allow custom tracks to be played when triggered by "SET_MUSIC", no matter what `Ft_NoCdMusic` is set to.

Cmd line options and config

---

src/frontmenu_ingame_tabs.c

Good:
Bad:
Should now be good in any resolution

Correctly position the little background in the imp menu

---

config/keeperfx.cfg
src/bflib_inputctrl.cpp
src/bflib_video.c
src/bflib_video.h
src/config.c
src/config_settings.c
src/config_settings.h
src/frontmenu_options.c
src/main.cpp
src/packets.c
src/vidmode.c
src/vidmode.h

* New config settings for screen resolutions:
* "DESKTOP" can be used for a borderless window that fills the whole screen (fake fullscreen).
* "DESKTOP_FULL" can be used for a real fullscreen mode that matches the current desktop.
* "ALL" can be used for a borderless window that fills all screens. YMMV.
* WxHx32 still gives real fullscreen at the given res.
* WxHw32 still gives a normal window at the given res.
* Launcher Settings already allows you to type these new settings, and will not complain*.
* `LbHwCheckIsModeAvailable` now actually checks the modes again (previously it just returned true without checking)
* screen mode is checked every time before switching, as different displays may support different modes.
* `display_id` stored internally instead of `display_number` - Config …

can now use "DESKTOP" as a screen res in config file - provides a "borderless fullscreen window" mode

---

src/creature_states.c

Fixes an issue where torture victims moving from left side to right side of U shaped torture room can get picked up by original owner:

Fixed U-shaped rooms releasing torture victims

---

Makefile
src/bflib_crash.c
src/main.cpp

Changes the stack trace code to include symbol names.
- Uses `SymFromAddr` to resolve OS calls
- If it doesn't find one it will try and use the map file
- Has an extra fallback if neither of the above worked
Before:
```
=== Crash ===Error: Attempt to read from inaccessible memory address.
in msvcrt.dll at 0023:656d9cc7, base 65680000
in keeperfx.exe at 0023:00436034, base 00400000
in keeperfx.exe at 0023:00443aad, base 00400000
in keeperfx.exe at 0023:005686a5, base 00400000
in keeperfx.exe at 0023:0051a6ab, base 00400000
in keeperfx.exe at 0023:00508026, base 00400000
in keeperfx.exe at 0023:00527fb4, base 00400000
in keeperfx.exe at 0023:004f663d, base 00400000
in keeperfx.exe at 0023:0050a04c, base 00400000
in keeperfx.exe at 0023:00600217, base 00400000
in keeperfx.exe at …
```

resolve stack trace symbols and look up using address map file

---

src/packets.c

My game kept crashing when trying to start it. This fixed it.
I think my game got corrupted by loading a packet from somebody else where I was missing the map.

Protection against a divide by 0 error on packet control

---

src/main.cpp

Example:
```
Sync: Operating System: Windows NT 10.0.18362
Sync: Running on Wine v8.0.2
Sync: Wine Host: Linux 6.5.0-13-generic
```

log wine version and host OS

---

config/fxdata/trapdoor.cfg
src/config_trapdoor.c
src/config_trapdoor.h
src/lvl_script_commands.c
src/player_instances.c

Complement to PR #2673 as feedback to @Loobinex feedback that it's strange that doors doesn't have configurable sounds when the traps has them. Basically the same code as the traps

Made placement sound of doors configurable

---

Makefile

lvl_filesdk1 and custom_sprites both need obj/ver_defs.h Now obj/ver_defs.h is requested explicitly when making lvl_filesdk1 and custom_sprites, rather than hoping that another task will have already built obj/ver_defs.h. This was only an issue when using multiple threads to compile.

Stop compile errors due to missing obj/ver_defs.h

---

src/creature_states_spdig.c

Before, when Imps were claiming rooms, they just kept going at normal speed (despite appearing to be faster than normal). after the spell expired.

Imps recast Speed when claiming rooms

---

src/light_data.h

For fixing Carbon's map. If this value is too low, then the cursor light won't spawn if the map has too many lights.
These lights on the map don't need to just be manually placed Lights, lots of things create their own light such as Dungeon Hearts and Lava. (this limit can be reached easily)

increased LIGHTS_COUNT

---

src/gui_tooltips.c

When you move your cursor to a new slab position, the tooltip timer now resets.
The generally expected behaviour of tooltips (in operating systems and software) is that you keep your mouse cursor still. However DK allowed you to move your cursor across multiple slabs of the same type while the tooltip annoyingly wouldn't disappear.
I also increased this particular tooltip's time by 50% (30 turns instead of 20). Tooltips have a lot of arbitrary appearance times (some are 10 turns, some are 20), so I don't believe I'm stepping out of bounds by increasing the most annoying one to 30.

Less sticky slab tooltips

---

src/bflib_crash.c
src/bflib_render.c
src/bflib_render.h
src/bflib_video.c
src/bflib_video.h
src/main.cpp
src/vidmode.c

Old log: [keeperfx.log](https://github.com/dkfans/keeperfx/files/13694284/keeperfx.log)
new repeated crash:
```
=== Crash ===
Error: Attempt to read from inaccessible memory address.
[#15]  in   keeperfx.exe : trig_render_md10                         [0x450ba0+0xfb]     (map lookup for 0023:00720c9b, base: 006d0000)
[#14]  in   keeperfx.exe : trig                                     [0x452950+0x338]     (map lookup for 0023:00722c88, base: 006d0000)
[#13]  in   keeperfx.exe : draw_view                                [0x4e6440+0x45e8]     (map lookup for 0023:007baa28, base: 006d0000)
[#12]  in   keeperfx.exe : engine                                   [0x5fa570+0x149]     (map lookup for 0023:008ca6b9, base: 006d0000)
[#11]  in   keeperfx.exe : draw_creature_view …
```

Potential fix for crash in trig_render_md10

---

levels/deepdngn/map00091.magic.cfg
levels/deepdngn/map00091.txt
src/frontmenu_ingame_tabs.c
src/gui_tooltips.c

comes with new binaries
Fixes #177
[map00091.zip](https://github.com/dkfans/keeperfx/files/13742562/map00091.zip)

Purple potion must now be picked up by player for bridge to work.

---

config/fxdata/objects.cfg
src/config_crtrmodel.c
src/config_magic.c
src/config_objects.c
src/config_objects.h
src/config_trapdoor.c
src/creature_states_lair.c
src/custom_sprites.c
src/custom_sprites.h
src/game_merge.h
src/gui_tooltips.c
src/lvl_script_commands.c
src/main.cpp
src/map_blocks.c
src/room_data.c
src/sounds.c
src/thing_list.c
src/thing_objects.c
src/thing_objects.h
src/value_util.c

last non configurable fields now configurable, and cleaned up old struct

Merge objectsstructs

---

config/keeperfx.cfg
src/config.c
src/engine_render.c
src/engine_render.h

- Thicker stripey line, relative to 640x480, so 2560x1440 has a 4x thicker line
- Fix for lines sometimes not rendering at specific angles or when zoomed in

Thicker selection box and fix for lines not rendering

---

src/bflib_guibtns.h
src/gui_tooltips.c

Continuing my war on land tooltips. I hate that every screenshot that someone takes of DK has a land tooltip in it. They're way too pushy and non-immersive.
- Increased land tooltips time to 2.5 seconds
- Land tooltips now require you to keep your cursor even more still
- Land tooltips will no longer display if you're hovering a creature (torture chamber was especially annoying)
Unrelated to land:
- GUI button tooltips now take longer to display the second time you see them (2 seconds instead of 0.5 seconds). I think this feels pretty subtle.
By the way, clicking the 'Query' button and hovering over stuff makes the tooltips display instantly. So you always can use that if you want to see fast land tooltips.

Tooltip time adjustments

---

src/engine_render.c

I believe it makes most sense to hover your cursor over a room to intentionally "inspect" it. Rather than dumping all information on you at all times when you don't need it. This kind of UI is a little intrusive and breaks immersion.
I'm just chilling here and I can't even see the vampire that's in the scavenger room. Half the room is covered by flag:

Only display roomflag for hovered room

---

src/ftests/README.md
src/ftests/ftest.h
src/ftests/tests/ftest_bug_ai_bridge.c
src/ftests/tests/ftest_bug_imp_goldseam_dig.c
src/ftests/tests/ftest_bug_imp_tp_job_attack_door.c
src/ftests/tests/ftest_bug_invisible_units_cant_select.c
src/ftests/tests/ftest_bug_pathing_pillar_circling.c
src/ftests/tests/ftest_bug_pathing_stair_treasury.c
src/ftests/tests/ftest_template.c

- Added enum `FTestActionResult` to make action flow easier to understand.
Now test actions should return FTestActionResult, either (`FTRs_Repeat_Current_Action` or `FTRs_Go_To_Next_Action`) instead of the old way (`true` or `false`).
Old tests that still use `true`/`false` will work, but will generate compiler warnings because action functions should return FTestActionResult
- Updated README.md
- fixed goldseam test, now uses `game.conf.rules.game.gold_per_gold_block` - Introduced in 49a8821db2a5d015b4a653ba7f9e14ef2486fb00

Making test action flow easier to understand

---

campgns/pstunded.cfg
campgns/undedkpr.cfg
lang/campgns/burdnimp/landview_chi.po
lang/campgns/undedkpr/landview_chi.po
lang/campgns/undedkpr/landview_eng.pot
pkg_sfx.mk

Received the following files, this PR makes them used:
[undead.zip](https://github.com/dkfans/keeperfx/files/13794645/undead.zip)
[postundead.zip](https://github.com/dkfans/keeperfx/files/13794648/postundead.zip)

Added Chinese landview speeches for (post) undead campaigns

---

.vscode/create_settings_and_launch_files.ps1
.vscode/defaultlaunch
.vscode/tasks.json

(Windows/VSCode Only)
New file browser dialog to select the KeeperFx.exe Shows upon opening VSCode ONLY when launch.json doesn't exist yet. During copy from defaultlaunch file:
- auto fills "program" and "cwd"
- uncomments "sourceFileMap" and fills with appropriate drive letter (to fix debugger file paths, now it will be able to find files during debugging!)

launch.json file dialog and debugger path fix

---

src/lvl_script_commands.c

because I set external volume on something that did not exist

Fixed a crash on playing internal speeches from script

---

src/power_hand.c
src/sounds.c
src/thing_data.c
src/thing_navigate.c

User reported the game reported he had won level 14 prematurely. This happened because he cast cave-in on the knight, which promptly hid in the hero gate for a second.
This triggered 'IF_CONTROLS' to say the good player controlled no knights, so the map was won.
There is however 2 kinds of limbo:
- Regular limbo (picked up)
- Creature controlled limbo (not on the map for another reason, like hiding in hero gate)
I made sure that IF_CONTROLS only checks regular limbo.

Fixed winning maps by chasing heroes through gate

---

src/player_comptask.c

Computer players would often not use call to arms anymore.
Issue was introduced in this commit: https://github.com/dkfans/keeperfx/commit/50005565e2ac00cbdba9e29de16c17f7a94e98e7
This is not the same:

Fixed Call to Arms not being used

---

config/keeperfx.cfg
src/engine_render.c

I think this is a better balance for what people want. The value is fairly granular by the way, there's a difference between 100, 125, 150. Even 0 is different than 100. But it also depends a little on your zoom level.

Change default line box size

---

src/lvl_script_commands.c
src/lvl_script_value.c

- Made final param of RANDOMISE_FLAG optional
- If final value of RANDOMISE_FLAG is not given or set to 0, it uses the current value as the max.
- Made final param of COMPUTE_FLAG optional
Example:
```
REM Kill a random amount of the players dragons, but keep at least 2 alive.
SET_FLAG(PLAYER0,FLAG2,2)
COMPUTE_FLAG(PLAYER0,FLAG3,SET,PLAYER0,DRAGON)
RANDOMISE_FLAG(PLAYER0,FLAG3)
COMPUTE_FLAG(PLAYER0,FLAG3,DECREASE,PLAYER0,FLAG2)
IF(PLAYER0,FLAG3 > 1)
KILL_CREATURE(PLAYER0,DRAGON,ANYWHERE,1)
ADD_TO_FLAG(PLAYER0,FLAG3,-1)
ENDIF
```

RANDOMISE_FLAG can use current flag value as max

---

src/main.cpp
src/sounds.c

External sound filenames only cleared when exiting a game

---

src/frontmenu_options.c
src/game_legacy.h
src/lvl_script.h
src/lvl_script_commands.c
src/lvl_script_commands.h
src/main.cpp
src/sounds.c

To test use these files:
[audio-numbers.zip](https://github.com/dkfans/keeperfx/files/14103502/audio-numbers.zip)
And add this script to a map:
```
IF(PLAYER0,GAME_TURN > 0)
PLAY_MESSAGE(PLAYER0,SPEECH,"1.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"2.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"3.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"4.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"5.wav")
ENDIF
IF(PLAYER0,GAME_TURN > 100)
PLAY_MESSAGE(PLAYER0,SPEECH,"6.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"7.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"8.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"9.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"10.wav")
ENDIF
IF(PLAYER0,GAME_TURN > 200)
PLAY_MESSAGE(PLAYER0,SPEECH,"11.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"12.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"13.wav")
PLAY_MESSAGE(PLAYER0,SPEECH,"14.wav") …
```

Raised maximum amount of external sounds from 7 to 32

---

src/lvl_script_commands.c
src/lvl_script_lib.h

Following the recent implementation of ``SET_PLAYER_MODIFIER`` this second command aims to add more flexibility for scripting, like ``ADD_TO_FLAG`` it adds value to choosen modifier. Accepts ``ALL_PLAYERS`` and negatives numbers.

Script command ADD_TO_PLAYER_MODIFIER

---

src/frontmenu_ingame_evnt.c

or any other other unit without an icon configured

Fixed a crash when displaying FLOATING_SPIRIT in battle menu

---

src/creature_states.c

Currently it only plays hounds fighting sound, this PR allows any creature with the job to use their own fighting sound.
To test it have a creature with SEEK_THE_ENEMY primary job and tunnellers digging around your walls, usually the hound bark at the walls.

No longer hardcoded sound for Seek The Enemy job

---

src/thing_effects.c

It seems bile demons in groups did a lot less damage in the original game compared to now, starting with this commit from 0.4.5: https://github.com/dkfans/keeperfx/commit/ef8653a1c134790ef41cfa08a7907c4bfb529b75
Original game:
KeeperFX:
KeeperFX with this PR:
Based on this fight:

Nerfed poison gas to be similar to original game

---

src/thing_stats.c

A shot with negative blow could lead to a crash with attempt at dividing by 0, this commit fix it by adding protection against such division. Try ``AreaDamage = 10 8 -128`` on a shot like meteor.

Fix a potential crash with Negative Blow

---

src/creature_states.c

Fix a crash if the rule GameTurnsPerHungerHealthLoss is set to 0 on rules.cfg.
I did a similar thing to https://github.com/dkfans/keeperfx/pull/3012 and simply disable the mechanic if it's set to 0.

Disable HungerHealthLoss if rule is set to 0.

---

config/fxdata/magic.cfg
src/config_rules.c
src/config_rules.h

```
Warning: assign_conf_command_field(line 68): field 'FIGHTMAXLOVE' smaller then min value '0', was '0'
Warning: assign_conf_command_field(line 70): field 'FIGHTHATEKILLVALUE' smaller then min value '0', was '0'
```
Those warnings were triggered by an incorrect minimum setting in config_rules.c and in config_rules.h the variables were mistakenly defined as unsigned when they should actually be signed, [see the variable hates_player in dungeon_data.h](https://github.com/dkfans/keeperfx/blob/master/src/dungeon_data.h#L213). Since hates_player is a short variable, all rule variables related to it should also be defined as short types, at least from my understanding, let me know if I'm wrong!

Fix log warning about "hate" on rules.cfg

---

src/creature_control.h

Instances above 127 couldn't be used in possession due to a limited range of data type.

Fix unuseable instances in possession mode

---

src/main.cpp

Prevent dividing by zero, don't know if that's a good fix tho, I just did the same thing that was done for lightning.

Fix Flame Breath Crash

---

src/thing_creature.c

Currently when a creature grow up it's a whole new creature, it doesn't look good.
This PR makes it so the new creature get to remember its own past, this includes the blood type, creature name, kill count, joined age/creation turn and the carried gold. This will stop the evolving creature to drop its carried gold too, so if you think this should be configurable let me know (some people may dislike the change?)...

Grow up carry over data and gold

---

src/engine_render.c

Fixes this flipped ? that happens when they are dragged east:

Do not flip non-rotatable sprites

---

lang/campgns/burdnimp/landview_spa.po
src/thing_creature.c

If you convert a creature that is behind (or ahead) or paydays he would take the paydays from your dungeon. This is now fixed and he forgets all missed paydays when converted.

Creatures changing owner forget advanced and missed paydays

---

config/fxdata/magic.cfg
src/config_magic.c
src/config_magic.h
src/thing_shots.c
src/thing_shots.h

In the past arrows were not strength based so would never miss. This last part is now restored.

Added a NeverBlock shot property and set it on shot arrow

---

src/lvl_script_commands.c
src/power_hand.c
src/power_hand.h

Use it like this:
`SET_HAND_RULE(PLAYER0,ARCHER,RULE1,DENY,DROPPED_TIME_LOWER,60)`
Would stop a unit from being picked up within 3 seconds after it was last dropped from hand

Hand rule to not pick up dropped creatures

---

src/config_strings.c
src/map_locations.c
src/map_locations.h

How to use:
```
REM Add a red bile demon to blue's cta.
ADD_CREATURE_TO_LEVEL(PLAYER0,BILE_DEMON,CTA[PLAYER1],1,1,1)
QUICK_OBJECTIVE(1,"See blue casting Call to Arms",CTA[PLAYER1])
```
Is only active when Call to Arms is cast, does not update
Also changed the combat location to have a [player] 
```
REM Add a red bile demon to blue's fighting
ADD_CREATURE_TO_LEVEL(PLAYER0,BILE_DEMON,COMBAT[PLAYER1],1,1,1)
QUICK_OBJECTIVE(1,"See the fighting",COMBAT[PLAYER1])
```
They both work without the [player] bracket, then they will take MY_PLAYER_NUMBER. On Multiplayer games it takes player0 and throws an error message.

Added 'CTA' script location

---

src/main.cpp

haven't tested anything about it, but noticed this loop that didn't clear the 3 new extra players

make clear_active_dungeons_stats also loop trough new players

---

config/fxdata/rules.cfg
config/fxdata/trapdoor.cfg
src/config_rules.c
src/config_rules.h
src/config_trapdoor.c
src/config_trapdoor.h
src/cursor_tag.c
src/lvl_script_commands.c
src/magic.c
src/packets_input.c
src/player_instances.c
src/thing_traps.c

This allows for much more flexibility for mapmakers. A possibility where say, mines can be stacked 9 per slab, but lightning traps cannot.
Also removed the need for a hardcoded boulder.

PlaceTrapsOnSubtiles now a trap property instead of a game rule

---

src/engine_render.c

doesn't address the root cause of #3233 but mitigates some of the slowdown

break infinite chain in render code

---

config/fxdata/trapdoor.cfg
src/creature_states_combt.c
src/creature_states_combt.h
src/thing_shots.c
src/thing_traps.c

also stopped traps from getting triggered while creature is being dropped. And documented trapdoor.cfg.

Units will attack traps they trigger when they can

---

src/power_hand.c

Transparency_flags 1 and 2 now also work for the PowerGrab sprites of creatures

more in-hand transparency options

---

src/creature_jobs.h
src/creature_states_mood.c

Has creatures stop doing the job when Must Obey is disabled

Stop doing jobs when no longer forced

---

src/lvl_script_commands.c
src/lvl_script_conditions.c
src/lvl_script_lib.h

Allows players to query where the player is looking. Example:
```
IF(PLAYER0,GAME_TURN>=60)
IF(PLAYER0,VIEW_TYPE == 1)
ZOOM_TO_LOCATION(PLAYER0,PLAYER1)
ENDIF
ENDIF
```

Added VIEW_TYPE script variable

---

src/map_events.c
src/map_events.h

Prevents players missing these messages on possession maps.

Information messages do not time out in possession/map view

---

config/fxdata/objects.cfg
config/fxdata/trapdoor.cfg
src/config_effects.c
src/config_trapdoor.c
src/config_trapdoor.h
src/creature_control.c
src/creature_graphics.c
src/creature_states.c
src/creature_states_tortr.c
src/engine_redraw.c
src/engine_render.c
src/lvl_script_commands.c
src/magic.c
src/main.cpp
src/packets_input.c
src/player_instances.c
src/power_hand.c
src/sounds.c
src/thing_creature.c
src/thing_data.h
src/thing_doors.c
src/thing_effects.c
src/thing_objects.c
src/thing_shots.c
src/thing_traps.c

```
- Added flame fields on traps, same as on objects
- Depleted traps do not show the flame
- Can be configured with SET_TRAP_CONFIGURATION
- Works with custom sprites
- SET_TRAP_CONFIGURATION has extra field: 
SET_TRAP_CONFIGURATION([trapname],[property],[value],[second value]*,[third value]*,[forth value]*)
- Fixed a bug introduced recently where all enemy traps are visible in straight view
- Fixed SET_OBJECT_CONFIGURATION not taking 4th param of FlameAnimationOffset
- Fixed bug where already existing TransparencyFlags field in trapdoor.cfg was not functional
- SET_TRAP_CONFIGURATION TransparencyFlags now take the same values as on objects
- Named a rendering flag
- Refactored some transparency flag setting and clearing
```

Flames on traps

---

src/config.c
src/engine_arrays.c
src/engine_textures.c
src/front_credits.c
src/front_fmvids.c
src/front_landview.c
src/front_simple.c
src/front_simple.h
src/front_torture.c
src/frontend.cpp
src/game_heap.c
src/game_saves.c
src/lvl_filesdk1.c
src/main.cpp

- Removed all checks for the disk availability (since we do not work with cd's)
- Show the 'No CD' screen when it is missing the first 'launcher' screen.
- If you alt-tab and complete installation with the launcher it will actually proceed and continue with booting up the game
- Show a clearer error message when you try to boot up without having completed the keeperfx installation
- Seriously reduced the amount of time the game 'hangs' on the no disk screen
- Added Escape as a possible key to close the screen

Show ?-screen when installation is not complete

---

src/thing_shots.c

Currently in [thing_shots.c#L125](https://github.com/dkfans/keeperfx/edit/master/src/thing_shots.c#L125) ``compute_creature_attack_spell_damage`` use shotng as argument, this is incorrect: shotng may not share the same index as castng, it is an issue for StrengthBased shots with AreaDamage.

Fix a potential issue with detonating shot damage calculation

---

src/dungeon_data.c
src/game_loop.c
src/thing_creature.c
src/thing_creature.h

Fixes #3151
It reverts and reimplements #2259, which caused maps to be won as soon as the final blow was struck on the hearth.
To test this PR:
- Make sure DUNGEON_DESTROYED and ALL_DUNGEONS_DESTROYED now behave like they did in the original game. I believe they should trigger when the hearth bell actually explodes.
- Make sure that when a player has 2 dungeon hearts, the first one can be destroyed and the second one will become functional. A floating spirit is created briefly as a visual effect.

Maps are only won when the heart explodes

---

src/lvl_script.c

This is needed for certain levels to work in KeeperFX without editing the script.

Discard only excess parameters in script commands

---

config/fxdata/keepcompp.cfg
src/player_compchecks.c
src/player_computer.c
src/player_computer.h

Param3 was used for both 'min creatures' and 'min hate', that conflicts. I do not believe hate is needed there.
Fixes #2680

Reworked 'CHECK FOR QUICK ATTACK'

---

src/magic.c

Keeper powers targeting enemy creatures now follow the same rules as creatures do when looking for something to attack. This fixes an issue that yellow creatures on a map without a yellow keeper could not be targeted with a chicken or disease power.
Fixes #3365

Keeper powers target keeperless creatures

---

src/bflib_basics.c
src/bflib_basics.h
src/bflib_datetm.cpp

Fixes #3379
The problem is now that the log doesn't record the date it was created, but that is infinitely preferable to the game crashing before it's even loaded.

Fixed year 2038 crash

---

src/frontmenu_ingame_tabs.c

Fixes what I did here: dd2005d
Old way would not open messages belonging to events beyond index 15, which happens when a lot of buttons show up in a short time.

E button now opens correct message always

---

src/ariadne.c
src/ariadne.h
src/ariadne_navitree.c
src/ariadne_regions.c
src/ariadne_tringls.c
src/ariadne_tringls.h
src/globals.h
src/map_data.c
src/map_data.h

partial fix for #3389 
in current state orange still fucked, but purple/black should be ok

fix doors pathing for purple/black

---

src/power_hand.c

Fixes #1939
The light was deleted when the creature was placed in hand, then recreated and light intensity increased when dropped. However, computers do not really take creatures in hand. They have a fake hand. In both cases though the creature ends up in limbo, so the light is deleted there.
Possible side effect would be that illuminated heroes fleeing into hero gates from cave in to lose their light too.
EDIT:  Heroes fleeing through gate unchanged, that is 'creature_controlled_limbo', totally different.

Stop ILLUMINATED from going haywire

---

src/front_landview.c
src/game_merge.c

The level that comes 2 weeks after a full moon, on campaigns that support those.
Needs https://github.com/dkfans/FXGraphics/pull/70

Distinct landview marker for New Moon levels

---

src/front_input.c
src/frontend.cpp
src/frontmenu_ingame_tabs.c

In the define keys menu, the user would press right shift/ctrl/alt to use on the one-click room commands and it would accept it as the general 'shift/control/alt', but then ingame would only accept pressing the left key. Now it accepts either.
Fixes #3415

Allow the use of the right keys for one-click

---

src/room_util.c

If the CHANGE_SLAB_TYPE script command is used to change a room slab into another room slab, it would leave the old room present in the slab information.
Function `do_slab_efficiency_alteration` would do this:
```c
struct SlabAttr* slbattr = get_slab_attrs(slb);
if (slbattr->category == SlbAtCtg_RoomInterior)
{
struct Room* room = slab_room_get(sslb_x, sslb_y);
```
And find a room of type NULL, causing several log errors and related issues, possibly also player notifications when the room was destroyed.
This PR cleans that up.
To reproduce the original issue:
1) Run this map: [map30117.zip](https://github.com/user-attachments/files/16740693/map30117.1.zip)
2) Press `~` to see logging
3) Wait for 140 gameturns to see rooms get replaced
-> Notice a `!` message that says a room is destroyed, …

Prevent CHANGE_SLAB_TYPE from leaving room information on slabs

---

src/lvl_script_commands.c
src/player_computer.c
src/player_computer.h
src/thing_list.c

So:
```
IF(PLAYER0,GAME_TURN > 200)
COMPUTER_PLAYER(PLAYER1,0)
ENDIF
```

Allow computer players to be set within IF-statement

---

libexterns.mk
prebuilds.mk

- Updated SDL2 from 2.28.5 to 2.30.6
- SDL mixer, net and image are still up-to-date

Update SDL2 libs to latest version

---

src/map_events.h

Not sure what the ideal number is, but the current number of 100 is too few for the largest and busiest maps, resulting in events not being triggered.

Decupled EVENTS_COUNT

---

src/config_creature.c
src/config_creature.h
src/config_crtrmodel.c
src/creature_states_mood.c
src/creature_states_scavn.c
src/lvl_script_commands.c
src/thing_list.c
src/thing_stats.c
src/thing_stats.h

Creature stats may change after SET_CREATURE_CONFIGURATION or after SWAP_CREATURE
In case of health, speed and lair totems, the updated creature stat did not update the value of individual creatures. Now for speed and health they do, and lairs get removed causing them to remake a lair.
If you swap out a creature that keeps a lair model, the lair is not destroyed.

Health, Speed and LairObject updated when stat changes

---

src/config_crtrmodel.c
src/creature_jobs.c
src/creature_states_gardn.c

Prevent creatures with LairSize = 0 or HungerRate = 0 from being forced to build a lair or eat when dropped in the relevant room
Now, dropped creatures require LairSize > 0 and HealRequirement > 0 to build a lair
and dropped creatures require HungerRate > 0 and HungerFill > 0 to eat 
Additionally, the default TokenRecovery value is set to 0 to prevent creatures with LairSize > 0 from accidentally attempting token recovery

no force feed sleep for needless creatures

---

lang/gtext_chi.po
lang/gtext_cht.po
lang/gtext_cze.po
lang/gtext_dut.po
lang/gtext_eng.pot
lang/gtext_fre.po
lang/gtext_ger.po
lang/gtext_ita.po
lang/gtext_jpn.po
lang/gtext_kor.po
lang/gtext_lat.po
lang/gtext_pol.po
lang/gtext_rus.po
lang/gtext_spa.po
lang/gtext_swe.po
src/config_strings.h

Changes:
239 - Bad string for a SELF_BUFF, so fixed
654 - the 'Monster' part means you target another. Removed LMB so it can be used for a RANGED SPEED creature spell buff
655 - the 'Monster' part means you target another. Removed LMB so it can be used for a RANGED PROTECT creature spell buff 
656 - the 'Monster' part means you target another. Removed LMB so it can be used for a RANGED INVISIBILITY creature spell buff 
1053/1056 - Gave it a different name so it is distinct from flight SELF_BUFF.
1066 - Quite similar to 'heal' keeper power, but added 'Monster' to match other spell/power names with monster in it to target others. This instead of changing the keeper power to HEAL MONSTER too.
1067/1068 - cleanse creature spell which is hopefully a creature spell soon
1069/1070/1071 - …

Add strings for new spells and door

---

src/thing_stats.c

Would revert this commit:
https://github.com/dkfans/keeperfx/commit/0eb6c985d07f64f9121bf84f92741e467538069d#diff-a8e1351154215ba628dff88df33ab7d49f14f9e722d37cbdcee817941bedb50e

Restore magic door resistance to original value

---

src/bflib_basics.c
src/bflib_basics.h
src/config.c
src/config.h
src/config_creature.c
src/config_cubes.c
src/config_magic.c
src/config_objects.c
src/config_trapdoor.c
src/console_cmd.c

The original config file loaders written by @mefistotelis have been sufficient until now. After many changes we finally managed to break the camel's back, so to speak.
Up until now config files were parsed by scanning for specific block sections. This worked reasonably well until the addition of thousands new block sections. I added a new iterator function that goes through the config file and returns the name of each block encountered.
After upgrading the worst offenders, load time in my tests has gone down from 14 to 3 seconds. Results may vary depending on system specifications.

Load config files faster

---

src/lvl_script_value.c
src/magic.c
src/magic.h
src/packets_input.c
src/player_comptask.c
src/thing_traps.c

some spots had allow_flags and mod_flags in the same field while these are clearly 2 different things
PwCast_CustodyCrtrs and PwMod_CastForFree would've conflicted with each other

split allow_flags and mod_flags

---

src/creature_states_combt.c

A lot of warning message of "Unrecognized spell kind" coming from creature_affected_by_spell().
The spell kind parameter is set at the index 0 of func_params[] of InstanceInfo, not 1.
Type: Bug Fix

Fix warning of "Unrecognized spell kind"

---

src/config_magic.h

Maybe I'm wrong but I think ``MAGIC_OVERCHARGE_LEVELS`` isn't correctly defined in config_magic.h with the recents changes.
Close this PR if i'm wrong.

Fix MAGIC_OVERCHARGE_LEVELS?

---

src/lvl_script_commands.c
src/thing_creature.c
src/thing_creature.h

Recalculate Players Digger/ctr Lists on typechange

---

src/lvl_script.c

Implements #3577
When a string variable happens to be a number, drawfrom accepts ranges from it.

DRAWFROM command now handles string ranges

---

CMakeLists.txt
CMakePresets.json

* Use LLD as linker
The default bfd linker in MinGW is extremely slow. The final linking seems to run forever.
On the other hand, LLVM linker (LLD) can complete in 1 second. Someone said we shouldn't link gcc if we use LLD, so I remove the linking of gcc.
* Remove INTERPROCEDURAL_OPTIMIZATION because it causes linking error on _WinMain().
* Remove linking of SDL2Main because we have WinMain in main.cpp.
* Enable verbose for standard build.
* Fix wrong display name of Release-MinGW32-Standard.
Type: Bug Fix
Change-Id: I0322fc7b4d851515e07732e18040e30893b98060

Fix Release mode in CMake

---

config/creatrs/imp.cfg
src/config_crtrmodel.c
src/creature_control.h
src/creature_states_prisn.c
src/creature_states_tortr.c
src/lvl_script_commands.c

```
; Defines the kind of creature it will become if it dies of starvation while imprisoned.
; Setting this to NULL will check if the creature has the 'HUMANOID_SKELETON' property and will default to the room creature creation specified in terrain.cfg.
PrisonKind = NULL
```
```
; Defines the kind of creature it will become if it dies from torture.
; The same rule applies as above, except it does not consider the 'HUMANOID_SKELETON' property.
TortureKind = NULL
```

Prison & Torture Kind per creature, 2 new fields on the creature config file

---

src/creature_control.h
src/thing_data.h

use correct datatype for a field that is THINGS_COUNT*CREATURES_COUNT times in the game struct saves about 8mb on save files

use ThingIndex for wind_affected_creature

---

CMakePresets.json
launch.vs.json

* It seems that "intelliSenseMode" should be windows-clang-x86.
* Modify the setupCommands of gdb to make the variables more readable in the debugger window. Without "enable-pretty-printing", they are almost not comprehensible.
The launch.vs.json can be put in the root or .vs folder. Both locations are okay.
Developer should change "currentDir" and "cwd" to the actual game folder. The "miDebuggerPath" might need to be changed, too.
Type: Bug Fix

Improve debugging experience of CMake

---

src/creature_control.h
src/globals.h
src/thing_data.h

should have no functional impact, just used a wrong type, still needed to be a ushrt in both cases though

fix type CctrlIndex

---

src/console_cmd.c
src/keeperfx.hpp
src/lvl_script_value.c
src/room_entrance.c
src/thing_creature.c

Recently I made it possible to add a negative amount of creatures to a pool, but it would break down at '-1' amount added.
This PR makes '-1' possible, completely simplifies the function, and makes it possible to get to negatives with the console commands too.

Fixed -1 amount of creatures to pool

---

config/creatrs/imp.cfg
src/engine_render.c

No Health Flower For Allied Unconscious

---

src/config_settings.c
src/globals.h

Make sure game settings are somewhat acceptable before using them. If for example minimap_zoom is loaded as zero, players won't be able to zoom out their minimap anymore.

Perform sanity check after loading game settings

---

src/power_hand.c
src/spdigger_stack.c
src/thing_corpses.c
src/thing_corpses.h
src/thing_creature.c

The original names were done by me too, but this seems more applicable.

Renamed death states and used enums for animations

---

config/fxdata/creature.cfg
levels/classic_cfgs/creature.cfg
levels/legacy_cfgs/creature.cfg
src/creature_instances.c
src/creature_instances.h

- Speed only cast when heroes non-idle
- Invisibility also cast outside of combat
- Flight no longer cast when idle in water
- Wind on classic/legacy no longer used when facing several melee attackers

Restore some instance behaviors that got changed when validate functions were introduced

---

src/lvl_script_commands.c
src/lvl_script_commands_old.c
src/lvl_script_conditions.h
src/lvl_script_lib.h
src/main.cpp
src/player_instances.c
src/player_instances.h
src/room_util.c
src/thing_list.c

- `PLACE_DOOR([player],[door],[slb_x],[slb_y],[locked],[free]`
- All USE_POWER_* script commands (5 of them) can now use strings for [free] block too
- [free] allows `0 / 1` or `PAID / FREE`.
- Placing a door 'PAID' means you should be able to subtract a door from the player, free it places it anyway.
- Fixed pathfinding to be correctly updated by level scripts

Implemented PLACE_DOOR script command

---

config/creatrs/imp.cfg
src/config_creature.h
src/config_crtrmodel.c
src/dungeon_data.h
src/lvl_script_commands.c
src/lvl_script_value.c
src/map_locations.c
src/map_locations.h
src/thing_creature.c

Added new meta location `LAST_DEATH_EVENT[player]` that holds the location of the last creature to die with the `EVENTFUL_DEATH` creature property.
Can be used to spawn objects/effects through script at the location of the death, or point objectives to it.

Added Eventful death meta location

---

src/creature_groups.c
src/creature_states_hero.c

When parties spawn they will wait 400 turns always, in addition to the countdown. Now you can set a negative countdown, to have a party wait less than 400 turns in total.
Naturally setting the countdown smaller than -400 has no further effect.

Allow negative countdown values on `ADD_TO_PARTY`

---

config/fxdata/trapdoor.cfg
src/config_trapdoor.c
src/config_trapdoor.h
src/lvl_script_commands.c
src/player_instances.c
src/thing_traps.c
src/thing_traps.h

Two new properties for traps: ``InstantPlacement`` & ``RemoveOnceDepleted``.
```
; Place the trap immediately without needing imps to drag the crate to arm it.
InstantPlacement = 0
; Destroy the trap once it runs out of Shots.
RemoveOnceDepleted = 0
```
Good for tower defense map.
NOTE:
I messed up with my own experimental build and merged it onto the original branch of this PR.
So I closed the previous PR, deleted the branch and made a new one, sorry for the inconvenience... 🫨

Traps: InstantPlacement & RemoveOnceDepleted

---

src/lvl_filesdk1.c
src/thing_doors.c
src/thing_doors.h

Fixes #3723
Keys placed on secret doors are invisible, unless the secret door is revealed for you or it is your door.

Hide keys when locking secret doors

---

src/front_input.c
src/frontend.cpp
src/packets.c
src/packets_input.c

In DK1 it is possible to charge spells on the battle menu. This broke in #1342
Restored the original behavior.

Fixed spell charging in battle menu

---

src/config_creature.c

Campaigns creature.cfg config with QUICK or any future deprecated property should now still work correctly.

CreatureCFG compat fix

---

src/config_effects.c
src/config_effects.h
src/creature_states.c
src/game_loop.c
src/keeperfx.hpp
src/lvl_script.c
src/lvl_script_commands.c
src/magic.c
src/main.cpp
src/power_process.c
src/power_specials.c
src/thing_corpses.c
src/thing_creature.c
src/thing_data.h
src/thing_effects.c
src/thing_effects.h
src/thing_objects.c
src/thing_shots.c
src/thing_stats.c
src/thing_traps.c

Shots that exploded to create effects would take the damage from the Word of Power shot or Word of Power Trap shot depending on if it was a trap or not that created it. Now it takes it from the actual shot that created the effect.

Area affect damage from correct shot

---

config/fxdata/trapdoor.cfg
src/api.c
src/config_trapdoor.c
src/config_trapdoor.h
src/dungeon_data.h
src/lvl_script_commands.c
src/lvl_script_conditions.c
src/lvl_script_lib.c
src/lvl_script_lib.h
src/thing_data.h
src/thing_traps.c

Added a new script flag: `TRAP#_ACTIVATED`, where the # is a number between 0 and 255 from `FlagNumber` on the trap configuration in trapdoor.cfg.
Example:
```
IF(PLAYER0,TRAP3_ACTIVATED >= 3)
QUICK_INFORMATION(1,"There have been 3 boulders activated")
ENDIF
```
From trapdoor.cfg:
```ini
[trap1]
Name = BOULDER
FlagNumber = 3
```

Added a script flag that stores how many times traps are activated

---

src/lvl_script_commands.c
src/lvl_script_conditions.h
src/lvl_script_lib.c
src/lvl_script_lib.h

`ADD_OBJECT_TO_LEVEL([object],[location],[property],[player]*,[orientation]*)`
`ADD_OBJECT_TO_LEVEL_AT_POS([object],[subtile_x],[subtile_y],[property],[player]*,[orientation]*)`
Where orientation are values between 0 and 2047, or the strings used in unearth:

Allow Orientation param in ADD_OBJECT_TO_LEVEL script command

---

config/creatrs/imp.cfg
levels/legacy_crtr/avatar.cfg
levels/legacy_crtr/ghost.cfg
src/lvl_script_commands.c

For `Powers`, `PowersLevelRequired` an `LevelsTrainValues` now the [value] would hold the value, and [value2] holds the slot.
This to more closely match [SET_POWER_CONFIGURATION](https://github.com/dkfans/keeperfx/wiki/Level-Script-commands#set_power_configuration) and the rest of SET_CREATURE_CONFIGURATION.

SET_CREATURE_CONFIGURATION swap [slot] and [value]

---

src/creature_control.h
src/creature_groups.c
src/creature_states_hero.c

Before: When heroes fail their party job, they will try to attack an enemy dungeon heart. If they can't find one they will idle until they do.
Now: When heroes fail their party job:
- If it is defensive they will try to attack enemies (better for maps with secret doors and disconnected dungeons)
- If attack enemies fails, or if it was not defensive, they will switch to attack dungeon heart
- If they cannot find an enemy dungeon heart, they will switch back to their original job
Also, stopped logging all those objective changes unless playing in heavylog.

Hero parties will retry original job after a while

---

src/thing_creature.c

This PR fix this issue: 
Creatures do not use instances with ``SELF_BUFF`` when configured with different ``ValidateSourceFunc`` & ``ValidateTargetFunc`` if the spell lacks spell flags.

Bug fix for instances casting spell with no spell flags

---

config/creatrs/imp.cfg
src/config_creature.c
src/creature_control.h
src/thing_creature.c
src/thing_creature.h

Refactor `update_creature_levels` function by splitting the GrowUp mechanic into two new functions: `grow_up_creature` and `get_random_appropriate_creature_kind`.
Additionally, modify `grow_up_level` to support value of 0 to randomise the level of the grown-up creature.

GrowUp Refactor + Randomise grown-up level

---

src/player_instances.c
src/thing_shots.c
src/thing_traps.c
src/thing_traps.h

Before this, only shooting traps would be activated by slapping.

Make all trap types slappable

---

src/lvl_script_commands.c

SET_BOX_TOOLTIP can be changed in IF-statements

---

src/player_utils.c

Fixes this bug:
On the above image, on a map with this structure (with the red tiles attached to your dungeon), the highlighted slab is explored. Everything inside that open space should remain hidden though.

Fixed initial exploring looking through corners

---

src/thing_creature.c

``'killertng' could be a trap, so verify if it has valid creature control before increasing the kill count and adjusting its anger.``

Fix Trap Anger Issue

---

src/creature_battle.c

a unit in a disconnected dungeon seems common enough that this is just clutter in the log file

supress flee error

---

src/lvl_script_commands.c

Fixes #3905
However, it only fixes impenetrable rock when the command is in an IF statement; it seems that something is re-revealing it when the map loads.

CONCEAL_MAP_RECT now works for players other than PLAYER0

---

src/lvl_script.c
src/lvl_script.h
src/lvl_script_commands.c

By storing offsets instead of pointers in the save file, some of the crashes when loading saves from a different game version is prevented.

Converted script string pointers to offsets

---

src/creature_states_combt.c

Melee enemies with lava in between will no longer shout and do random backwards walking. They will just ignore each other, like they did in DK1. KeeperFX changed this years ago, [here](https://github.com/dkfans/keeperfx/commit/8fe032cd107dc4bf075533d19ed22e1dcfba9705).

Ignore enemies you cannot reach

---

src/frontend.cpp
src/map_events.c
src/map_events.h
src/packets.c
src/packets.h

Fixed an issue with the eye being at (0,0), instead of where the button eye pointed too. It only updated locations of the first 12 out of 1000 events, because it got confused with there being just 12 buttons.

Update all events, not just the first 12

---

src/creature_states.c

Creatures pre-placed with critical health would not make a lair in the first 128 turns, but still counted this as a failed attempt at making a lair. This also caused a further refusal to make a lair for 128 more turns, resulting in more anger and never actually sleeping.
See this map for the bug: [map02899.zip](https://github.com/user-attachments/files/19495878/map02899.zip)
(notice that thieves do not get angry for having no lair. Change that to see it also gets angry real soon).
Now a 'do not check because we just checked' type of situation, does not count as a check.

Fixed infinite sleep loop in first 128 turns

---

config/fxdata/trapdoor.cfg
src/config_trapdoor.c

numbers will still work same as before, just an option to be more readable now

Add named commands for Trigger and ActivationType in trapdoors.cfg

---

src/creature_states.c
src/creature_states_combt.c

Functional alternative to #3970
Proper cleanup of 'creatures leaving' state

Change owner of leaving creatures

---

config/fxdata/keepcompp.cfg
src/lvl_script_commands.c
src/player_compevents.c
src/player_compprocs.c
src/player_computer.c
src/player_computer.h

The MAX_CREATURE script variable determined the lair size the computer tried to make. Meaning that with a portal limit of 100, it would immediately try a 10x10 lair.
As this is suboptimal, now it will build lairs just 1 size larger than the configured size in keepcommp.cfg for the first lair, and then normal sized lairs on top of that for additional lairs when the first is full.
Also fixed expanding lairs/treasure rooms, just the part that recently broke in the computer event refactor.

Computer Players build smaller lairs with huge portal limit

---

config/fxdata/keepcompp.cfg
src/player_compevents.c
src/player_comptask.c
src/player_computer.c

On payday the AI would by default sell 0 workshop items to afford payday, and move 0 gold piles to the treasure room. However, the selling and moving tasks would do the activity the first time before it reached the check how many were left, doing it always one time more than specified.
I moved the number check to _before_ it was executed, so now it will actually do it 0 times.
Also, both of these options used the same param, so if you set it to 5, you would move 6 piles and sell 6 traps. I split it into 2 params for more configurability.
Also documented the params in keepcompp.cfg.

EVENT PAY DAY now has 0 as do it 0 instead 1 times

---

src/player_comptask.c
src/player_computer.c

So, the variables like DOORS_SOLD and MANUFACTURE_GOLD now get filled when the AI sells his traps/doors/crates.
Also fixes the selling the AI does when he has, but cannot build, a workshop.

Fixed Script variables when AI sells doors

---

config/fxdata/keepcompp.cfg
src/player_compchecks.c
src/player_comptask.c
src/player_computer.h

Adds an option to disable this change in legacy keepcommp configs: https://github.com/dkfans/keeperfx/commit/f632a23c41a0b0e2628c5553a3f33a331d62f4db

Option for computers to not slap imps with speed

---

src/creature_states_spdig.c

In this commit it seems some copy-paste mistakes were left in the function: https://github.com/dkfans/keeperfx/commit/3420d7bc3fb81cc034c66a7bd5ad25afcb731907#diff-808ac64e3a6ca746fd17d9ac96e4477955fcedd343555daea934baac42a0dea3R1311
It was checking a library when picking up a corpse.

Fixed creature_picks_up_corpse

---

src/config_objects.c
src/gui_tooltips.c
src/power_hand.c
src/thing_list.c
src/thing_list.h
src/thing_objects.c
src/thing_objects.h

Fixes an issue where an object without a tooltip stacked on top of an object without a tooltip would block the tooltip of the object below.

On stacked objects, show tooltip of any object

---

config/fxdata/magic.cfg
src/config_magic.c
src/config_magic.h
src/thing_shots.c

- PENETRATING shot property no longer allows shots to go through walls. This allows for shots that pierce creatures and rebound of walls.
- PIERCE_WALLS property does allow shots to go through walls
- Strength based shots can now be PENETRATING too when hitting doors..

PIERCE_WALLS shot property

---

config/fxdata/magic.cfg
src/power_process.c
src/thing_shots.c

instead of the 5th power value of power_lightning times 256.

Shots with TrapLightning update logic use MaxRange

---

src/slab_data.c

Fixed bug introduced here:
https://github.com/dkfans/keeperfx/pull/3979/files
Where rooms like this are 100% efficient:

Fixed room efficiency on low slabs

---

src/room_library.c

From the RESEARCH script command documentation:
```
Changes amount of research points needed to discover an item in library. It doesn't affect research order, only amount of points. If the item never was in research list, it's added at end.
```
It was not added to the end. Tested on latest alpha and version 0.4.8.
With this PR it does.

Research script command adds it to the back

---

src/creature_groups.c
src/creature_states.c
src/magic_powers.c
src/player_compevents.c
src/player_comptask.c
src/player_computer.h
src/thing_creature.c
src/thing_creature.h

- Familiars get teleported on Hold Audience
- Familiars that get dropped wait until they stop falling before they consider going back to the summoner
- Captivity will prevent reunification
- Holding a familiar in hand will not break the group and will not spam log

Fixes to summoned Familiar behavior

---

src/creature_states.c

Fixes an issue where angry high level warlocks can persuade a prisoner to leave both prison and the dungeon.

Prisoners do not stay grouped with free creatures

---

config/fxdata/rules.cfg
src/config_rules.c
src/config_rules.h
src/thing_stats.c

Allows mapmakers to easily make training slower, or scavenging faster.

Implemented rules for the work values

---

config/fxdata/magic.cfg
src/creature_graphics.c
src/creature_states.c

When a party leader is far away, the party members may travel 200% the speed of the leader to catch up. When they are quite far, they may move at 125% speed.
Now, when the natural speed of the follower is faster than that catch-up speed, the follower may move 125% (far) or 100% of his own speed instead.
So, a Samurai following a Giant, will now catch up faster, and would no longer be limited to being twice as fast as the giant.
Also very useful for slow druids with fast bird familiars.

Party members rejoin slow party leader faster

---

src/packets_input.c

Fixed tile being tagged when right-clicking to cancel drag-tagging

---

src/lvl_script_commands.c

This broke the original campaign tutorial flashing buttons.

Removed TUTORIAL_FLASH_BUTTON duration check

---

src/console_cmd.c
src/engine_redraw.c
src/front_input.c
src/front_input.h
src/gui_boxmenu.c
src/packets.c

add optional entry for cheat menu in console command.
especially for the creature cheat menu, avoid having to enter possession mode to activate it.
optimize spell text info when everything as free.
show charging level instead of none when cost is zero.
fix the issue where selecting the cheat menu options would result in additional spellcasting behavior.
typically, avoid additional attack behavior when selecting the instance cheat menu options in possession mode.
fix the issue of FPInstantCast=1 instance not working in the instance cheat menu.

Optimize for cheat menu

---

src/lua_api_things.c
src/power_hand.c
src/power_hand.h

Creatures that were in hand and deleted from lua would bug out the hand.
To test the bug, run a map with this lua script and pick up an avatar within 200 game turns:
```lua
function OnGameStart()
DeleteAvatarWithTimer()
end
function DeleteAvatarWithTimer()
local creatures = GetCreatures()
for index, creature in ipairs(creatures) do
if creature.model == 'AVATAR' then
local trigger = RegisterTimerEvent(function (currentTurn, triggerData) triggerData.avatar:delete() end, 200, false)
trigger.triggerData.avatar = creature
end
end
end
```
With this PR it is cleared from hands.

Lua: Thing that gets deleted is removed from hand

---

src/bflib_basics.c
src/main.cpp

Uses `keeperfx_host.log` for logging when `-server` is used as a launch argument and uses `keeperfx_client.log` for logging when `-connect` is used as an argument.

Use separate log files for host and client

---

src/main.cpp
src/net_sync.c
src/net_sync.h
src/packets.c
src/packets.h
src/packets_misc.c
src/player_utils.c
src/room_util.c
src/thing_list.c
src/thing_list.h

I've centralized all the multiplayer checksum computing to be done all at once, instead of being scattered throughout the codebase. I put them in `net_sync.c`, which is where they should be, and added a function called `compute_multiplayer_checksum_sync`, which is called in `update()`. This will make it all easier to understand and much cleaner.
It perhaps even avoids a bug where we compute checksum for a Thing and then another function later changes the Thing. For example:
Old:
1. update_things and checksums for things
2. update_rooms and checksums for rooms
3. update other stuff <--- maybe a function here also modifies a Thing, so its original checksum calculation becomes moot.
3. exchange_packets_and_do_network_stuff
New:
1. update_things
2. update_rooms
3. update_other_stuff
4. update …

Refactor multiplayer checksum sync code

---

src/main.cpp

`-log blah.log`
So use these when self-joining multiplayer in same game directory:
```
"C:\Games\Dungeon Keeper\keeperfx.exe" -log keeperfx-server.log -server -campaign keeporig -level 50
```
```
"C:\Games\Dungeon Keeper\keeperfx.exe" -log keeperfx-client.log -connect localhost
```

Added launch argument for specifying log filename

---

src/main_game.c
src/packets.h
src/packets_misc.c

I introduced a desync when I added the new seeds, so this should hopefully fix it.
Also cleaned up `init_seeds()`

Fix initial seed desync in multiplayer

---

src/main.cpp

Dragonlich had some performance concerns, this might fix that. But it's a good change regardless. I had a look and noticed that the first creatures on a map have their index start out very high, at the limit of 8191 (allocating in reverse order), this is easy to change just by reversing the list of available indices. I also printed all the values in a logging test to be sure this change isn't "off by 1".
If it doesn't improve performance then worse performance is most likely because we upped the `THINGS_COUNT` to 12288 (8192+4096) and there's a lot of loops in the game which loop through those 12k things a few dozen times every gameturn.

Utilize low indices instead of high indices

---

src/bflib_network.cpp
src/bflib_network.h
src/custom_sprites.c
src/custom_sprites.h
src/front_network.c
src/main.cpp
src/net_sync.c
src/packets.c
src/packets.h

there's definitely way more you could do with checksumming lots of files, but I'm only bothering with checking the filecount here.
I've also standardized the `get_host_player_id` method.

Make multiplayer instantly notify you if the custom sprite zip counts are different between players
